---
sidebar: sidebar 
permalink: add-ha-pairs.html 
keywords: add high-availability pairs, add HA pairs, add HA pair, add high-availability pair, scale out, file system, fsx for ontap 
summary: BlueXP  ワークロード工場内のファイルシステムにハイアベイラビリティペアを追加して、ファイルシステムをスケールアウトします。 
---
= BlueXP  ワークロード工場内のファイルシステムにHAペアを追加
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ハイアベイラビリティ（HA）ペアを追加して、BlueXP  ワークロード工場にFSx for ONTAPの第2世代シングルAZファイルシステムをスケールアウトすることで、パフォーマンスと容量を向上できます。この拡張により、第1世代のファイルシステムに比べてパフォーマンスの拡張性と柔軟性が向上します。

.タスクの内容
新しいHAペアは、HAペアごとに同じSKUと同じ容量を使用して追加されます。

HAペアの追加は、次の項目ではサポートされません。

* 複数のAZのHA環境または第1世代のFSx for ONTAPファイルシステム
* 5台以上のStorage VMで構成されるFSx for ONTAPファイルシステム
* iSCSI LUNを使用するFSx for ONTAPファイルシステム
* SSDの最大容量または最大容量に近い構成、またはIO割り当て制限に達した構成


HAペアの追加については、次の点を考慮してください。

* HAペアの削除：ファイルシステムに追加したHAペアを削除することはできません。
* 処理時間と制限事項：HAペアの追加には約30分かかることがあります。HAペアの追加は、メンテナンス時間中やアクティビティが少ない時間帯に検討してください。また、HAペアを追加すると、HAペアの追加、IOPSのプロビジョニング、SSD容量の拡張、スループット容量の更新など、その他の処理も制限されます。
* IO割り当て：自動IO割り当ては、ストレージ容量の合計によって異なります。ユーザ設定のIO割り当てにHAペアの追加容量を掛けます。
* NVMeキャッシュ：HAペアを追加する場合、NVMeキャッシュはデフォルトで有効になります。負荷の高いワークロードの場合はNVMeキャッシュをオフにすることを推奨します。
* HAペアの数：ファイルシステムを偶数個のHAペアに拡張して、HAペア間でバランスのとれたデータ分散を実現することを推奨します。
* LUNの作成：第2世代のシングルAZファイルシステムでは、HAペアの追加時にファイルシステムにLUNが存在していない場合にのみLUNを作成できます。LUNの作成は、HAペアが6つ以下のファイルシステムでのみサポートされます。


.開始する前に
ファイルシステムにHAペアを追加する前に、次の手順を実行します。

* すべてのiSCSI LUNを削除して、ファイルシステムをスケールアウトします。
* ファイルシステムに含まれるStorage VMが5個以下であることを確認してください。


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. [FSx for ONTAP *]タブの*[Information]*で、*[HA Pairs]*の横にある鉛筆アイコンを選択します。
. [HAペアの追加]*ダイアログで、ファイルシステムに追加するHAペアの数を選択します。
. [追加]*を選択して、HAペアの追加を確定します。


.結果
ワークロードファクトリによって、ファイルシステムにHAペアを追加するプロセスが開始されます。HAペアが追加されるまで、ファイルシステムはボリューム作成などの他の処理に使用できません。処理の進行状況は* Tracker *タブで監視できます。
