---
sidebar: sidebar 
permalink: cascade-replication.html 
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume 
summary: データ保護ボリュームをレプリケートするか、ボリュームデータのレプリケーションをカスケードして、データ保護を3次システムに拡張したり、データを移行したりできます。 
---
= BlueXP  ワークロード工場でデータ保護ボリュームをレプリケート
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
データ保護ボリュームをレプリケートするか、ボリュームデータのレプリケーションをカスケードして、データ保護を3次システムに拡張したり、データを移行したりできます。

.タスクの内容
BlueXP  ワークロードファクトリでは、データ保護ボリュームのレプリケートがサポートされています。ONTAPでは、データ保護ボリュームのレプリケートは_mirror-mirrorカスケード構成_とみなされます。ミラー-ミラーカスケード構成の関係のチェーンでは、ソースボリュームがセカンダリボリュームにミラーリングされ、そのセカンダリボリュームが3番目のボリュームにミラーリングされます。セカンダリボリュームが使用できなくなった場合は、新しいベースライン転送を実行せずに、プライマリボリュームと3番目のボリュームの間の関係を同期できます。

この機能は、ONTAPバージョン9.6以降のFSx for ONTAPファイルシステムでサポートされます。を参照してください link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships["互換性のあるONTAPバージョンのONTAPドキュメント"^]。


NOTE: 関係のソースボリュームがデータ保護ボリュームであり、別の関係のターゲットである場合、レプリケーション関係を反転することはできません。

.開始する前に
カスケード構成に含まれるボリュームの再同期には時間がかかることに注意してください。

[role="tabbed-block"]
====
.単一のボリュームをレプリケート
--
データ保護（DP）ボリュームをレプリケートできます。


NOTE: データ保護ボリュームのレプリカが1つサポートされます。DPボリュームの2つ目のレプリカは作成できません。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、[Go to storage inventory]を選択します。
. [FSx for ONTAP ]タブで、更新するファイルシステムの3ドットメニューを選択し、[Manage]を選択します。
. Volumes （ボリューム）タブを選択します。
. データ保護ボリューム（DP /レプリケートボリューム）の3ドットメニューを選択し、*[ボリュームデータのレプリケート]*を選択します。
. [Create replication]ページの[Replication target]で、次の情報を指定します。
+
.. * FSx for ONTAPファイルシステム*：対象となるFSx for ONTAPファイルシステムのクレデンシャル、リージョン、FSx for ONTAPファイルシステム名を選択します。
.. * Storage VM名*：ドロップダウンメニューからStorage VMを選択します。
.. *ボリューム名*：ターゲットボリューム名は次の形式で自動的に生成されます `{OriginalVolumeName}_copy`。自動生成されたボリューム名を使用するか、別のボリューム名を入力できます。
.. *ユースケース*：レプリケーションのユースケースとして、次のいずれかを選択します。
+
*** 移行：ターゲットのFSx for ONTAPファイルシステムにデータを転送
*** ホットディザスタリカバリ：重要なワークロードの高可用性と迅速なディザスタリカバリを実現
*** コールド/アーカイブのディザスタリカバリ：
+
**** コールドディザスタリカバリ：目標復旧時間（RTO）とオブジェクト復旧時点（RPO）を長くしてコストを削減
**** アーカイブ：長期的なストレージとコンプライアンスのためにデータをレプリケート


*** その他


.. *階層化ポリシー*：ターゲットボリュームに格納されているデータの階層化ポリシーを選択します。選択したユースケースに応じて、階層化ポリシーはユースケースに推奨される階層化ポリシーにデフォルトで設定されます。
+
_Balanced（自動）_は、工場出荷時のFSx for ONTAPユーザインターフェイスを使用してボリュームを作成する場合のデフォルトの階層化ポリシーです。ボリューム階層化ポリシーの詳細については、AWS FSx for NetApp ONTAPドキュメントのを参照してください link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["ボリュームのストレージ容量"^] 。

.. *最大転送速度*：* Limited *を選択し、最大転送速度をMB/秒単位で入力します。または、*無制限*を選択します。
+
制限がないと、ネットワークとアプリケーションのパフォーマンスが低下する可能性があります。また、FSx for ONTAPファイルシステムは、主にディザスタリカバリに使用されるワークロードなど、重要なワークロードには無制限の転送速度を推奨します。



. [Replication settings]で、次の情報を指定します。
+
.. *レプリケーション間隔*：ソースボリュームからターゲットボリュームにSnapshotを転送する頻度を選択します。
.. *長期保存*：オプションで、長期保存用のスナップショットを有効にします。
+
長期保持を有効にする場合は、既存のポリシーを選択するか、新しいポリシーを作成して、レプリケートするSnapshotと保持する数を定義します。

+
*** [Choose an existing policy]*で、ドロップダウンメニューから既存のポリシーを選択します。
*** [新しいポリシーを作成する]*に、次の情報を入力します。
+
**** *ポリシー名*：ポリシー名を入力します。
**** * Snapshotポリシー*：表で、Snapshotポリシーの頻度と保持するコピーの数を選択します。Snapshotポリシーは複数選択できます。






. 「 * Create * 」を選択します。


--
.ファイルシステム内のすべてのボリュームをレプリケート
--
ファイルシステム内のすべてのデータ保護（DP）ボリュームをレプリケートできます。


NOTE: データ保護ボリュームのレプリカが1つサポートされます。DPボリュームの2つ目のレプリカは作成できません。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. [FSx for ONTAP ]タブで、ボリュームを含むファイルシステムの3ドットメニューを選択し、*[管理]*を選択します。
. ファイルシステムの概要で、*レプリケーションの作成*を選択します。
. [Create replication]ページの[Replication target]で、次の情報を指定します。
+
.. * FSx for ONTAPファイルシステム*：対象となるFSx for ONTAPファイルシステムのクレデンシャル、リージョン、FSx for ONTAPファイルシステム名を選択します。
.. * Storage VM名*：ドロップダウンメニューからStorage VMを選択します。
.. *ボリューム名*：ターゲットボリューム名は次の形式で自動的に生成されます `{OriginalVolumeName}_copy`。
.. *階層化ポリシー*：ターゲットボリュームに格納されているデータの階層化ポリシーを選択します。
+
_Auto_は、工場出荷時のFSx for ONTAPユーザインターフェイスを使用してボリュームを作成する場合のデフォルトの階層化ポリシーです。ボリューム階層化ポリシーの詳細については、AWS FSx for NetApp ONTAPドキュメントのを参照してください link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["ボリュームのストレージ容量"^]。

.. *最大転送速度*：* Limited *を選択し、最大転送速度をMiB/秒で入力します。または、*無制限*を選択します。
+
制限がないと、ネットワークとアプリケーションのパフォーマンスが低下する可能性があります。また、FSx for ONTAPファイルシステムは、主にディザスタリカバリに使用されるワークロードなど、重要なワークロードには無制限の転送速度を推奨します。



. [Replication settings]で、次の情報を指定します。
+
.. *レプリケーション間隔*：ソースボリュームからターゲットボリュームにSnapshotを転送する頻度を選択します。
.. *長期保存*：オプションで、長期保存用のスナップショットを有効にします。
+
長期保持を有効にする場合は、既存のポリシーを選択するか、新しいポリシーを作成して、レプリケートするSnapshotと保持する数を定義します。

+
*** [Choose an existing policy]*で、ドロップダウンメニューから既存のポリシーを選択します。
*** [新しいポリシーを作成する]*に、次の情報を入力します。
+
**** *ポリシー名*：ポリシー名を入力します。
**** * Snapshotポリシー*：表で、Snapshotポリシーの頻度と保持するコピーの数を選択します。Snapshotポリシーは複数選択できます。






. 「 * Create * 」を選択します。


--
====
.結果
レプリケートされたボリュームはレプリケートされ、ターゲットのFSx for ONTAPファイルシステムの*レプリケーション関係*タブに表示されます。
