---
sidebar: sidebar 
permalink: cascade-replication.html 
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume 
summary: データ保護ボリュームをレプリケートするか、ボリュームデータのレプリケーションをカスケードして、データ保護を3次システムに拡張したり、データを移行したりできます。 
---
= BlueXP  ワークロード工場でデータ保護ボリュームをレプリケート
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
データ保護ボリュームをレプリケートするか、ボリュームデータのレプリケーションをカスケードして、データ保護を3次システムに拡張したり、データを移行したりできます。

.タスクの内容
BlueXP  ワークロードファクトリでは、データ保護ボリュームのレプリケート（_cascade deployments_）がサポートされています。_cascade deployment_は関係のチェーンで構成されます。このチェーンでは、ソースボリュームがセカンダリボリュームにミラーリングされ（1番目のホップ）、セカンダリボリュームが3番目のボリュームにミラーリングされます（2番目のホップ）。セカンダリボリュームが使用できなくなった場合は、新しいベースライン転送を実行せずに、プライマリボリュームと3番目のボリュームの間の関係を同期できます。

この機能は、ONTAPバージョン9.6以降のFSx for ONTAPファイルシステムでサポートされます。を参照してください link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships["互換性のあるONTAPバージョンのONTAPドキュメント"^]。

詳細については、をご覧ください link:https://docs.netapp.com/us-en/ontap/data-protection/supported-deployment-config-concept.html#how-cascade-deployments-work["カスケード構成の仕組み"^]。

.開始する前に
開始する前に、次の点を考慮してください。

* カスケード構成に含まれるボリュームの再同期には時間がかかることに注意してください。
* 関係のソースボリュームがデータ保護ボリュームであり、別の関係のターゲットである場合、レプリケーション関係を反転することはできません。
* データ保護ボリュームの1つのレプリカ（または2番目のホップ）がサポートされます。データ保護ボリュームの2つ目のレプリカ（または3つ目のホップ）を作成することはベストプラクティスとはみなされていません。


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、レプリケートするボリュームを含むファイルシステムの3ドットメニューを選択し、* Manage *を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [ボリューム]の表で、1つ以上のデータ保護ボリューム（DP /レプリケートされたボリューム）を選択し、*[データのレプリケート]*を選択します。
. [Replicate data]ページの[Replication target]で、次の情報を指定します。
+
.. * FSx for ONTAPファイルシステム*：対象となるFSx for ONTAPファイルシステムのクレデンシャル、リージョン、FSx for ONTAPファイルシステム名を選択します。
.. * Storage VM名*：ドロップダウンメニューからStorage VMを選択します。
.. *ボリューム名*：ターゲットボリューム名は次の形式で自動的に生成されます `{OriginalVolumeName}_copy`。自動生成されたボリューム名を使用するか、別のボリューム名を入力できます。
.. *ユースケース*：レプリケーションのユースケースとして、次のいずれかを選択します。選択したユースケースに応じて、ワークロードファクトリはベストプラクティスに従って推奨値をフォームに入力します。推奨値をそのまま使用することも、フォームに入力する際に変更を加えることもできます。
+
*** 移行：ターゲットのFSx for ONTAPファイルシステムにデータを転送
*** ホットディザスタリカバリ：重要なワークロードの高可用性と迅速なディザスタリカバリを実現
*** コールド/アーカイブのディザスタリカバリ：
+
**** コールドディザスタリカバリ：目標復旧時間（RTO）とオブジェクト復旧時点（RPO）を長くしてコストを削減
**** アーカイブ：長期的なストレージとコンプライアンスのためにデータをレプリケート


*** その他


.. *階層化ポリシー*：ターゲットボリュームに格納されているデータの階層化ポリシーを選択します。階層化ポリシーは、選択したユースケースに応じた推奨される階層化ポリシーにデフォルトで設定されます。
+
_Balanced（Auto）_は、ワークロード工場出荷時のコンソールを使用してボリュームを作成する際のデフォルトの階層化ポリシーです。ボリューム階層化ポリシーの詳細については、AWS FSx for NetApp ONTAPドキュメントのを参照してください link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["ボリュームのストレージ容量"^] 。ワークロードファクトリでは、階層化ポリシーにワークロードファクトリコンソールのユースケースベースの名前が使用され、かっこ内にFSx for ONTAP階層化ポリシー名が含まれていることに注意してください。

+
移行のユースケースを選択した場合は、ソースボリュームの階層化ポリシーをターゲットボリュームにコピーすることがワークロード出荷時に自動的に選択されます。階層化ポリシーをコピーするかどうかを選択解除し、レプリケーション対象として選択したボリュームに適用する階層化ポリシーを選択できます。

.. *最大転送速度*：* Limited *を選択し、最大転送速度をMB/秒単位で入力します。または、*無制限*を選択します。
+
制限がないと、ネットワークとアプリケーションのパフォーマンスが低下する可能性があります。また、FSx for ONTAPファイルシステムは、主にディザスタリカバリに使用されるワークロードなど、重要なワークロードには無制限の転送速度を推奨します。



. [Replication settings]で、次の情報を指定します。
+
.. *レプリケーション間隔*：ソースボリュームからターゲットボリュームにSnapshotを転送する頻度を選択します。
.. *長期保存*：オプションで、長期保存用のスナップショットを有効にします。長期保存により、サイト全体に障害が発生してもビジネスサービスの運用を継続できるため、アプリケーションをセカンダリコピーを使用して透過的にフェイルオーバーできます。
+
長期保存のないレプリケーションでは、_MirrorAllSnapshots_ ポリシーが使用されます。長期保存を有効にすると、レプリケーションに _MirrorAndVault_ ポリシーが割り当てられます。

+
長期保持を有効にする場合は、既存のポリシーを選択するか、新しいポリシーを作成して、レプリケートするSnapshotと保持する数を定義します。

+

NOTE: 長期保存には、ソースラベルとターゲットラベルを一致させる必要があります。必要に応じて、Workload Factoryで不足しているラベルが作成されることがあります。

+
*** *既存のポリシーを選択*：ドロップダウンメニューから既存のポリシーを選択します。
*** *新しいポリシーを作成*：次の情報を入力します。
+
**** *ポリシー名*：ポリシー名を入力します。
**** オプション：変更不可のSnapshotを有効にします。
+
***** このポリシーで作成されたSnapshotが保持期間中に削除されないようにするには、[変更不可のSnapshotを有効にする]*を選択します。
***** [Retention Period]*を時間、日、月、または年数で設定します。


**** * Snapshotポリシー*：表で、Snapshotポリシーの頻度と保持するコピーの数を選択します。Snapshotポリシーは複数選択できます。






. 「 * Create * 」を選択します。


.結果
レプリケートされたボリュームはレプリケートされ、ターゲットのFSx for ONTAPファイルシステムの*レプリケーション関係*タブに表示されます。
