---
sidebar: sidebar 
permalink: change-tiering-policy.html 
keywords:  
summary: 階層化ポリシーを変更して、高パフォーマンスのプライマリストレージ階層からセカンダリの容量プールストレージ階層にデータを再割り当てします。 
---
= ボリュームの階層化ポリシーを変更する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
高パフォーマンスのプライマリストレージ階層からセカンダリの大容量プールストレージ階層にデータを自動的に再割り当てするように階層化ポリシーを変更します。

.タスクの内容
ボリュームの階層化ポリシーはいつでも変更できます。階層化ポリシーはボリュームごとに定義されます。

データの格納場所を決定することは、コスト削減に影響します。

FSx for ONTAPには、ボリュームデータを格納するための2つの階層があります。

* * SSDストレージ階層*：このプライマリストレージ階層は、最も頻繁にアクセスするデータ用です（_hot_dataとも呼ばれます）。プライマリストレージ階層にデータを格納する方が、セカンダリストレージ階層に格納するよりもコストがかかります。
* *容量プールストレージ階層*：このセカンダリストレージ階層は、アーカイブデータまたはアクセス頻度の低いデータ（_COLD_DATAとも呼ばれます）用です。


ストレージ階層の詳細については、AWS for FSx for NetApp ONTAPのドキュメントを参照して link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-storage-capacity.html#storage-tiers["ストレージ容量の管理"^] ください。

.開始する前に
階層化ポリシーを変更する前に、使用可能な4つの階層化ポリシーを確認してください。

* *自動*：ユーザデータとSnapshotを含むすべてのコールドデータを一定期間大容量プールストレージ階層に階層化します。
* * Snapshotのみ*：スナップショットデータのみを容量プールストレージ階層に階層化します。
* *なし*：ボリュームのすべてのデータをプライマリストレージ階層に保持します。
* * all *：すべてのユーザデータとSnapshotデータをコールドとしてマークし、容量プールストレージ階層に格納します。


一部の階層化ポリシーには、最小クーリング期間が関連付けられています。最小クーリング期間は、ボリューム内のアクセス頻度の低いユーザデータが「コールド」とみなされて大容量プールストレージ階層に移動されるまでの時間（_cooling days_）を設定します。クーリング期間は、データがディスクに書き込まれた時点から開始されます。

.手順
. にログインします。 link:https://console.workloads.netapp.com/["Workload Factoryコンソール"^]
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、更新するボリュームを含むファイルシステムの3つのドットメニューを選択し、*[管理]*を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [ボリューム]タブで、階層化ポリシーを変更するボリュームの3つのドットのメニューをクリックします。
. [アドバンストアクション]*を選択し、*[階層化ポリシーの変更]*を選択します。
. [階層化ポリシーの変更]ページで、次のいずれかの階層化ポリシーを選択します。
+
** *自動*：冷却日数を入力します。
** *スナップショットのみ*：クーリング日数を入力します。
** * なし *
** *すべて*


. [ 適用（ Apply ） ] をクリックします。

