---
sidebar: sidebar 
permalink: change-snapshot-policy.html 
keywords: snapshot policy, snapshot schedule, modify snapshot policy, edit snapshot policy, change snapshot policy 
summary: BlueXP  ワークロード工場では、ボリュームのSnapshotポリシーをいつでも更新できます。 
---
= BlueXP  ワークロードファクトリでのボリュームのSnapshotポリシーの変更
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロードファクトリでは、ボリュームに対して作成されるスナップショットの頻度を更新するか、または自動スナップショットを無効にします。

.開始する前に
既存のSnapshotポリシーを表示するには、リンクを関連付ける必要があります。リンクを関連付けるには、*[アカウント名]*で*[リンクの関連付け]*を選択します。その後、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、更新するSnapshotポリシーが設定されたボリュームが含まれているFSx for ONTAPファイルシステムの3ドットメニューを選択し、*[管理]*を選択します。
. ファイルシステムの[概要]タブで、*[ボリューム]*タブを選択します。
. [ボリューム]*タブを選択します。
. [ボリューム]*タブで、Snapshotポリシーを変更するボリュームの3ドットのメニューを選択します。
. [データ保護操作]*、*[スナップショット]*の順に選択し、*[スナップショットポリシーの管理]*を選択します。
. Snapshotポリシーの管理ページで、*[既存のSnapshotポリシーの変更]*を選択します。
. [Snapshotポリシー名]*フィールドで、このボリュームに別のSnapshotポリシーを選択します。
+
自動Snapshotを無効にするには、を選択します `none`。

+
他のSnapshotポリシーがない場合は、 link:create-snapshot-policy.html["このボリュームの新しいSnapshotポリシーを作成する"]を参照してください。

. [適用]*を選択して変更を保存します。

