---
sidebar: sidebar 
permalink: clone-volume.html 
keywords: clone volume, clone, clone data 
summary: BlueXP ワークロード ファクトリーでボリュームを複製し、テスト用に元のボリュームの読み取り/書き込みボリュームを作成します。 
---
= BlueXP  ワークロードファクトリでのボリュームのクローニング
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP ワークロード ファクトリーでボリュームを複製し、テスト用に元のボリュームの読み取り/書き込みボリュームを作成します。

クローンには、データの現在のポイントインタイムの状態が反映されます。クローンを使用すると、追加のユーザに本番環境のデータへのアクセスを許可することなく、データへのアクセスを許可することもできます。

.タスクの内容
ボリュームクローニングは、FlexCloneボリュームでのみサポートされます。

ボリュームがクローニングされると、親ボリュームのSnapshotへの参照を使用して書き込み可能なボリュームが作成されます。クローンの作成は数秒で完了します。クローニングされたデータはボリュームクローンには格納されず、親ボリュームに格納されます。クローン作成後にボリュームに書き込まれた新しいデータは、クローン上に格納されます。

クローンボリュームに親ボリュームのすべてのデータと、作成後にクローンに追加された新しいデータを格納するには、親ボリュームからを実行する必要が link:split-cloned-volume.html["クローンをスプリットする"] あります。また、親ボリュームにクローンがある場合は削除できません。親ボリュームを削除するには、クローンをスプリットする必要があります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、クローンを作成するボリュームが含まれているFSx for ONTAPファイルシステムの3ドットメニューを選択し、* Manage *を選択します。
. ファイルシステムの[概要]タブで、*[ボリューム]*タブを選択します。
. [Volumes]タブで、クローニングするボリュームの3ドットメニューを選択します。
. [データ保護操作]*を選択し、*[ボリュームのクローニング]*を選択します。
. [Clone volume]ダイアログで、ボリュームクローンの名前を入力します。
. 「 * Clone * 」を選択します。

