---
sidebar: sidebar 
permalink: clone-volume.html 
keywords: clone volume 
summary: テスト用に元のボリュームの読み取り/書き込みボリュームを作成するには、ボリュームをクローニングします。 
---
= ボリュームのクローニング
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
テスト用に元のボリュームの読み取り/書き込みボリュームを作成するには、ボリュームをクローニングします。

クローンには、データの現在のポイントインタイムの状態が反映されます。クローンを使用すると、追加のユーザに本番環境のデータへのアクセスを許可することなく、データへのアクセスを許可することもできます。

.タスクの内容
ボリュームクローニングは、FlexCloneボリュームでのみサポートされます。

ボリュームがクローニングされると、親ボリュームのSnapshotへの参照を使用して書き込み可能なボリュームが作成されます。クローンの作成は数秒で完了します。クローニングされたデータはボリュームクローンには格納されず、親ボリュームに格納されます。クローン作成後にボリュームに書き込まれた新しいデータは、クローン上に格納されます。

クローンボリュームに親ボリュームのすべてのデータと、作成後にクローンに追加された新しいデータを格納するには、親ボリュームからを実行する必要が link:split-cloned-volume.html["クローンをスプリットする"] あります。また、親ボリュームにクローンがある場合は削除できません。親ボリュームを削除するには、クローンをスプリットする必要があります。

.手順
. にログインします。 link:https://console.workloads.netapp.com/["Workload Factoryコンソール"^]
. [Storage]で、*[Go to storage inventory]*を選択します。
. [ボリューム]*タブを選択します。
. [Volumes]タブで、クローニングするボリュームの3つのドットメニューを選択します。
. [データ保護操作]*を選択し、*[ボリュームのクローニング]*を選択します。
. [Clone volume]ダイアログで、ボリュームクローンの名前を入力します。
. [* Clone* ] をクリックします。

