---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload FactoryはAmazon FSx for NetApp ONTAPファイルシステム構成を定期的に分析し、構成上の問題がないかどうかを確認します。 
---
= FSx for ONTAPファイルシステムの構成分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload FactoryはAmazon FSx for NetApp ONTAPファイルシステム構成を定期的に分析し、構成上の問題がないかどうかを判断します。問題が検出された場合、Workload Factoryは問題点を示し、ファイルシステムストレージが最高のパフォーマンス、コスト効率、およびベストプラクティスへの準拠を達成するために何を変更する必要があるかを説明します。

主な機能は次のとおりです。

* 日常的な構成分析
* ベストプラクティスの自動検証
* プロアクティブなオブザーバビリティ
* インサイトからアクションへ
* AWS Well-Architected Framework Advisor




[[how-it-works]]
== 仕組み

Workload Factoryは、サポートされているクラウドストレージシステム上で実行されているワークロードを毎日分析します。この分析により、適切に設計されたステータス、インサイト、および推奨事項が提供されます。

日々の分析が完了すると、デプロイメントのWell-architectedダッシュボードに、構成が「最適化済み」または「最適化されていない」として表示されます。設定に関する問題はカテゴリ別に整理されており、設定に関する問題とその推奨事項の一覧も掲載されています。設定に関する問題については、推奨事項をご確認ください。Workload Factoryは一部の問題を自動的に修正できますが、その他の問題には手動での対応が必要です。この場合、Workload Factoryは、推奨される変更を実装するための詳細な手順を提供します。

ご自身の環境に適用されない構成の分析を無視することができます。これにより、不要なアラートや不正確な最適化結果を回避できます。

また、組織の標準および NetApp のベストプラクティスに照らして環境を検証するために、平易な言葉でカスタムルールを作成することもできます。ドライランでルールをテストし、各環境で実行するようにスケジュールを設定します。link:https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["カスタムルールについて詳しくはこちらをご覧ください"^]。



[[why-it-matters]]
== 重要な理由

Workload Factory は、継続的な評価と推奨事項、および修復策を組み合わせることで、大規模なストレージ、データベース、および VMware 環境にベストプラクティスを適用します。自動化された修正機能は、人的ミスを減らし、均一な管理を確保し、ワークロードインフラストラクチャ全体でパフォーマンスと信頼性を維持します。



[[analysis-requirements]]
== 分析要件

完全なファイル システム分析を行うには、次の操作を実行する必要があります。

* リンクを関連付けます。リンク接続により、Workload Factory はデータ保護やパフォーマンスなどのすべてのファイル システム構成を分析できます。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"^]。

* AWS アカウントで表示、計画、分析の権限を付与します。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWSアカウントに権限を付与する方法を確認する"^]。





[[best-practices-and-recommendations-for-storage-workloads]]
== ストレージワークロードに関するベストプラクティスと推奨事項

適切に設計されたダッシュボードは、ストレージ構成をONTAPのベストプラクティスおよびAWS Well-Architected Frameworkに照らして評価します。この評価では、改善点や修正点も推奨しています。

適切に設計された分析では、構成をフレームワークの次の柱に分類します：_信頼性_、_セキュリティ_、_運用効率_、_コスト最適化_、および_パフォーマンス効率_。



[[reliability]]
=== 信頼性

信頼性とは、障害が発生した場合でも、ワークロードが意図された機能を正確かつ一貫して実行することを保証するものです。

* ボリュームバックアップ
+
ボリュームのバックアップは、データ保持とコンプライアンスのニーズをサポートするのに役立ちます。ボリュームバックアップを使用して、データの自動バックアップと保持を設定します。

* *Snapshotポリシー*
+
効率的なバックアップと迅速なリストアのために、ローカルSnapshotをスケジュール設定してください。Snapshotは、ボリュームのポイントインタイムイメージを瞬時に作成します。この推奨事項はデータベース環境には適用されません。

* *アプリケーション整合性Snapshot*
+
データベース環境では、NetApp SnapCenter のアプリケーション整合性スナップショットを使用して、特定のポイントインタイムにおけるボリュームデータの正確で信頼性の高いスナップショットを取得します。これにより、アプリがスムーズに動作し、データが安全に保たれます。SnapCenter はバックアップを容易にし、データの迅速かつ正確な復元を支援することで、ダウンタイムを削減し、最も重要なワークロードを保護します。

* *リージョン間レプリケーション*
+
リージョン間レプリケーションにより、データが別のAWSリージョンに複製されるため、データの耐久性と可用性が向上します。災害復旧とコンプライアンスをサポートするために、リージョン間レプリケーションを設定します。

* *SSDキャパシティのヘッドルーム*
+
SSDストレージ層の容量は、使用率が80%を超えないようにしてください。これは、キャパシティプールストレージ層へのデータの読み書きに影響を与え、ファイルシステムのスループット容量にも影響を与える可能性があります。容量が不足すると、データボリュームは読み取り専用になります。新しいデータを書き込もうとするサービスも失敗します。

* *レプリケーションポリシーラベル*
+
データの信頼性を確保するためには、ソースボリュームのSnapshotポリシーラベルとレプリケーションポリシーラベルが一致している必要があります。

* ファイルオブジェクト容量
+
ボリューム容量制限に達しないように、ファイル容量のしきい値を引き上げるべきです。ファイル容量（iノード）が不足しているため、ボリュームへの追加データの書き込みができません。Workload Factoryは、新規ファイルの作成を可能にするため、ファイル容量の使用率を80%未満に維持することを推奨しています。





[[security]]
=== セキュリティ

セキュリティは、リスク評価と軽減戦略を通じて、データ、システム、資産を保護することを重視します。

* *ランサムウェア対策（ARP/AI）*
+
NetApp Autonomous Ransomware Protection with AI（ARP/AI）は、ボリュームをランサムウェアの脅威から保護するのに役立ちます。Workload Factory では、すべてのボリュームに対して ARP/AI を有効にすることをお勧めします。

* *不正なiSCSIボリュームアクセス*
+
iSCSIを使用してアプリケーションデータを提供するボリュームは、同時にNASアクセスを許可すべきではありません。Workload Factoryは、iSCSIボリュームが他のプロトコルを使用しないよう制限することを推奨します。





[[operational-excellence]]
=== 運用の卓越性

運用上の卓越性とは、最適なアーキテクチャとビジネス価値を提供することに重点を置くものです。

* *自動容量管理*
+
SSD 階層がしきい値を超えないように定期的に確保するには、自動容量管理を有効にする必要があります。

* *ボリューム容量のヘッドルーム*
+
潜在的なアプリケーションの読み取り / 書き込みへの影響を防ぐために、ボリュームの使用率を80%未満に抑えてください。容量は手動で増やすか、ボリュームの自動拡張を使用して増やすことができます。

* *FlexCache 書き込みモード*
+
最適なパフォーマンスを得るには、ワークロードに最適なキャッシュ関係書き込みモードを設定してください。ライトアラウンドモードは、小さなファイルを扱う読み込み中心のワークロードにおいて優れたパフォーマンスを発揮する一方、ライトバックモードは、大きなファイルを扱う書き込み中心のワークロードにおいて優れたパフォーマンスを発揮します。

* *FlexCacheレプリカサイズ*
+
キャッシュボリュームの自動サイズ変更とスクラビングを有効にして、最適なサイズを維持し、キャッシュをホットデータに集中させることで、最高の効率を実現します。

* *ホストから見える容量レポート*
+
ホストから見える容量レポートを有効にすることで、ボリュームレベルでのストレージ使用状況をより詳細に把握できます。

* *オペレーティングシステム（OS）の種類*
+
ONTAP LUN のオペレーティングシステム（OS）タイプの値が、I/O アライメントを実現するためにオペレーティングシステムのパーティショニング方式と一致していることを確認してください。設定が正しくない場合、パフォーマンスが低下する可能性があります。

* *ブロックデバイスの領域管理*
+
FSx for ONTAP で書き込みエラーを防止し、スペース効率を向上させるために、データベースホストインスタンスで使用される LUN のブロックデバイススペース設定を構成します。この構成は、シンプロビジョニングボリュームに推奨される設定の組み合わせ（スペース リザベーション、スペース割り当て、およびフラクショナルリザーブ）に適用されます。

* *シンプロビジョニング*
+
データベースインスタンスをホストする FSx for ONTAP ボリュームのシンプロビジョニングを構成します。このアプローチにより、物理的に利用可能な容量よりも多くの論理データを格納できます。





[[cost-optimization]]
=== コスト最適化

コストの最適化により、コストを低く抑えながらビジネスの価値を最大限に高めることができます。

* *コールドデータ階層化*
+
SSDストレージ階層の利用率を削減するために、コールドデータ階層化を有効にしてください。一般的なデータストレージを目的としたすべてのボリュームに階層化ポリシーを適用します。データベースボリュームについては、必要に応じてコールドデータ階層化を有効にしてください。FSx for ONTAPはデータを継続的にスキャンしてコールドデータを検出し、中断することなくキャパシティプール層に移動します。

* *ストレージ効率*
+
ストレージ効率化機能（コンパクション、圧縮、重複排除）を有効にすることで、ストレージ利用率を最適化し、SSDティアのコストを削減します。

* *バックアップの有効期限*
+
削除されたボリュームに対して手動で作成されたバックアップ、および2週間以上前のバックアップをすべて削除してください。これらのバックアップは自動的に期限切れにならず、SLAや復旧のために不要になった場合でも、コストが増加したり、複雑さが増したりする可能性があります。

* *Snapshotの有効期限*
+
不要になった古いスナップショットや手動で作成したスナップショットは削除してください。削除することでコストを削減し、整理整頓に役立ちます。特に、SLAや復旧ニーズに必要でない場合はなおさらです。

* *非アクティブなブロックデバイス*
+
ブロックデバイスが7日間使用されなかった場合は、コスト削減のため、ブロックデバイスのデータをアーカイブするか、使用されていないブロックデバイスを削除してください。

* *SSD容量のオーバープロビジョニング*
+
過剰なSSD容量は不要なコスト増につながります。20%の空き容量バッファを維持しながら、SSDティアを削減します。この操作には数時間から数日かかる場合があり、その間は他のファイルシステム操作はサポートされません。

* *非アクティブなNASボリューム*
+
構成分析では、アクティブに使用されていない NAS ボリュームを特定し、コストを削減するためにボリュームを削除またはアーカイブすることを提案します。





[[performance-efficiency]]
=== パフォーマンス効率

パフォーマンス効率を高めることで、ストレージリソースが効果的に使用され、ワークロードが最適なパフォーマンスを発揮することを確認できます。

* *FlexGroupボリュームの再調整*
+
FlexGroup ボリュームを再バランスして効率を向上させます。スケールアウト後、容量とワークロードのアクティビティがボリューム全体で不均一になる可能性があります。

* *FlexVolボリュームの再調整*
+
FlexVol ボリュームのバランスを再調整して、効率を向上させます。スケールアウト後、容量とワークロードのアクティビティがボリューム全体で不均一になる場合があります。



.次のステップ
link:improve-configurations.html["適切に設計されたファイルシステム構成の実装"]
