---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: BlueXP  ワークロードファクトリは、Amazon FSx for NetApp ONTAPのファイルシステム構成を定期的に分析し、問題がないかどうかを判断します。 
---
= FSx for ONTAPファイルシステムの構成分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロードファクトリは、Amazon FSx for NetApp ONTAPのファイルシステム構成を定期的に分析し、問題がないかどうかを判断します。問題が検出されると、ワークロードファクトリに問題の内容が表示され、ファイルシステムストレージが最高のパフォーマンス、コスト効率、ベストプラクティスへの準拠を達成できるようにするために何を変更する必要があるかが説明されます。

主な機能は次のとおりです。

* 日常的な構成分析
* ベストプラクティスの自動検証
* プロアクティブなオブザーバビリティ
* インサイトからアクションへ
* AWS Well-Architected Framework Advisor




== 適切に設計されたステータス

ファイルシステムレベルのワークロードファクトリコンソールには、すべてのFSx for ONTAPファイルシステムについて、適切に設計されたステータスが表示されます。Well-Architectedステータスは、「問題」、「分析されていない」、または「Well-Architected」に分類されます。well-architectedステータスを選択すると、ファイルシステム内のwell-architectedステータスタブにリダイレクトされます。このタブでは、well-architectedスコア、構成カテゴリ、ファイルシステムのすべての構成を確認できます。

適切に設計されたスコア:: スコアには現在分析されているすべての構成が含まれ、パーセンテージで表示されます。25%のスコアは、25%のファイルシステム構成が適切に設計されていることを意味します。
構成のカテゴリ:: ファイルシステム構成は、AWS Well-Architected Frameworkの次の5つの柱に沿ったカテゴリに分類されています。
+
--
* _信頼性_：システムが停止した場合でも、ワークロードが意図した機能を正しく一貫して実行するようにします。構成例としては、FSx for ONTAPのバックアップがあります。
* _セキュリティ_：リスク評価とリスク軽減戦略を通じて、データ、システム、資産を保護することに重点を置いています。
* _優れた運用性_：最適なアーキテクチャとビジネスバリューを提供することに重点を置いています。
* _コスト最適化_：コストを最小限に抑えながらビジネス価値を提供することを目指しています。
* _パフォーマンス効率_：リソースを効率的に使用してシステム要件を満たし、需要の変化に応じて最適なパフォーマンスを維持することに重点を置いています。


--




== 分析要件

ファイルシステムを完全に分析するには、リンクを関連付ける必要があります。リンク接続により、ワークロード工場はデータ保護やパフォーマンスなどのすべてのファイルシステム構成を分析できます。

link:create-link.html["リンクを作成する方法について説明します。"]

.次のステップ
link:improve-configurations.html["FSx for ONTAP環境の構成を改善"]
