---
sidebar: sidebar 
permalink: configure-active-directory.html 
keywords: configure AD, configure active directory, update ad, edit active directory 
summary: BlueXP  ワークロード工場のFSx for ONTAPファイルシステムで、Storage VMのActive Directoryを設定および更新します。 
---
= Storage VMのActive Directoryの設定と更新
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロード工場のFSx for ONTAPファイルシステムで、Storage VMのActive Directoryを設定および更新します。

.タスクの内容
Storage VMのActive Directoryの設定と更新も同じ手順です。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、更新するStorage VMがあるファイルシステムの3ドットメニューを選択し、*[管理]*を選択します。
. ファイルシステムの概要で、*[Storage VMs]*タブを選択します。
. [Storage VM]タブで、Active Directoryを設定するStorage VMの3ドットメニューを選択します。
. [AD構成の管理]*を選択します。
. [Manage AD configuration]ページで、次の情報を指定します。
+
.. *参加するActive Directoryドメイン*: Active Directoryの完全修飾ドメイン名(FQDN)を入力します。
.. * DNS IPアドレス*：IPアドレスを3つまでカンマで区切って入力します。
.. * SMBサーバのNetBIOS名*：Storage VM用に作成するActive DirectoryコンピュータオブジェクトのSMBサーバのNetBIOS名を入力します。Active Directory内のこのSVMの名前を指定します。
.. *ユーザー名*：既存のActive Directory内のサービスアカウントのユーザー名を入力します。
+
ドメインのプレフィックスまたはサフィックスは含めないでください。の場合は `EXAMPLE\ADMIN`、を使用し `ADMIN`ます。

.. *パスワード*：サービスアカウントのパスワードを入力します。
.. *組織単位（OU）*：組織単位を入力します。
+
OUは、ファイルシステムに参加する組織単位の識別パス名です。

.. *委任された管理者グループ*：必要に応じて、委任されたファイルシステム管理者グループを入力します。
+
委任管理者グループは、ファイルシステムを管理できるActive Directory内のグループの名前です。

+
AWS Managed Microsoft ADを使用している場合は、AWS Delegated FSx Administrators、AWS Delegated Administratorsなどのグループ、またはOUに権限を委譲されたカスタムグループを指定する必要があります。

+
自己管理型ADに接続する場合は、AD内のグループ名を使用します。デフォルトのグループはです `Domain Admins`。



. * 適用 * を選択します。

