---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload FactoryはAmazon FSx for NetApp ONTAPファイルシステム構成を定期的に分析し、構成上の問題がないかどうかを確認します。 
---
= FSx for ONTAPファイルシステムの構成分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload FactoryはAmazon FSx for NetApp ONTAPファイルシステム構成を定期的に分析し、構成上の問題がないかどうかを判断します。問題が検出された場合、Workload Factoryは問題点を示し、ファイルシステムストレージが最高のパフォーマンス、コスト効率、およびベストプラクティスへの準拠を達成するために何を変更する必要があるかを説明します。

主な機能は次のとおりです。

* 日常的な構成分析
* ベストプラクティスの自動検証
* プロアクティブなオブザーバビリティ
* インサイトからアクションへ
* AWS Well-Architected Framework Advisor




== 仕組み

Workload Factory は、Amazon FSx for NetApp ONTAP ファイルシステムの導入環境で実行されているワークロードを毎日分析します。この分析により、適切に設計された状態、インサイト、および推奨事項が提供されます。

日々の分析が完了すると、デプロイメントのWell-architectedダッシュボードに、構成が「最適化済み」または「最適化されていない」として表示されます。総合的な最適化スコア、カテゴリ別の構成の問題、および構成の問題と推奨事項の一覧が表示されます。構成の問題に関する推奨事項を確認できます。一部の問題はWorkload Factoryによって自動的に修正できますが、その他の問題は手動での介入が必要です。この場合、Workload Factoryは、推奨される変更を実装するのに役立つ詳細な手順を提供します。

ご使用の環境に適用されない構成の分析を無視することができます。これにより、不要なアラートや不正確な最適化結果を回避できます。特定の構成分析を無視すると、Workload Factory ではその構成が全体の最適化スコアに含められません。



== 重要な理由

Workload Factoryは、継続的な評価と推奨事項、および修復策を組み合わせることで、大規模なストレージ、データベース、およびVMware環境にベストプラクティスを適用します。Workload Factoryコンソールで適用される自動修正により、人的ミスが削減され、統一された管理が確保され、ワークロードインフラストラクチャ全体でパフォーマンスと信頼性が維持されます。



== 分析要件

完全なファイル システム分析を行うには、次の操作を実行する必要があります。

* リンクを関連付けます。リンク接続により、Workload Factory はデータ保護やパフォーマンスなどのすべてのファイル システム構成を分析できます。
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。

* AWS アカウントで表示、計画、分析の権限を付与します。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWSアカウントに権限を付与する方法を確認する"^]





== ストレージワークロードに関するベストプラクティスと推奨事項

Workload Factoryはストレージ構成を評価し、ONTAP構成のベストプラクティスとAWS Well-Architected Frameworkへの準拠について詳細なビューを提供します。評価では改善と修正も推奨されます。

適切に設計された分析では、構成をフレームワークの次の柱に分類します：_信頼性_、_セキュリティ_、_運用効率_、_コスト最適化_、および_パフォーマンス効率_。



=== 信頼性

信頼性とは、障害が発生した場合でも、ワークロードが意図された機能を正確かつ一貫して実行することを保証するものです。

* *ボリュームバックアップをスケジュールする*
+
ボリュームのバックアップは、データ保持とコンプライアンスのニーズをサポートするのに役立ちます。ボリュームバックアップを使用して、データの自動バックアップと保持を設定します。

* *ローカルスナップショットのスケジュール設定*
+
効率的なバックアップと迅速な復元のために、ローカルスナップショットをスケジュール設定しましょう。スナップショットは、ボリュームの瞬時のポイントインタイムイメージです。

* *リージョン間レプリケーション*
+
クロスリージョンレプリケーションにより、データが別の AWS リージョンにレプリケートされ、データの耐久性と可用性が向上します。Workload Factory では、災害復旧とコンプライアンスを支援するために、クロスリージョンレプリケーションを設定することを推奨しています。

* *データレプリケーションの設定*
+
データの信頼性を高めるために、データを同一リージョン内または別リージョン内のFSx for ONTAPファイルシステムに複製することができます。ファイルシステム間での移行、災害復旧、および長期保存をサポートするために、データレプリケーションを設定します。

* *SSD容量のしきい値を上げる*
+
SSDストレージ層の容量は、継続的に80%の使用率を超えないようにする必要があります。これにより、容量プールストレージ層へのデータの読み取りと書き込みに影響し、ファイルシステムのスループット容量に影響する可能性があります。容量が不足すると、データボリュームが読み取り専用になり、新しいデータを書き込もうとするサービスが失敗する可能性があります。

* *データの信頼性を確保するためにラベルを一致させる*
+
データの信頼性を確保するためには、ソースボリュームのSnapshotポリシーラベルとレプリケーションポリシーラベルが一致している必要があります。

* *ファイル容量のしきい値を上げる*
+
ボリューム容量制限に達しないように、ファイル容量のしきい値を引き上げるべきです。ファイル容量（iノード）が不足しているため、ボリュームへの追加データの書き込みができません。Workload Factoryは、利用可能なファイル容量の使用率を継続的に80%未満に抑えることを推奨しています。ボリューム内に新しいファイルを作成するには、利用可能なファイル容量が必要です。





=== セキュリティ

セキュリティは、リスク評価と軽減戦略を通じて、データ、システム、資産を保護することを重視します。

* *ARP/AIを有効にする*
+
NetApp Autonomous Ransomware Protection with AI（ARP/AI）は、ボリュームをランサムウェアの脅威から保護するのに役立ちます。Workload Factory では、すべてのボリュームに対して ARP/AI を有効にすることをお勧めします。

* *ボリュームへの不正アクセス*
+
iSCSIを使用してアプリケーションデータを提供するボリュームは、NASからの同時アクセスを許可すべきではありません。NetApp Workload Factoryは、iSCSIプロトコルを介してアクセスされるボリュームは、他のプロトコルに制限することを推奨しています。





=== 運用の卓越性

運用上の卓越性とは、最適なアーキテクチャとビジネス価値を提供することに重点を置くものです。

* *自動容量管理を有効にする*
+
SSD 階層がしきい値を超えないように定期的に確保するには、自動容量管理を有効にする必要があります。

* *ボリューム容量使用率のしきい値*
+
Workload Factoryは、ボリューム容量の利用率が継続的に80%を超えないようにすることを推奨しています。これは、アプリケーションへのデータの読み書きに影響を与える可能性があります。ボリューム容量の増加は、手動またはボリュームの自動拡張機能を使用して自動的に行うことができます。

* *ボリューム使用率がほぼ満杯です*
+
ボリュームの容量がほぼ満杯に近づいた場合、NetApp Workload Factoryは、アプリケーションの潜在的な中断を回避するために、ボリューム容量を増やすための対策を講じることを推奨します。

* *キャッシュ関係の書き込みモード*
+
最適なパフォーマンスを実現するために、Workload Factoryはワークロードに最適なキャッシュ関係書き込みモードを推奨します。ライトアラウンドモードは、小さなファイルを扱う読み込み中心のワークロードにおいて優れたパフォーマンスを発揮する一方、ライトバックモードは、大きなファイルを扱う書き込み中心のワークロードにおいて優れたパフォーマンスを発揮します。

* *キャッシュボリュームのサイズを最適化*
+
Workload Factory では、最適なサイズを維持し、ホットデータにキャッシュを集中させて効率を最大限に高めるために、ボリュームの自動サイズ調整とキャッシュボリュームのスクラブを有効にすることを推奨しています。

* *Storage VM論理レポート*
+
Workload Factory では、ボリュームレベルでのストレージ使用状況をより適切に把握できるように、ストレージ VM のデフォルトのレポート設定を論理に設定することをお勧めします。





=== コスト最適化

コストの最適化により、コストを低く抑えながらビジネスの価値を最大限に高めることができます。

* *コールドデータを階層化することでTCOを最適化*
+
SSDストレージ層の使用率を低減するために、コールドデータ階層化を有効にする必要があります。すべてのボリュームに階層化ポリシーを適用することをお勧めします。FSx for ONTAPはデータを継続的にスキャンして、コールドデータを検出し、中断することなく容量ストレージプール層に移動します。

* *ストレージ効率を有効にする*
+
ストレージ効率化機能（コンパクション、圧縮、重複排除）を有効にして、ストレージ利用率を最適化し、SSD階層のコストを削減する必要があります。

* *不要なスナップショットおよびバックアップの削除*
+
不要になったスナップショットやバックアップは、コスト削減のため削除する必要があります。

* *非アクティブなブロックデバイス*
+
ブロックデバイスが7日間使用されなかった場合、Workload Factoryはブロックデバイスデータをアーカイブするか、未使用のブロックデバイスを削除してコストを削減することを推奨します。

* *SSD容量の使用率が低い*
+
十分に活用されていないSSD容量層は、不必要なコストを発生させている可能性があります。NetApp Workload Factoryは、SSDティアの容量を削減しつつ、現在使用している容量より20%高い空き容量バッファを維持することを推奨しています。縮小操作には数時間から数日かかる場合があり、その間は他のファイルシステム操作はサポートされません。



.次のステップ
link:improve-configurations.html["適切に設計されたファイルシステム構成の実装"]
