---
sidebar: sidebar 
permalink: create-snapshot-policy.html 
keywords: create 
summary: BlueXP  ワークロード工場でFSx for ONTAPボリュームのSnapshotポリシーを作成Snapshotポリシーは、ボリュームのSnapshotの作成方法を定義します。 
---
= FSx for ONTAPボリュームのSnapshotポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロード工場でFSx for ONTAPボリューム用のカスタムSnapshotポリシーを作成Snapshotポリシーは、ボリュームのSnapshotの作成方法を定義します。

.タスクの内容
FSx for ONTAPに組み込まれている3つのスナップショットポリシーとは異なるカスタムスナップショットポリシーを作成できます。

* `default`
* `default-1weekly`
* `none`


デフォルトでは、すべてのボリュームがファイルシステムのSnapshotポリシーに関連付けられ `default` ています。ほとんどのワークロードでこのポリシーを使用することを推奨します。

ポリシーをカスタマイズすると、スナップショットを作成するタイミング、保持するコピーの数、およびスナップショットに名前を付ける方法を指定できます。

.開始する前に
* Snapshotを使用する前に、Snapshotの容量について次の点を考慮してください。
+
** ほとんどのデータセットでは、20%の容量を追加すれば、Snapshotを最大4週間保持できます。データが古くなるにつれて、リストアに使用される可能性は低くなります。
** Snapshot内のすべてのデータを上書きすると、ボリューム容量が大量に消費されます。これは、ボリューム容量のプロビジョニングに影響します。


* カスタムのSnapshotポリシーを作成するには、が必要です link:manage-links.html["リンクの関連付け"]。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*で*[リンクの関連付け]*を選択します。リンクが関連付けられたら、この操作に戻ります。


.手順
いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。です。[ストレージ]*で、*[ストレージインベントリに移動]*を選択します。です。FSx for ONTAP *タブで、ボリュームを含むファイルシステムの3ドットメニューを選択し、* Manage *を選択します。です。ファイルシステムの概要で、*[ボリューム]*タブを選択します。です。[ボリューム]*タブで、スケジュールされたSnapshotで保護するボリュームの3ドットメニューを選択します。です。[データ保護操作]*、*[スナップショット]*の順に選択し、*[スナップショットポリシーの管理]*を選択します。です。Snapshotポリシーの管理ページで、*[新しいSnapshotポリシーの作成]*を選択します。です。Snapshotポリシー名*フィールドに、Snapshotポリシーの名前を入力します。です。オプション：[説明]*フィールドに、Snapshotポリシーの説明を入力します。です。[スケジュール]*で、Snapshotを作成するタイミングを選択します。たとえば、毎分、毎時などです。

+複数の周波数を選択できます。です。[コピー数]*で、保持するコピー数を入力します。

+コピーの最大数は1、023です。です。オプション：[命名規則]*で、ポリシーの*プレフィックス*を入力します。です。*保持ラベル*は自動的に入力されます。

+このラベルは、ソースからターゲットファイルシステムへのレプリケーション用に指定されたスナップショットのみを選択するために使用されるSnapMirror（レプリケーションラベル）を示します。です。* 適用 * を選択します。
