---
sidebar: sidebar 
permalink: create-link.html 
keywords: connect, connection, link, lambda link, associate link, create link, authenticate link 
summary: リンクを作成および管理して、BlueXP  ワークロードファクトリアカウントと1つ以上のFSx for ONTAPファイルシステム間の信頼関係と接続を確立できます。 
---
= LambdaリンクでFSx for ONTAPファイルシステムに接続
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
高度なONTAP管理操作を実行するには、ワークロードファクトリアカウントと1つ以上のFSx for ONTAPファイルシステム間の接続を確立する必要があります。接続の確立には、新規および既存のLambdaリンクの関連付け、およびリンクの認証が含まれます。リンク関連付けを使用すると、AWS FSx for ONTAP APIでは利用できない特定の機能をFSx for ONTAPファイルシステムから直接監視および管理できます。

link:links-overview.html["リンクの詳細"]です。

.タスクの内容
リンクはAWS Lambdaを利用してイベントに応じてコードを実行し、そのコードに必要なコンピューティングリソースを自動的に管理します。作成したリンクはNetAppアカウントの一部であり、AWSアカウントに関連付けられています。

FSx for ONTAPファイルシステムを定義する際に、アカウントにリンクを作成できます。このリンクはそのファイルシステムに使用され、他のFSx for ONTAPファイルシステムでも使用できます。後でファイルシステムにリンクを関連付けることもできます。

リンクには認証が必要です。Workload Factoryのクレデンシャルサービスに保存されているクレデンシャル、またはAWS Secrets Managerに保存されているクレデンシャルを使用して、リンクを認証できます。1つのリンクでサポートされる認証方式は1つだけです。たとえば、[Link authentication with AWS Secrets Manager]を選択した場合、あとで認証方法を変更することはできません。


NOTE: コネクタを使用する場合、AWS Secrets Managerはサポートされません。



== 新しいリンクの関連付け

新しいリンクの関連付けには、リンクの作成と関連付けが含まれます。

リンクを作成するには、自動または手動の2つのオプションがあります。リンクを作成するには、AWSアカウントでAWS CloudFormationスタックを起動する必要があります。

* Automatically：Workload Factory経由で自動登録されたリンクを作成します。自動的に作成されたリンクには、ワークロードファクトリオートメーション用のトークンが必要であり、CloudFormationコードは短命です。最大6時間しか使用できません。
* 手動（Manually）：手動登録によるリンクを作成します。CloudFormationコードは、操作を完了するためのより多くの時間を与えます。これは、リンク作成を完了するために必要な権限を最初に付与する必要があるセキュリティやDevOpsなど、さまざまなチームと連携する場合に便利です。


.開始する前に
* どのリンク作成オプションを使用するかを検討する必要があります。
* Workload Factoryには、FSx for ONTAPファイルシステムが少なくとも1つ必要です。FSx for ONTAPファイルシステムを検出または作成するには、FSx for ONTAPインスタンスに対する権限を持つAWSアカウントとlink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html#overview["ワークロードファクトリにクレデンシャルを追加"^]ストレージ管理用の _読み取り専用_ または _読み取り/書き込み_ 権限を持ちます。
* CloudFormationスタックを使用してリンクを追加する場合は、AWSアカウントで次の権限が必要です。
+
[%collapsible]
====
[source, json]
----
"cloudformation:GetTemplateSummary",
"cloudformation:CreateStack",
"cloudformation:DeleteStack",
"cloudformation:DescribeStacks",
"cloudformation:ListStacks",
"cloudformation:DescribeStackEvents",
"cloudformation:ListStackResources",
"ec2:DescribeSubnets",
"ec2:DescribeSecurityGroups",
"ec2:DescribeVpcs",
"iam:ListRoles",
"iam:GetRolePolicy",
"iam:GetRole",
"iam:DeleteRolePolicy",
"iam:CreateRole",
"iam:DetachRolePolicy",
"iam:PassRole",
"iam:PutRolePolicy",
"iam:DeleteRole",
"iam:AttachRolePolicy",
"lambda:AddPermission",
"lambda:RemovePermission",
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:CreateFunction",
"lambda:DeleteFunction",
"lambda:TagResource",
"codestar-connections:GetSyncConfiguration",
"ecr:BatchGetImage",
"ecr:GetDownloadUrlForLayer"
----
====


[role="tabbed-block"]
====
.自動作成
--
CloudFormationを使用して、ワークロードファクトリ内のリンクを自動的に作成して登録します。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. [FSx for ONTAP *]タブで、リンクを関連付けるファイルシステムの3ドットメニューを選択し、*[Associate link]*を選択します。
. [リンクの関連付け]ダイアログで、*[新しいリンクの作成]*を選択し、*[続行]*を選択します。
. [Create Link]ページで、次の情報を指定します。
+
.. *リンク名*：このリンクに使用する名前を入力します。名前はアカウント内で一意である必要があります。
.. * AWS Secrets Manager *：オプション。Workload FactoryがAWS Secrets ManagerからFSx for ONTAPアクセスクレデンシャルを取得できるようにします。
+
リンク配置スタックは、次のデフォルトのシークレットマネージャARN正規表現をLambda権限ポリシーに追加します。 `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*`

+
デフォルトの権限に合わせてシークレットを作成するか、リンクポリシーにカスタムの権限を割り当てることができます。

+
* VPCプライベートエンドポイントをAWS Secrets Managerに設定*はデフォルトで無効になっています。このオプションを選択すると、シークレットはローカルではなくVPCプライベートエンドポイントを使用して格納されます。

.. *タグ*:必要に応じて、リソースをより簡単に分類できるように、このリンクに関連付けるタグを追加します。たとえば、FSx for ONTAPファイルシステムでこのリンクが使用されていることを示すタグを追加できます。
+
AWSアカウントと、アカウント、場所、セキュリティグループの追加情報は、FSx for ONTAPファイルシステムに基づいて自動的に取得されます。



. 「 * Create * 」を選択します。
+
[Redirect to CloudFormation]ダイアログが表示され、AWS CloudFormationサービスからリンクを作成する方法が説明されます。

. [続行]*を選択してAWS管理コンソールを開き、このFSx for ONTAPファイルシステムのAWSアカウントにログインします。
. [Quick create stack]ページの[Capabilities]で、*[I acknowledge that AWS CloudFormation might create IAM resources]*を選択します。
+
CloudFormationテンプレートを起動すると、Lambdaに3つの権限が付与されます。Workload Factoryでは、リンクの使用時にこれらの権限が使用さ

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
. [スタックの作成]*を選択し、*[続行]*を選択します。
+
リンクの作成ステータスは[Events]ページで監視できます。これには5分以内にかかります。

. ワークロードファクトリのインターフェイスに戻ると、リンクがFSx for ONTAPファイルシステムに関連付けられていることがわかります。


--
.手動で作成
--
このオプションでは、AWS CloudFormationからリンクのARNを抽出し、ここにレポートします。Workload Factoryは手動でリンクを登録します。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. [FSx for ONTAP *]タブで、リンクを関連付けるファイルシステムの3ドットメニューを選択し、*[Associate link]*を選択します。
. [リンクの関連付け]ダイアログで、*[新しいリンクの作成]*を選択し、*[続行]*を選択します。
. [Create Link]ページで、次の情報を指定します。
+
.. *リンク名*：このリンクに使用する名前を入力します。名前はアカウント内で一意である必要があります。
.. * AWS Secrets Manager *：オプション。Workload FactoryがAWS Secrets ManagerからFSx for ONTAPアクセスクレデンシャルを取得できるようにします。
+
リンク配置スタックは、次のデフォルトのシークレットマネージャARN正規表現をLambda権限ポリシーに追加します。 `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*`

+
デフォルトの権限に合わせてシークレットを作成するか、リンクポリシーにカスタムの権限を割り当てることができます。

+
* VPCプライベートエンドポイントをAWS Secrets Managerに設定*はデフォルトで無効になっています。このオプションを選択すると、シークレットはローカルではなくVPCプライベートエンドポイントを使用して格納されます。

.. *タグ*:必要に応じて、リソースをより簡単に分類できるように、このリンクに関連付けるタグを追加します。たとえば、FSx for ONTAPファイルシステムでこのリンクが使用されていることを示すタグを追加できます。
.. *リンク登録*：ドロップダウン矢印を選択して、AWS CloudFormationサービスからリンクを登録する手順を展開します。指示に従ってください。
+
CloudFormationテンプレートを起動すると、Lambdaに3つの権限が付与されます。Workload Factoryでは、リンクの使用時にこれらの権限が使用さ

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
+
スタックが正常に作成されたら、テキストボックスにLambda ARNを貼り付けます。

.. AWSアカウントと、アカウント、場所、セキュリティグループの追加情報は、FSx for ONTAPファイルシステムに基づいて自動的に取得されます。


. 「 * Create * 」を選択します。
+
リンクの作成ステータスは[Events]ページで監視できます。これには5分以内にかかります。

. ワークロードファクトリのインターフェイスに戻ると、リンクがFSx for ONTAPファイルシステムに関連付けられていることがわかります。


--
====
.結果
作成したリンクはFSx for ONTAPファイルシステムに関連付けられます。高度なONTAP処理を実行できます。



== 既存のリンクをFSx for ONTAPファイルシステムに関連付ける

リンクを作成したら、1つ以上のFSx for ONTAPファイルシステムに関連付けます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. [FSx for ONTAP *]タブで、リンクを関連付けるファイルシステムの3ドットメニューを選択し、*[Associate link]*を選択します。
. [リンクの関連付け]ページで*[既存のリンクの関連付け]*を選択し、リンクを選択して*[続行]*を選択します。
. 認証モードを選択します。
+
** Workload Factory：パスワードを2回入力します。
** AWS Secrets Manager：シークレットARNを入力します。
+
シークレットARNには、次のキー有効なペアを含める必要があります。

+
*** filesystemID = fsx_filesystem_id
*** ユーザ= FSX_USER
*** password = user_password




. * 適用 * を選択します。


.結果
リンクはFSx for ONTAPファイルシステムに関連付けられています。高度なONTAP処理を実行できます。



== AWS Secrets Managerのリンク認証に関する問題のトラブルシューティング

問題:: リンクにシークレットを取得する権限がありません。
+
--
*解決策*：リンクがアクティブになった後に権限を追加します。AWSコンソールにログインし、Lambdaリンクを見つけて、添付されている権限ポリシーを編集します。

--
問題:: その秘密は見つからない。
+
--
*解決策*：正しいシークレットARNを指定します。

--
問題:: その秘密は正しい形式ではない。
+
--
*解決方法*：AWS Secrets Managerに移動して形式を編集します。

シークレットには、次のキー有効なペアが含まれている必要があります。

* filesystemID = fsx_filesystem_id
* ユーザ= FSX_USER
* password = user_password


--
問題:: シークレットに、ファイルシステム認証用の有効なONTAPクレデンシャルが含まれていません。
+
--
*解決方法*：AWS Secrets ManagerでFSx for ONTAPファイルシステムを認証するためのクレデンシャルを指定します。

--

