---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: FSx for ONTAP ファイルシステムをセットアップしたら、ワークロードファクトリーに FSx for ONTAP ボリュームを作成します。 
---
= ワークロード ファクトリーで FSx for ONTAP ボリュームを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
FSx for ONTAP ファイルシステムをセットアップした後、データをグループ化するための仮想リソースとして、ワークロードファクトリーに FSx for ONTAP ボリュームを作成します。

.タスクの内容
FSx for ONTAP ボリュームはデータを仮想的にグループ化し、データの保存方法を決定し、データへのアクセスの種類を決定します。ボリュームはファイルシステムのストレージ容量を消費しません。ボリュームに格納されたデータは、主にSSDストレージを消費します。ボリュームの階層化ポリシーによっては、データが容量プールのストレージを消費する場合もあります。ボリュームのサイズは作成時に設定します。あとで変更することもできます。

ボリュームには次のプロトコルが使用されます。

* CIFS：Windowsオペレーティングシステム用のファイルストレージプロトコル
* NFS：UNIXオペレーティングシステム用のファイルストレージプロトコル
* iSCSI：ブロックストレージプロトコル


.開始する前に
ボリュームを作成する前に、次の前提条件を確認してください。

* ワークロード ファクトリー コンソールに FSx for ONTAP ファイル システムが必要です。
* Storage VMが必要です。
* プロトコルアクセスの場合は、次の手順を実行します。
+
** ボリュームへのアクセスを構成するには、リンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。
** 選択したプロトコル（CIFS、NFS、またはiSCSI）へのアクセスを設定する必要があります。






== ボリュームの作成

Codeboxで使用可能なREST API、CloudFormation、Terraformの各ツールを使用してボリュームを作成できます。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Codeboxを使用して自動化する方法"^]です。


NOTE: CodeboxからTerraformを使用すると、コピーまたはダウンロードしたコードが非表示になり、パスワードが表示され `fsxadmin` `vsadmin` ます。コードを実行するときは、パスワードを再入力する必要があります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、ボリュームを作成するファイルシステムの3ドットメニューを選択し、* Create volume *を選択します。
. [Create volume]ページの[General details]で、次の詳細を指定します。
+
.. *ボリューム名*：ボリュームの名前を入力します。
.. * Storage VM名*：必要に応じて、Storage VM名を入力します。
.. *ボリュームスタイル*：* FlexVol *または* FlexGroup * volumeを選択します。
+
FlexVolボリュームの形式はデフォルトで選択されています。

+
FlexGroup ボリュームのサイズは構成要素の数によって異なり、構成要素ごとに 100 GiB が必要です。

.. *ボリュームサイズ*：ボリュームサイズと単位を入力します。
+
必要に応じて、ボリュームの自動拡張を有効にします。このオプションは、ボリュームアクセスタイプとして*ファイルアクセス*を選択した場合に使用できます。

.. *ボリュームの自動拡張*：オプションでボリュームの自動拡張を有効にすると、ボリュームが最大サイズに達するまでボリューム容量が自動的に拡張されます。この機能は、データ使用量の増加に対応し、中断のない運用を保証します。
+
ボリュームの最大拡張サイズと単位を指定します。最大拡張サイズを現在のボリュームサイズより小さく設定することはできません

.. *タグ*:オプションで、最大50個のタグを追加できます。


. [Access]（リンクが関連付けられているファイルシステムの場合のみ）で、次の詳細を指定します。
+
.. *アクセスタイプ*：*ファイルアクセス*または*ブロックアクセス*を選択します。ボリュームアクセスを設定するための追加フィールドは、選択内容によって異なります。
+
*** *ファイルアクセス*：SMB / CIFS、NFS、またはデュアル（SMB / NFS）プロトコルを使用して、許可された複数のユーザとデバイスにボリュームへのアクセスを許可します。
+
次のフィールドに値を入力して、ボリュームへのファイルアクセスを設定します。

+
.... * NFSエクスポートポリシー*：NFSアクセスを提供するには、次の詳細を指定してください：
+
..... *アクセス制御*：ドロップダウンメニューから*[カスタムエクスポートポリシー]*、*[既存のエクスポートポリシー]*、または*[ボリュームへのアクセスなし]*を選択します。
..... *エクスポートポリシー名*：
+
カスタムエクスポートポリシーを選択した場合は、ドロップダウンメニューから既存のポリシー名を選択します。

+
既存のエクスポートポリシーを選択した場合は、新しいポリシー名を入力します。

..... *エクスポートポリシールールの追加*：必要に応じて、カスタムエクスポートポリシーの場合、エクスポートポリシールールをポリシーに追加できます。


.... * CIFS共有*：次の情報を指定します。
+
..... *名前*：SMBアクセスを提供するCIFS共有名を入力します。
..... *権限*：[フルコントロール]、[読み取り/書き込み]、[読み取り]、または[アクセスなし]を選択し、ユーザまたはグループをセミコロン（;）で区切って入力します。ユーザまたはグループでは大文字と小文字が区別されます。ユーザのドメインは「domain\username」の形式で指定する必要があります。


.... *セキュリティ形式*：デュアルプロトコルボリュームの場合は、UNIXまたはNTFSのいずれかのセキュリティ形式を選択します。UNIXは、デュアルプロトコルボリュームのデフォルトのセキュリティ形式です。このコンテキストでのユーザマッピングの詳細なガイダンスについては、AWSブログ記事を参照してlink:https://aws.amazon.com/blogs/storage/enabling-multiprotocol-workloads-with-amazon-fsx-for-netapp-ontap["Amazon FSx for NetApp ONTAPでマルチプロトコルワークロードを実現"^]ください。


*** *ブロックアクセス*：重要なビジネスアプリケーションを実行しているホストがiSCSIプロトコルを使用してボリュームにアクセスできるようにします。ブロックアクセスは、ファイルシステムのスケールアウト構成のHAペアが6つ以下の場合にのみ使用できます。
+
ボリュームへのブロックアクセスを設定するには、次のフィールドに値を入力します。

+
.... * iSCSIの設定*：ボリュームへのブロックアクセス用にiSCSIを設定するには、以下の詳細を指定してください。
+
..... [新しいイニシエータグループを作成する]*または*[既存のイニシエータグループをマッピングする]*を選択します。
..... ドロップダウンメニューから*[ホストオペレーティングシステム]*を選択します。
..... 新しいイニシエータグループの*イニシエータグループ名*を入力します。
..... [Host Initiators]で、1つ以上のiSCSI Qualified Name（IQN）ホストイニシエータを追加します。








. [Efficiency and protection]で、次の詳細を指定します。
+
.. *ストレージ効率*: デフォルトで有効になっています。この機能を無効にするには選択します。
+
ONTAPは、重複排除機能と圧縮機能を活用してストレージ効率を実現します。重複排除機能は重複するデータブロックを排除し、データ圧縮機能はデータブロックを圧縮することで、必要な物理ストレージ容量を削減します。

.. * Snapshotポリシー*：Snapshotポリシーを選択して、Snapshotの頻度と保持を指定します。
+
AWSのデフォルトポリシーは次のとおりです。カスタムスナップショットポリシーの場合は、 link:link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["リンクの関連付け"] 。

+
`default`:: このポリシーでは、次のスケジュールでSnapshotが自動的に作成され、新しいコピー用のスペースを確保するために最も古いSnapshotコピーが削除されます。
+
--
*** 最大6つの時間単位のスナップショットが毎時5分に作成されます。
*** 最大2つの日次スナップショットが月曜日から土曜日の午前0時10分に作成されます。
*** 最大2つの週単位Snapshotが毎週日曜日の午前0時15分に作成されます。
+

NOTE: Snapshotの時間はファイルシステムのタイムゾーンに基づいており、デフォルトは協定世界時（UTC）です。タイムゾーンの変更については、NetAppのサポートドキュメントのを参照してください link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["システムのタイムゾーンの表示と設定"^] 。



--
`default-1weekly`:: このポリシーはポリシーと同様に機能し `default` ますが、週次スケジュールのSnapshotが1つだけ保持されます。
`none`:: このポリシーではスナップショットは作成されません。このポリシーをボリュームに割り当てると、自動Snapshotが作成されないようにすることができます。


.. *階層化ポリシー*：ボリュームに格納されているデータの階層化ポリシーを選択します。
+
_Balanced（Auto）_は、ワークロード工場出荷時のコンソールを使用してボリュームを作成する際のデフォルトの階層化ポリシーです。ボリューム階層化ポリシーの詳細については、AWS FSx for NetApp ONTAPドキュメントのを参照してください link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["ボリュームのストレージ容量"^] 。ワークロードファクトリでは、階層化ポリシーにワークロードファクトリコンソールのユースケースベースの名前が使用され、かっこ内にFSx for ONTAP階層化ポリシー名が含まれていることに注意してください。

.. *変更不可ファイル*:この機能はSnapLockとも呼ばれ、デフォルトでは無効になっています。不変ファイルを有効にすると、一定期間データの削除や上書きが防止されます。この機能は、ボリュームの作成時にのみ有効にできます。この機能は、一度有効にすると無効にすることはできません。これは追加料金が発生するFSx for ONTAPのプレミアム機能です。詳細については、Amazon FSx for NetApp ONTAPドキュメントのを参照してlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/how-snaplock-works.html["SnapLockの仕組み"^]ください。
+
書き換え不能ファイル機能を有効にすると、このボリューム内のファイルが書き換え不能WORM（Write-Once-Read-Many）状態に永続的にコミットされます。

+
保持モード:: 2つの保持モード（_Enterprise_or_Compliance_）から選択できます。
+
--
*** _ENTERPRISE_MODEでは、管理者は変更不可のファイル（SnapLock）を保持期間中にファイルを削除できます。
*** _Compliance_modeでは、WORMファイルは保持期間が終了するまで削除できません。同様に、変更不可のボリュームは、ボリューム内のすべてのファイルの保持期間が終了するまで削除できません。


--
保持期間:: 保持期間には、_retention policy_and_retention periods_という2つの設定があります。保持ポリシー：書き換え不可のWORM状態でファイルを保持する期間を定義します。独自の保持ポリシーを指定するか、デフォルトの保持ポリシー（未指定）（30年）を使用できます。最小保持期間と最大保持期間_は、ファイルのロックに許可される期間を定義します。
+
--
注:: 保持期間が経過したあともWORMファイルを変更することはできません。削除するか、新しい保持期間を設定してWORM保護を再度有効にすることしかできません。


--
自動コミット:: 自動コミット機能を有効にするオプションがあります。自動コミット期間内にファイルに変更がなかった場合、自動コミット機能によってSnapLockボリューム上でファイルがWORM状態にコミットされます。自動コミット機能は、デフォルトでは無効になっています。自動コミットするファイルが SnapLock ボリューム上に存在することを確認する必要があります。
ボリュームアペンドモード:: WORMで保護されたファイル内の既存のデータを変更することはできません。ただし、変更不可のファイルを使用すると、追記可能WORMファイルを使用して既存データを保護できます。たとえば、ログファイルを生成したり、オーディオまたはビデオストリーミングデータを保持しながら、データを段階的に書き込むことができます。link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/worm-state.html#worm-state-append["ボリュームアペンドモードに関する詳細情報"^]を参照してNetApp ONTAPください。
+
--
.不変ファイルの手順
... 選択すると、* SnapLockを使用した変更不可ファイル*が有効になります。
... 同意して続行するには、ボックスを選択してください。
... [ 有効 ] を選択します。
... *保持モード*：*エンタープライズ*または*コンプライアンス*モードを選択します。
... *保持期間*：
+
**** 保持ポリシーを選択します。
+
***** *未指定*：保持ポリシーを30年に設定します。
***** *期間の指定*：独自の保持ポリシーを設定する秒数、分数、時間数、日数、月数、または年数を入力します。


**** 最小保持期間と最大保持期間を選択します。
+
***** *最小*：最小保持期間を設定する秒数、分数、時間数、日数、月数、または年数を入力します。
***** *最大*：最大保持期間を設定する秒数、分数、時間数、日数、月数、または年数を入力します。




... * autocommit *：自動コミットを無効または有効にします。自動コミットを有効にする場合は、自動コミット期間を設定します。
... *ボリュームアペンドモード*：無効または有効にします。WORMファイルに新しいコンテンツを追加できます。


--


.. *ARP/AI*: リンクがファイル システムに関連付けられている場合、NetApp Autonomous Ransomware Protection with AI (ARP/AI) はデフォルトで有効になります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["ARP/AIについて詳しくはこちら"]です。続行するには、ステートメントを受け入れます。
+
機能が利用できない場合は、次のいずれかの理由が考えられます。

+
*** リンクはファイル システムに関連付けられていません。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。
*** 不変のファイルを含むボリューム、および iSCSI および NVMe プロトコルを含むボリュームは、ARP/AI ではサポートされません。
*** ファイル システムには既に ARP/AI ポリシーがあります。




. [Advance configuration]で、次の情報を指定します。
+
.. *ジャンクションパス*：ボリュームをマウントするStorage VMのネームスペース内の場所を入力します。デフォルトのジャンクションパスはです `/<volume-name>`。
.. *アグリゲートリスト*：FlexGroupボリュームのみ。アグリゲートを追加または削除します。アグリゲートの最小数は1です。
.. *コンスティチュエントの数*：FlexGroupボリュームの場合のみ。アグリゲートあたりのコンスティチュエントの数を入力します。コンスティチュエントあたり100GiBが必要です。


. 「 * Create * 」を選択します。


.結果
ワークロードファクトリーがボリュームの作成を開始します。ボリュームが作成されると、システムは「ボリューム」タブに新しいボリュームを表示します。
