---
sidebar: sidebar 
permalink: create-snapshot.html 
keywords: create snapshot, snapshot 
summary: NetApp Workload Factory で FSx for ONTAPボリュームの手動スナップショットを作成します。スナップショットは、ボリュームのコンテンツの特定時点のバージョンです。 
---
= FSx for ONTAPボリュームの手動スナップショットの作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory で FSx for ONTAPボリュームの手動スナップショットを作成します。スナップショットは、ボリュームのコンテンツの特定時点のバージョンです。

Snapshotはボリュームのリソースであり、変更されたデータのためだけにスペースを消費するデータを瞬時にキャプチャします。データは時間の経過とともに変化するため、Snapshotは通常、古くなるにつれてより多くのスペースを消費します。

FSx for ONTAPボリュームではジャストインタイムのcopy-on-writeが使用されるため、Snapshot内の変更されていないファイルがボリュームの容量を消費することはありません。


NOTE: スナップショットはデータのコピーではありません。データのコピーを作成する場合は、FSx for ONTAPのバックアップ機能やボリュームレプリケーション機能の使用を検討してください。

.開始する前に
ボリュームの手動スナップショットを作成するには、リンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ストレージ タイルで、[ストレージへ移動] を選択します。
. [ストレージ] メニューから、*FSx for ONTAP* を選択します。
. *FSx for ONTAP*から、スナップショットを作成するボリュームを含むファイルシステムのアクションメニューを選択し、*管理*を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. *ボリューム* タブから、スナップショットで保護するボリュームのアクション メニューを選択します。
. *データ保護アクション*を選択し、*スナップショットの管理*を選択します。
. スナップショットの管理ページで、*スナップショットの作成*を選択します。
. [スナップショットの作成] ダイアログで、次の操作を行います。
+
.. *スナップショット名* フィールドにスナップショット名を入力します。
.. 必要に応じて、ラベルを選択するか、新しいラベルを作成します。
.. [Retention Period]*に、時間、日、月、または年数を設定します。
.. オプション: *このスナップショットを不変にする* ことで、保持期間中にスナップショットが削除されるのを防ぎます。
+
変更不可のスナップショットに関するステートメントを受け入れます。



. 「 * Create * 」を選択します。

