---
sidebar: sidebar 
permalink: create-block-device.html 
keywords: create block device, create lun, iscsi protocol 
summary: '基幹業務 (LOB) アプリケーション要件をサポートするブロック デバイスを作成します。' 
---
= NetApp Workload Factoryでファイルシステム用のブロックデバイスを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
基幹業務 (LOB) アプリケーション要件をサポートするブロック デバイスを作成します。

.タスクの内容
NetApp Workload Factoryのブロック デバイスでは、 FlexVolボリュームのみがサポートされます。iSCSI プロトコルを使用してブロック デバイスを作成できます。

ブロック サイズは、使用可能なFlexVol volumeサイズよりも小さくする必要があります。

.開始する前に
* ブロック デバイスを作成するには、リンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]。リンクを関連付けたら、この操作に戻ります。


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ストレージ タイルで、[ストレージへ移動] を選択します。
. [ストレージ] メニューから、*FSx for ONTAP* を選択します。
. *FSx for ONTAP*から、*ブロック デバイス* タブを選択します。
. *ブロックデバイスの作成*を選択します。
. *ボリュームの詳細*で、次の操作を行います。
+
.. *ボリューム名*: 次のいずれかのオプションを選択します。
+
*** 新しいボリュームを作成し、ボリュームの名前を入力します。
*** 既存のボリュームを選択します。


.. *ストレージ VM*: ストレージ VM を選択します。
.. *ボリューム スタイル*: デフォルトのボリューム スタイルは * FlexVol* です。
.. *ボリューム サイズ*: ボリュームのサイズを入力し、単位を選択します。FlexVol volumeあたりの最大サイズは 100 TiB です。
.. *ボリュームの自動拡張*: オプションで、ボリュームの自動拡張を有効にして、ボリュームが容量に達したときにサイズが自動的に増加するようにします。最大拡張サイズは 300 TiB です。
.. *タグ*: オプションで、ブロックデバイスを整理および分類するためにタグを追加します。


. *ブロックデバイスの詳細*で、次の操作を行います。
+
.. *ブロックデバイス名*: ブロックデバイスの名前を入力します。
.. *ブロック デバイス サイズ*: ブロック デバイスのサイズを入力し、単位を選択します。ブロック デバイスのサイズは、使用可能なボリューム サイズよりも小さくする必要があります。


. *アクセス* で、次の操作を行います。
+
.. *iSCSI 構成*: 次のいずれかのオプションを選択します。
+
*** *新しいイニシエーター グループの作成*: ホスト オペレーティング システム、イニシエーター グループ名を指定し、1 つ以上の iSCSI 修飾名 (IQN) ホスト イニシエーターを追加します。
*** *既存のイニシエーター グループのマップ*: 既存のイニシエーター グループを選択し、ホスト オペレーティング システムを指定して、1 つ以上の iSCSI 修飾名 (IQN) ホスト イニシエーターを選択します。




. *効率と保護*の下で、次の操作を行います。
+
.. *ストレージ効率*: デフォルトで有効になっています。この機能を無効にするには選択します。
+
ONTAPは、重複排除機能と圧縮機能を活用してストレージ効率を実現します。重複排除機能は重複するデータブロックを排除し、データ圧縮機能はデータブロックを圧縮することで、必要な物理ストレージ容量を削減します。

.. * Snapshotポリシー*：Snapshotポリシーを選択して、Snapshotの頻度と保持を指定します。
+
以下は AWS のデフォルトポリシーです。既存のスナップショットポリシーを表示するには、 link:link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["リンクの関連付け"]。

+
`default`:: このポリシーでは、次のスケジュールでSnapshotが自動的に作成され、新しいコピー用のスペースを確保するために最も古いSnapshotコピーが削除されます。
+
--
*** 最大6つの時間単位のスナップショットが毎時5分に作成されます。
*** 最大2つの日次スナップショットが月曜日から土曜日の午前0時10分に作成されます。
*** 最大2つの週単位Snapshotが毎週日曜日の午前0時15分に作成されます。
+

NOTE: Snapshotの時間はファイルシステムのタイムゾーンに基づいており、デフォルトは協定世界時（UTC）です。タイムゾーンの変更については、NetAppのサポートドキュメントのを参照してください link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["システムのタイムゾーンの表示と設定"^] 。



--
`default-1weekly`:: このポリシーはポリシーと同様に機能し `default` ますが、週次スケジュールのSnapshotが1つだけ保持されます。
`none`:: このポリシーではスナップショットは作成されません。このポリシーをボリュームに割り当てると、自動Snapshotが作成されないようにすることができます。


.. *階層化ポリシー*：ボリュームに格納されているデータの階層化ポリシーを選択します。
+
_バランス (自動)_ は、Workload Factory コンソールを使用してボリュームを作成するときのデフォルトの階層化ポリシーです。ボリューム階層化ポリシーの詳細については、以下を参照してください。 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["ボリュームのストレージ容量"^] AWS FSx for NetApp ONTAPドキュメント。Workload Factory では、階層化ポリシーに Workload Factory コンソールでユースケース ベースの名前が使用され、括弧内に FSx for ONTAP階層化ポリシー名が含まれていることに注意してください。

.. *ARP/AI*: リンクがファイル システムに関連付けられている場合、NetApp Autonomous Ransomware Protection with AI (ARP/AI) はデフォルトで有効になります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["ARP/AIについて詳しくはこちら"]です。続行するには、ステートメントを受け入れます。
+
機能が利用できない場合は、次のいずれかの理由が考えられます。

+
*** リンクはファイル システムに関連付けられていません。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。
*** 不変ファイルを含むボリュームと NVMe プロトコルを使用するボリュームは、ARP/AI ではサポートされません。
*** ファイル システムには既に ARP/AI ポリシーがあります。




. 「 * Create * 」を選択します。


.関連情報
link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["FSx for ONTAPファイルシステムのブロックデバイスを管理する"]
