---
sidebar: sidebar 
permalink: create-backup.html 
keywords: create backup, volume backup, back up a volume 
summary: 定期的にスケジュールされたバックアップ以外で、ボリュームの手動バックアップを作成します。 
---
= ボリュームの手動バックアップの作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
定期的にスケジュールされたバックアップ以外で、ボリュームの手動バックアップを作成します。

.タスクの内容
FSx for ONTAPのバックアップはボリューム単位で行われるため、各バックアップには特定のボリューム内のデータのみが含まれます。

FSx for ONTAPバックアップは増分バックアップです。つまり、最新のバックアップ後に変更されたボリューム上のデータのみが保存されます。これにより、バックアップの作成に必要な時間とバックアップに必要なストレージを最小限に抑えることができ、データを複製しないことでストレージコストを削減できます。

.開始する前に
ボリュームのバックアップを作成するには、ボリュームとファイルシステムの両方に、バックアップSnapshotを格納するための十分なSSDストレージ容量が必要です。バックアップスナップショットの作成時に、スナップショットによって消費される追加のストレージ容量によって、ボリュームのSSDストレージ利用率が98%を超えることはありません。この場合、バックアップは失敗します。

.手順
. にログインします。 link:https://console.workloads.netapp.com/["Workload Factoryコンソール"^]
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、ボリュームを含むファイルシステムの3つのドットメニューをクリックし、* Manage *を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [Volumes]*タブで、バックアップするボリュームの3つのドットメニューをクリックします。
. *データ保護アクション*、* FSx for ONTAPバックアップ*、*手動バックアップ*の順に選択します。
. [Manual backup]ダイアログで、バックアップの名前を入力します。
. [バックアップ]*をクリックします。

