---
sidebar: sidebar 
permalink: create-file-system.html 
keywords: create, FSx file system, ONTAP file system, workload factory, storage 
summary: BlueXP  ワークロードファクトリを使用すると、FSx for ONTAPファイルシステムを作成して、ボリュームと追加データサービスを追加および管理できます。 
---
= BlueXP  ワークロード工場でFSx for ONTAPファイルシステムを作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロードファクトリを使用すると、FSx for ONTAPファイルシステムを作成して、ボリュームと追加データサービスを追加および管理できます。

.タスクの内容
Storage VMとセキュリティグループは、ファイルシステムの作成時に作成されます。

.開始する前に
FSx for ONTAPファイルシステムを作成する前に、以下が必要になります。

* FSx for ONTAPファイルシステムの作成に必要な権限をワークロードファクトリに付与するIAMロールのARN。link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWSアカウントに権限を付与する方法を確認する"^]です。
* ONTAP インスタンスの FSX を作成する場所のリージョンおよび VPC 情報。




== FSx for ONTAPファイルシステムの作成

FSx for ONTAPファイルシステムは、_Quick create_or_Advanced create_を 使用して作成できます。Codeboxで利用可能なREST API、CloudFormation、Terraformの各ツールを使用することもできます。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Codeboxを使用して自動化する方法"^]です。


NOTE: CodeboxからTerraformを使用すると、コピーまたはダウンロードしたコードが非表示になり、パスワードが表示され `fsxadmin` `vsadmin` ます。コードを実行するときは、パスワードを再入力する必要があります。

[role="tabbed-block"]
====
.クイック作成
--
クイック作成を使用すると、推奨されるベストプラクティス構成を使用できます。ほとんどの設定は、FSx for ONTAPファイルシステムの作成後に変更できます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ストレージで、* Create FSx for ONTAP *を選択します。
. [FSx for ONTAPの作成]ページで、*[クイック作成]*を選択します。
+
保存されている設定をロードすることもできます。

. [File system general configuration]で、次の情報を指定します。
+
.. * AWSクレデンシャル*：ワークロード工場でAWSクレデンシャルを追加する場合、またはクレデンシャルなしで続行する場合に選択します。
.. *ファイルシステム名*：ファイルシステムの名前を入力します。
.. *導入トポロジ*:導入トポロジを選択します。
+
*** スケールアップトポロジでは、1つのファイルシステムをデータ分散に使用し、データの増大に合わせてサイズを拡張できます。
*** スケールアウトトポロジでは、データ分散に複数のファイルシステムが使用されます。


.. * HAペア*：HAペアの数を入力します。
+
*** スケールアップ環境ではHAペアを1つだけ作成できます。
*** スケールアウト環境では、2~12個のHAペアを設定できます。
+
ファイルシステムにiSCSIブロックボリュームをプロビジョニングする場合は、HAペアを6つまで選択してください。



.. *導入タイプ*：導入タイプを選択します。
+
*** 単一アベイラビリティゾーン（単一アベイラビリティゾーン）の導入：ハードウェア障害を監視し、障害発生時にインフラコンポーネントを自動的に交換することで可用性を提供します。アベイラビリティゾーン内にデータを自動的にレプリケートし、コンポーネント障害からデータを保護することで、高い耐久性を実現します。
*** 複数のアベイラビリティゾーン（マルチAZ）の導入：アベイラビリティゾーンが使用できない場合でも、データの継続的可用性を提供します。マルチAZファイルシステムは、シングルAZファイルシステムの可用性と耐久性のすべての機能をサポートしています。Multi-AZファイルシステムは、共有ONTAPファイルデータの高可用性を必要とし、複数のアベイラビリティゾーンにわたるレプリケーション機能を備えたストレージを必要とする、ビジネスクリティカルな本番ワークロード向けに設計されています。


.. *タグ*:オプションで、最大50個のタグを追加できます。


. [ネットワークとセキュリティ]*の*[リージョンとVPC]*フィールドで、ファイルシステムのリージョンとVPCを選択します。
. [ファイルシステムの詳細]*で、次の情報を入力します。
+
.. * SSDストレージ容量*：ストレージ容量を入力し、ストレージ容量の単位を選択します。
.. * ONTAPクレデンシャル*：ONTAPのユーザ名とパスワードを入力します。
.. * SMB / CIFSのセットアップ*：オプション。SMB / CIFSプロトコルを使用してボリュームにアクセスする場合は、ファイルシステムの作成時にStorage VMのActive Directoryを設定する必要があります。このファイルシステム用に作成されるStorage VMに関する以下の詳細を指定してください。
+
... *参加するActive Directoryドメイン*：Active Directoryの完全修飾ドメイン名（FQDN）を入力します。
... * DNS IPアドレス*：DNS IPアドレスをカンマで区切って3つまで入力します。
... * SMBサーバのNetBIOS名*：Storage VM用に作成するActive DirectoryコンピュータオブジェクトのSMBサーバのNetBIOS名を入力します。これは、Active Directory内のこのStorage VMの名前です。
... *ユーザー名*：既存のActive Directory内のサービスアカウントのユーザー名を入力します。
+
ドメインのプレフィックスまたはサフィックスは含めないでください。の場合は `EXAMPLE\ADMIN`、を使用し `ADMIN`ます。

... *パスワード*：サービスアカウントのパスワードを入力します。
... *組織単位*：必要に応じて、FSx for ONTAPのコンピュータアカウントを作成する組織単位の名前を入力します。OUは、ファイルシステムに参加する組織単位の識別パス名です。
... *委任管理者グループ*:必要に応じて、ファイルシステムを管理できるActive Directory内のグループの名前を入力します。
+
AWS Managed Microsoft ADを使用している場合は、AWS Delegated FSx Administrators、AWS Delegated Administratorsなどのグループ、またはOUに権限を委譲されたカスタムグループを指定する必要があります。

+
自己管理型ADに参加する場合は、AD内のグループ名を使用します。デフォルトのグループはです `Domain Admins`。





. [Summary]*を開き、定義した構成を確認します。必要に応じて、ファイルシステムを保存または作成する前に、この時点で任意の設定を変更できます。
. ファイルシステムを保存または作成します。


ファイルシステムを作成した場合は、*インベントリ*ページでFSx for ONTAPファイルシステムを確認できるようになりました。

--
.高度な作成
--
Advanced createでは、可用性、セキュリティ、バックアップ、メンテナンスなど、すべての構成オプションを設定できます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ストレージで、* Create FSx for ONTAP *を選択します。
. [FSx for ONTAPの作成]ページで、*[Advanced create]*を選択します。
+
保存されている設定をロードすることもできます。

. [File system general configuration]で、次の情報を指定します。
+
.. * AWSクレデンシャル*：ワークロード工場でAWSクレデンシャルを追加する場合、またはクレデンシャルなしで続行する場合に選択します。
.. *ファイルシステム名*：ファイルシステムの名前を入力します。
.. *導入トポロジ*:導入トポロジを選択します。
+
*** スケールアップトポロジでは、1つのファイルシステムをデータ分散に使用し、データの増大に合わせてサイズを拡張できます。
*** スケールアウトトポロジでは、データ分散に複数のファイルシステムが使用されます。


.. * HAペア*：HAペアの数を入力します。
+
*** スケールアップ環境ではHAペアを1つだけ作成できます。
*** スケールアウト環境では、2~12個のHAペアを設定できます。
+
ファイルシステムにiSCSIブロックボリュームをプロビジョニングする場合は、HAペアを6つまで選択してください。



.. *導入タイプ*：導入タイプを選択します。
+
*** 単一アベイラビリティゾーン（単一アベイラビリティゾーン）の導入：ハードウェア障害を監視し、障害発生時にインフラコンポーネントを自動的に交換することで可用性を提供します。アベイラビリティゾーン内にデータを自動的にレプリケートし、コンポーネント障害からデータを保護することで、高い耐久性を実現します。
*** 複数のアベイラビリティゾーン（マルチAZ）の導入：アベイラビリティゾーンが使用できない場合でも、データの継続的可用性を提供します。マルチAZファイルシステムは、シングルAZファイルシステムの可用性と耐久性のすべての機能をサポートしています。Multi-AZファイルシステムは、共有ONTAPファイルデータの高可用性を必要とし、複数のアベイラビリティゾーンにわたるレプリケーション機能を備えたストレージを必要とする、ビジネスクリティカルな本番ワークロード向けに設計されています。


.. *タグ*:オプションで、最大50個のタグを追加できます。


. [ネットワークとセキュリティ]で、次の情報を入力します。
+
.. *リージョンとVPC *：ファイルシステムのリージョンとVPCを選択します。
.. *セキュリティグループ*：既存のセキュリティグループを作成または使用します。
+
新しいセキュリティグループの場合、セキュリティグループのプロトコル、ポート、およびロールの説明については、を参照してください<<セキュリティグループの詳細,セキュリティグループの詳細>>。

.. *アベイラビリティゾーン*：アベイラビリティゾーンとサブネットを選択します。
+
*** クラスタ構成ノード1：アベイラビリティゾーンとサブネットを選択します。
*** クラスタ構成ノード2：アベイラビリティゾーンとサブネットを選択します。


.. * VPCルートテーブル*：VPCルートテーブルを選択して、ボリュームへのクライアントアクセスを有効にします。
.. *エンドポイントIPアドレス範囲*：*[Floating IP address range outside your VPC]*または*[Enter an IP address range]*を選択し、IPアドレス範囲を入力します。
.. *暗号化*：ドロップダウンから暗号化キー名を選択します。


. [File system details]で、次の情報を入力します。
+
.. * SSDストレージ容量*：ストレージ容量を入力し、ストレージ容量の単位を選択します。
.. *[Provisioned IOPS]*：*[Automatic]*または*[User-Provisioned]*を選択します。
.. * HAペアあたりのスループット容量*：HAペアあたりのスループット容量を選択します。
.. * ONTAPクレデンシャル*：ONTAPのユーザ名とパスワードを入力します。
.. * Storage VMクレデンシャル*：ユーザ名を入力します。このファイルシステムに固有のパスワードを指定することも、ONTAPクレデンシャルに入力したパスワードと同じパスワードを使用することもできます。
.. * SMB / CIFSのセットアップ*：オプション。SMB / CIFSプロトコルを使用してボリュームにアクセスする場合は、ファイルシステムの作成時にStorage VMのActive Directoryを設定する必要があります。このファイルシステム用に作成されるStorage VMに関する以下の詳細を指定してください。
+
... *参加するActive Directoryドメイン*：Active Directoryの完全修飾ドメイン名（FQDN）を入力します。
... * DNS IPアドレス*：DNS IPアドレスをカンマで区切って3つまで入力します。
... * SMBサーバのNetBIOS名*：Storage VM用に作成するActive DirectoryコンピュータオブジェクトのSMBサーバのNetBIOS名を入力します。これは、Active Directory内のこのStorage VMの名前です。
... *ユーザー名*：既存のActive Directory内のサービスアカウントのユーザー名を入力します。
+
ドメインのプレフィックスまたはサフィックスは含めないでください。の場合は `EXAMPLE\ADMIN`、を使用し `ADMIN`ます。

... *パスワード*：サービスアカウントのパスワードを入力します。
... *組織単位*：必要に応じて、FSx for ONTAPのコンピュータアカウントを作成する組織単位の名前を入力します。OUは、ファイルシステムに参加する組織単位の識別パス名です。
... *委任管理者グループ*:必要に応じて、ファイルシステムを管理できるActive Directory内のグループの名前を入力します。
+
AWS Managed Microsoft ADを使用している場合は、AWS Delegated FSx Administrators、AWS Delegated Administratorsなどのグループ、またはOUに権限を委譲されたカスタムグループを指定する必要があります。

+
自己管理型ADに参加する場合は、AD内のグループ名を使用します。デフォルトのグループはです `Domain Admins`。





. [Backup and maintenance]で、次の情報を入力します。
+
.. * FSx for ONTAPバックアップ*：毎日の自動バックアップはデフォルトで有効になっています。必要に応じて無効にします。
+
... *自動バックアップ保持期間*：自動バックアップを保持する日数を入力します。
... *日次自動バックアップウィンドウ*：*設定なし*（日次バックアップの開始時間を選択）または*日次バックアップの開始時間を選択*のいずれかを選択し、開始時間を指定します。
... *週次メンテナンス時間*：*設定なし*（週次メンテナンス時間の開始時間を選択）または*週次メンテナンス時間30分の開始時間を選択*のいずれかを選択し、開始時間を指定します。




. ファイルシステムを保存または作成します。


ファイルシステムを作成した場合は、*インベントリ*ページでFSx for ONTAPファイルシステムを確認できるようになりました。

--
====


== セキュリティグループの詳細

次の表に、セキュリティグループの詳細（プロトコル、ポート、ロールなど）を示します。

[]
====
[cols="2,2,4a"]
|===
| プロトコル | ポート | ロール 


| SSH | 22  a| 
クラスタ管理 LIF またはノード管理 LIF の IP アドレスへの SSH アクセス



| TCP | 80  a| 
クラスタ管理LIFのIPアドレスへのWebページアクセス



| TCP / UDP | 111  a| 
NFS のリモートプロシージャコール



| TCP / UDP | 135  a| 
CIFS のリモートプロシージャコール



| UDP | 137  a| 
CIFSノNetBIOSメイカイケツ



| TCP / UDP | 139  a| 
CIFS の NetBIOS サービスセッション



| TCP | 443  a| 
クラスタ管理LIFまたはSVM管理LIFのIPアドレスへのONTAP REST APIアクセス



| TCP | 445  a| 
NetBIOS フレーム同期を使用した Microsoft SMB over TCP



| TCP / UDP | 635  a| 
NFSマウント



| TCP | 749  a| 
Kerberos



| TCP / UDP | 2049  a| 
NFSサーバデーモン



| TCP | 3260  a| 
iSCSI データ LIF を介した iSCSI アクセス



| TCP / UDP | 4045  a| 
NFSロックデーモン



| TCP / UDP | 4046  a| 
NFS のネットワークステータスモニタ



| UDP | 4049  a| 
NFSクォータプロトコル



| TCP | 10000  a| 
Network Data Management Protocol（NDMP；ネットワークデータ管理プロトコル）とNetApp SnapMirrorのクラスタ間通信



| TCP | 11104  a| 
NetApp SnapMirrorのクラスタ間通信の管理



| TCP | 11105  a| 
クラスタ間 LIF を使用した SnapMirror データ転送



| TCP / UDP | 161-162  a| 
Simple Network Management Protocol（SNMP；簡易ネットワーク管理プロトコル）



| すべての ICMP | すべて  a| 
インスタンスの ping を実行します

|===
====
.次のステップ
ストレージインベントリにファイルシステムを格納することで、FSx for ONTAPファイルシステムの管理やリソースのセットアップを行うことができます link:create-volume.html["ボリュームの作成"] link:data-protection-overview.html["データ保護"] 。
