---
sidebar: sidebar 
permalink: create-volume-from-snapshot.html 
keywords: create volume from snapshot, new volume 
summary: FSx for ONTAPボリュームの手動スナップショットを作成します。スナップショットは、ボリュームのコンテンツのポイントインタイムバージョンです。 
---
= スナップショットから新しいFSx for ONTAPボリュームを作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
スナップショットから新しいFSx for ONTAPボリュームを作成し、ポイントインタイムリカバリを可能にします。

.タスクの内容
Snapshotは、ある時点で作成されたFSx for ONTAPボリュームの読み取り専用イメージです。Snapshotから新しいボリュームを作成すると、ボリュームサイズに関係なく、ボリューム全体のコピーが数秒以内に作成されます。新しく作成されたコピーは新しいボリュームを表します。

.開始する前に
Snapshotからボリュームを作成する前に、次の制限事項を考慮してください。

* 権限モデルの変更：この処理を使用してNetwork-Attached Storage（NAS；ネットワーク接続型ストレージ）プロトコルタイプを切り替えると、セキュリティ形式で提供される権限モデルも切り替える可能性があります。ファイルアクセス権限の問題が発生する可能性があります。この問題は、NASクライアントツールを使用して権限の設定を行う管理者アクセスでのみ手動で修正できます。
* ボリューム消費量の増加：Snapshotからボリュームを作成すると、2つの独立したボリュームが作成され、どちらもホストファイルシステムの容量を消費します。


.手順
. Workload Factoryコンソールにログインします。
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、ボリュームSnapshotが含まれているファイルシステムの3つの点のメニューをクリックし、*[管理]*を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [Volumes]タブで、ボリュームを作成するSnapshotがあるボリュームの3つのドットメニューをクリックします。
. [データ保護操作]*、*[ Snapshot ]*を選択し、*[ Snapshotからのボリュームの作成]*を選択します。
. [Create volume from a snapshot]ダイアログで、Snapshot名を入力します。
. [ 作成（ Create ） ] をクリックします。

