---
sidebar: sidebar 
permalink: create-cyber-vault.html 
keywords: create cyber vault, volume cyber vault, protect data cyber vault, cyber vault setup 
summary: NetAppサイバー ボールトについて、またランサムウェアやサイバー脅威からデータを保護するためのサイバー ボールト アーキテクチャの実装方法について学習します。 
---
= サイバーボールトでデータを保護
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
サイバー ボールト ボリュームは、データのバックアップ コピーを保存し、ランサムウェア攻撃やその他のサイバー脅威からデータを保護するために使用する、隔離された安全なストレージの場所です。ボールト作成の一環として、サイバー ボールト ボリュームを作成し、すべてのクライアント プロトコルを無効にし、ソース ボリュームとサイバー ボールト ボリューム間のレプリケーション関係を設定し、サイバー ボールト ボリューム上に不変のスナップショットを作成します。

.サイバーボールトとは何ですか?
サイバー ボールトは、主要な IT インフラストラクチャとは別の隔離された環境に重要なデータを保存する特定のデータ保護技術です。

サイバー ボールトは、マルウェア、ランサムウェア、さらには内部脅威など、メイン ネットワークに影響を及ぼす脅威の影響を受けない、「エアギャップ」された、変更不可能で消去不可能なデータ リポジトリです。サイバー金庫は、変更不可能かつ消去不可能なスナップショットによって実現できます。

従来の方法を使用するエアギャップ バックアップでは、スペースを作成し、プライマリ メディアとセカンダリ メディアを物理的に分離する必要があります。メディアをオフサイトに移動したり、接続を切断したりすることで、悪意のある人物がデータにアクセスできなくなります。これによりデータは保護されますが、回復時間が遅くなる可能性があります。

.ONTAPサイバーボールト向け FSx
Amazon FSx for NetApp ONTAP は、サイバー ボールトのソースおよびターゲットとしてサポートされています。

.導入
Workload Factory は、サイバー ボールト アーキテクチャの作成を支援します。  NetAppに連絡してサイバー ボールトの実装に関心があることを伝えると、 NetApp のスペシャリストがお客様に連絡して要件について話し合います。

開始するには、ng-FSx-CyberVault@netapp.com に電子メールを送信してください。

.関連情報
サイバー金庫とこのアーキテクチャの設定方法の詳細については、 link:https://docs.netapp.com/us-en/netapp-solutions-dataops/cyber-vault/ontap-cyber-vault-overview.html["ONTAPサイバー ボールトのドキュメント"^]。
