---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: FSx for ONTAPファイルシステムのセットアップが完了したら、FSx for ONTAPボリュームを作成できます。 
---
= FSx for ONTAPボリュームの作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
FSx for ONTAPファイルシステムのセットアップが完了したら、FSx for ONTAPボリュームを作成できます。

.タスクの内容
FSx for ONTAPボリュームは、データのグループ化、データの保存方法の決定、データへのアクセスタイプの決定に使用される仮想リソースです。ボリュームはファイルシステムのストレージ容量を消費しません。ボリュームに格納されたデータは、主にSSDストレージを消費します。ボリュームの階層化ポリシーによっては、データが容量プールのストレージを消費する場合もあります。ボリュームのサイズは作成時に設定します。あとで変更することもできます。

ボリュームには次のプロトコルを使用できます。

* CIFS：Windowsオペレーティングシステム用のファイルストレージプロトコル
* NFS：UNIXオペレーティングシステム用のファイルストレージプロトコル
* iSCSI：ブロックストレージプロトコル


.開始する前に
ボリュームを作成する前に、次の前提条件を確認してください。

* Workload FactoryにFSx for ONTAPファイルシステムが必要です。
* Storage VMが必要です。
* プロトコルアクセスの場合は、次の手順を実行します。
+
** ボリュームへのアクセスを設定するには、が必要です link:manage-links.html["リンクの関連付け"]。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*の*[リンクの関連付け]*をクリックします。リンクが関連付けられたら、この操作に戻ります。
** 選択したプロトコル（CIFS、NFS、またはiSCSI）へのアクセスを設定する必要があります。




.手順
. にログインします。 link:https://console.workloads.netapp.com/["Workload Factoryコンソール"^]
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、ボリュームを作成するファイルシステムの3つのドットメニューを選択し、* Manage *を選択します。
. [概要]*タブで、*[ボリュームの作成]*をクリックします。
. [Create volume]ページの[General details]で、次の詳細を指定します。
+
.. *ボリューム名*：ボリュームの名前を入力します。
.. * Storage VM名*：必要に応じて、Storage VM名を入力します。
.. *ボリュームスタイル*：* FlexVol *または* FlexGroup * volumeを選択します。
+
FlexVolボリュームの形式はデフォルトで選択されています。

+
FlexGroupボリュームのサイズはコンスティチュエントの数によって異なります。コンスティチュエントあたり100GiBが必要です。

.. *ボリュームサイズ*：ボリュームサイズと単位を入力します。
+
必要に応じて、ボリュームの自動拡張を有効にします。このオプションは、ボリュームアクセスタイプとして*ファイルアクセス*を選択した場合に使用できます。

.. *タグ*:オプションで、最大50個のタグを追加できます。


. [Access]（リンクが関連付けられているファイルシステムの場合のみ）で、次の詳細を指定します。
+
.. *アクセスタイプ*：*ファイルアクセス*または*ブロックアクセス*を選択します。ボリュームアクセスを設定するための追加フィールドは、選択内容によって異なります。
+
*** *ファイルアクセス*：SMB / CIFS、NFS、またはデュアル（SMB / NFS）プロトコルを使用して、許可された複数のユーザとデバイスにボリュームへのアクセスを許可します。
+
次のフィールドに値を入力して、ボリュームへのファイルアクセスを設定します。

+
.... * NFSエクスポートポリシー*：NFSアクセスを提供するには、次の詳細を指定してください：
+
..... *アクセス制御*：ドロップダウンメニューから*[カスタムエクスポートポリシー]*、*[既存のエクスポートポリシー]*、または*[ボリュームへのアクセスなし]*を選択します。
..... *エクスポートポリシー名*：
+
カスタムエクスポートポリシーを選択した場合は、ドロップダウンメニューから既存のポリシー名を選択します。

+
既存のエクスポートポリシーを選択した場合は、新しいポリシー名を入力します。

..... *エクスポートポリシールールの追加*：必要に応じて、カスタムエクスポートポリシーの場合、エクスポートポリシールールをポリシーに追加できます。


.... * CIFS共有*：SMBアクセスを提供するCIFS共有名を入力します。


*** *ブロックアクセス*：重要なビジネスアプリケーションを実行しているホストがiSCSIプロトコルを使用してボリュームにアクセスできるようにします。
+
ボリュームへのブロックアクセスを設定するには、次のフィールドに値を入力します。

+
.... * iSCSIの設定*：ボリュームへのブロックアクセス用にiSCSIを設定するには、以下の詳細を指定してください。
+
..... [新しいイニシエータグループを作成する]*または*[既存のイニシエータグループをマッピングする]*を選択します。
..... ドロップダウンメニューから*[ホストオペレーティングシステム]*を選択します。
..... 新しいイニシエータグループの*イニシエータグループ名*を入力します。
..... [Host Initiators]で、1つ以上のiSCSI Qualified Name（IQN）ホストイニシエータを追加します。








. [Efficiency and protection]で、次の詳細を指定します。
+
.. * Storage Efficiency *：Storage Efficiencyを無効または有効にします。
+
ストレージ効率化は、ONTAPの重複排除機能と圧縮機能を利用することで実現されます。重複排除は、重複するデータブロックを排除します。データ圧縮は、データブロックを圧縮して、必要な物理ストレージの量を削減します。

.. * Snapshotポリシー*：Snapshotポリシーを選択して、Snapshotの頻度と保持を指定します。
+
AWSのデフォルトポリシーは次のとおりです。カスタムのSnapshotポリシーの場合は、リンクを関連付ける必要があります。

+
`default`:: このポリシーでは、次のスケジュールでSnapshotが自動的に作成され、新しいコピー用のスペースを確保するために最も古いSnapshotコピーが削除されます。
+
--
*** 最大6つの時間単位のスナップショットが毎時5分に作成されます。
*** 最大2つの日次スナップショットが月曜日から土曜日の午前0時10分に作成されます。
*** 最大2つの週単位Snapshotが毎週日曜日の午前0時15分に作成されます。
+

NOTE: Snapshotの時間はファイルシステムのタイムゾーンに基づいており、デフォルトは協定世界時（UTC）です。タイムゾーンの変更については、NetAppのサポートドキュメントのを参照してください link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["システムのタイムゾーンの表示と設定"^] 。



--
`default-1weekly`:: このポリシーはポリシーと同様に機能し `default` ますが、週次スケジュールのSnapshotが1つだけ保持されます。
`none`:: このポリシーではスナップショットは作成されません。このポリシーをボリュームに割り当てると、自動Snapshotが作成されないようにすることができます。


.. *階層化ポリシー*：ボリュームに格納されているデータの階層化ポリシーを選択します。
+
自動は、ユーザインターフェイスを使用してボリュームを作成する場合のデフォルトの階層化ポリシーです。ボリューム階層化ポリシーの詳細については、AWS FSx for NetApp ONTAPドキュメントのを参照してください link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["ボリュームのストレージ容量"^] 。



. [Advance configuration]で、次の情報を指定します。
+
.. *ジャンクションパス*：ボリュームをマウントするStorage VMのネームスペース内の場所を入力します。デフォルトのジャンクションパスはです `/<volume-name>`。
.. *アグリゲートリスト*：FlexGroupボリュームのみ。アグリゲートを追加または削除します。アグリゲートの最小数は1です。
.. *コンスティチュエントの数*：FlexGroupボリュームの場合のみ。アグリゲートあたりのコンスティチュエントの数を入力します。コンスティチュエントあたり100GiBが必要です。


. [ 作成（ Create ） ] をクリックします。


.結果
ボリュームの作成が開始されます。作成された新しいボリュームは[Volumes]タブに表示されます。
