---
sidebar: sidebar 
permalink: create-snapshot.html 
keywords: create snapshot, snapshot 
summary: FSx for ONTAPボリュームの手動スナップショットを作成します。スナップショットは、ボリュームのコンテンツのポイントインタイムバージョンです。 
---
= FSx for ONTAPボリュームの手動スナップショットの作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
FSx for ONTAPボリュームの手動スナップショットを作成します。スナップショットは、ボリュームのコンテンツのポイントインタイムバージョンです。

Snapshotはボリュームのリソースであり、変更されたデータのためだけにスペースを消費するデータを瞬時にキャプチャします。データは時間の経過とともに変化するため、Snapshotは通常、古くなるにつれてより多くのスペースを消費します。

FSx for ONTAPボリュームではジャストインタイムのcopy-on-writeが使用されるため、Snapshot内の変更されていないファイルがボリュームの容量を消費することはありません。


NOTE: スナップショットはデータのコピーではありません。データのコピーを作成する場合は、FSx for ONTAPのバックアップ機能やボリュームレプリケーション機能の使用を検討してください。

.開始する前に
スナップショットを作成する必要があり link:manage-links.html["リンクの関連付け"] ます。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*の*[リンクの関連付け]*をクリックします。リンクが関連付けられたら、この操作に戻ります。

.手順
. Workload Factoryコンソールにログインします。
. [ストレージ]*で、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、ボリュームを含むファイルシステムの3つのドットメニューをクリックし、* Manage *を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [ボリューム]*タブで、保護するボリュームの3つのドットメニューを選択します。
. [データ保護操作]*、*[ Snapshot ]*を選択し、*[ Snapshotからのボリュームの作成]*を選択します。
. [Create volume from a snapshot]ダイアログの*[Snapshot name *]フィールドに、Snapshot名を入力します。
. [ 作成（ Create ） ] をクリックします。

