---
sidebar: sidebar 
permalink: create-backup.html 
keywords: create backup, volume backup, back up a volume 
summary: BlueXP  Workload Factoryでは、定期的なバックアップ以外で、ボリュームの手動バックアップを作成します。 
---
= BlueXP  ワークロード工場でのボリュームの手動バックアップの作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロード工場で定期的にスケジュールされたバックアップ以外で、ボリュームの手動バックアップを作成します。

.タスクの内容
FSx for ONTAPのバックアップはボリューム単位で行われるため、各バックアップには特定のボリューム内のデータのみが含まれます。

FSx for ONTAPバックアップは増分バックアップです。つまり、最新のバックアップ後に変更されたボリューム上のデータのみが保存されます。これにより、バックアップの作成に必要な時間とバックアップに必要なストレージを最小限に抑えることができ、データを複製しないことでストレージコストを削減できます。

.開始する前に
ボリュームのバックアップを作成するには、ボリュームとファイルシステムの両方に、バックアップSnapshotを格納するための十分なSSDストレージ容量が必要です。バックアップスナップショットの作成時に、スナップショットによって消費される追加のストレージ容量によって、ボリュームのSSDストレージ利用率が98%を超えることはありません。この場合、バックアップは失敗します。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、ボリュームを含むファイルシステムの3ドットメニューを選択し、* Manage *を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [ボリューム]*タブで、バックアップするボリュームの3ドットメニューを選択します。
. *データ保護アクション*、* FSx for ONTAPバックアップ*、*手動バックアップ*の順に選択します。
. [Manual backup]ダイアログで、バックアップの名前を入力します。
. [バックアップ]*を選択します。

