---
sidebar: sidebar 
permalink: create-snapshot.html 
keywords: create snapshot, snapshot 
summary: BlueXP  ワークロード工場でFSx for ONTAPボリュームの手動スナップショットを作成スナップショットは、ボリュームのコンテンツのポイントインタイムバージョンです。 
---
= FSx for ONTAPボリュームの手動スナップショットの作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロード工場でFSx for ONTAPボリュームの手動スナップショットを作成スナップショットは、ボリュームのコンテンツのポイントインタイムバージョンです。

Snapshotはボリュームのリソースであり、変更されたデータのためだけにスペースを消費するデータを瞬時にキャプチャします。データは時間の経過とともに変化するため、Snapshotは通常、古くなるにつれてより多くのスペースを消費します。

FSx for ONTAPボリュームではジャストインタイムのcopy-on-writeが使用されるため、Snapshot内の変更されていないファイルがボリュームの容量を消費することはありません。


NOTE: スナップショットはデータのコピーではありません。データのコピーを作成する場合は、FSx for ONTAPのバックアップ機能やボリュームレプリケーション機能の使用を検討してください。

.開始する前に
スナップショットを作成する必要があり link:manage-links.html["リンクの関連付け"] ます。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*で*[リンクの関連付け]*を選択します。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]*で、*[ストレージインベントリに移動]*を選択します。
. [FSx for ONTAP *]タブで、Snapshotを作成するボリュームが含まれているファイルシステムの3ドットメニューを選択し、*[管理]*を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [ボリューム]*タブで、Snapshotで保護するボリュームの3ドットメニューを選択します。
. [データ保護操作]*、*[スナップショット]*を選択し、*[スナップショットの作成]*を選択します。
. [Create a snapshot]ダイアログで、*[Snapshot name]*フィールドにSnapshot名を入力します。
. オプション：Snapshotを変更不可にして、保持期間中にSnapshotが削除されないようにします。
+
.. [変更不可のSnapshot ]*を有効にします。
.. [Retention Period]*に、時間、日、月、または年数を設定します。
.. 変更不可のスナップショットに関するステートメントを受け入れます。


. 「 * Create * 」を選択します。


.結果
ボリュームにSnapshotコピーがあります。
