---
sidebar: sidebar 
permalink: create-snapshot-policy.html 
keywords: create 
summary: BlueXP  ワークロード工場でStorage VM用のカスタムSnapshotポリシーを作成 
---
= BlueXP  ワークロード工場でのStorage VMのSnapshotポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロード工場でStorage VM用のカスタムSnapshotポリシーを作成Snapshotポリシーは、Storage VMのSnapshotの作成方法を定義します。FSx for ONTAPファイルシステムでは、Storage VMのSnapshotポリシーを作成できます。また、複数のStorage VMでポリシーを共有することもできます。

.タスクの内容
FSx for ONTAPに組み込まれている3つのスナップショットポリシーとは異なるカスタムスナップショットポリシーを作成できます。

* `default`
* `default-1weekly`
* `none`


デフォルトでは、すべてのボリュームがファイルシステムのSnapshotポリシーに関連付けられ `default` ています。ほとんどのワークロードでこのポリシーを使用することを推奨します。

ポリシーをカスタマイズすると、スナップショットを作成するタイミング、保持するコピーの数、およびスナップショットに名前を付ける方法を指定できます。

.開始する前に
* Snapshotポリシーを作成したあとでStorage VMとの関連付けを変更することはできませんが、ポリシーはボリュームに対して追加または削除できます。
* Snapshotを使用する前に、Snapshotの容量について次の点を考慮してください。
+
** ほとんどのデータセットでは、20%の容量を追加すれば、Snapshotを最大4週間保持できます。データが古くなるにつれて、リストアに使用される可能性は低くなります。
** Snapshot内のすべてのデータを上書きすると、ボリューム容量が大量に消費されます。これは、ボリューム容量のプロビジョニングに影響します。


* カスタム スナップショット ポリシーを作成するには、リンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]*で、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、ボリュームを含むファイルシステムの3ドットメニューを選択し、* Manage *を選択します。
. ファイルシステムの概要で、*[Storage VMs]*タブを選択します。
. [Storage VMs]タブで、スケジュールされたSnapshotで保護するボリュームの3ドットメニューを選択し、*[詳細な操作]*、*[ Snapshotポリシーの管理]*の順に選択します。
. Snapshotポリシーの管理ページで、* Snapshotポリシーの作成*を選択します。
. Snapshotポリシー名*フィールドに、Snapshotポリシーの名前を入力します。
. 必要に応じて、Snapshotポリシーの説明を入力します。
. [ポリシーのスケジュールとコピー]*で、Snapshotを作成するタイミングを選択します。たとえば、毎分、毎時などです。
+
複数の周波数を選択できます。

. [コピー数]*で、保持するコピー数を入力します。
+
コピーの最大数は1、023です。

. オプション：[命名規則]*で、ポリシーの*プレフィックス*を入力します。
. *保持ラベル*は自動的に入力されます。
+
このラベルは、ソースファイルシステムからターゲットファイルシステムへのレプリケーション用に指定されたSnapshotのみを選択するために使用されるSnapMirror（レプリケーションラベル）を示します。

. オプション：必要なスケジュールについて*変更不可のスナップショット*を有効にするには、スケジュールごとに*保持期間*を設定し、このステートメントを受け入れて続行します。
+
変更不可のSnapshotを有効にすると、このSnapshotポリシー内のすべてのSnapshotがロックされ、保持期間中にSnapshotが削除されないようになります。

. * Storage VM間で共有*：デフォルトで有効になっています。有効にすると、Snapshotポリシーがファイルシステム内のすべてのStorage VMで共有されます。単一のStorage VMのSnapshotポリシーを作成する場合は無効にしてください。
. 「 * Create * 」を選択します。


.結果
Snapshotポリシーが作成されます。
