---
sidebar: sidebar 
permalink: create-storage-vm.html 
keywords: create storage VM, create svm 
summary: 'FSx for ONTAPストレージ VM (SVM) を作成して、 NetApp Workload Factory のワークロードにストレージおよびデータ サービスを提供できます。' 
---
= FSx for ONTAPファイルシステム用Storage VMの作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
FSx for ONTAPファイル システム用のストレージ VM (SVM) を作成し、 NetApp Workload Factory のワークロードのストレージおよびデータ サービスに仮想的にアクセスします。

.タスクの内容
ストレージ VM は、ワークロード ファクトリー ストレージ内の各ワークロードのデータにアクセスするために使用できる分離されたファイル サーバーです。各 SVM には、データの管理とアクセスを行うための独自の管理資格情報とエンドポイントがあります。

SVMを使用している場合、FSx for ONTAPのデータにアクセスすると、SVMのエンドポイント（IPアドレス）を使用して、SVMによってホストされているボリューム、CIFS / SMB共有、またはiSCSI LUNがクライアントやワークステーションにマウントされます。

.開始する前に
ファイルシステムあたりのサポートされるStorage VM数を確認します。ファイルシステムあたりのSVMの最大数については、AWSのドキュメントのを参照してください link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["FSx for ONTAP Storage Virtual Machineの管理"^] 。



== Storage VM を作成

Workload Factory コンソールからストレージ VM を作成できます。 Codebox で利用可能な REST API、CloudFormation、Terraform などのツールも使用できます。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Codeboxを使用して自動化する方法"^] 。


NOTE: CodeboxからTerraformを使用すると、コピーまたはダウンロードしたコードが非表示になり、パスワードが表示され `fsxadmin` `vsadmin` ます。コードを実行するときは、パスワードを再入力する必要があります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ストレージ タイルで、[ストレージへ移動] を選択します。
. [ストレージ] メニューから、*FSx for ONTAP* を選択します。
. *FSx for ONTAP*から、ファイルシステムのアクションメニューを選択し、*管理*を選択します。
. ストレージ VM のファイル システムの概要で、*ストレージ VM の作成*を選択します。
. [ストレージ VM の作成] ページの [ストレージ VM 構成] で、次の情報を入力します。
+
.. *名前*：Storage VMの名前を入力します。
.. * Storage VMクレデンシャル*：このStorage VMのユーザのパスワードを指定する `vsadmin` か、ファイルシステムのユーザクレデンシャルを使用して `fsxadmin` ください。
.. *ルートボリュームのセキュリティ形式*：データにアクセスするクライアントのタイプ（UNIX（Linuxクライアント）、NTFS（Windowsクライアント）、Mixed）に応じて、ルートボリュームのセキュリティ形式を選択します。
.. *タグ*:オプションで、最大50個のタグを追加できます。


. 「 * Create * 」を選択します。

