---
sidebar: sidebar 
permalink: create-replication.html 
keywords: replication, replicate 
summary: 予期しない災害が発生した場合のデータ損失を回避するために、FSx for ONTAPファイルシステムのレプリケーション関係を作成します。 
---
= BlueXP  ワークロードファクトリでレプリケーション関係を作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
予期しない災害が発生した場合のデータ損失を回避するために、BlueXP  ワークロード工場でFSx for ONTAPファイルシステムのレプリケーション関係を作成します。

.タスクの内容
レプリケーションはデータ保護の追加レイヤであり、データが格納されているリージョンで災害が発生した場合に不可欠です。リージョン間レプリケーションを使用する場合は、データ損失を回避できます。

この処理では、FSx for ONTAPファイルシステム内の1つまたはすべてのソースボリュームに対してレプリケーション関係を作成します。

ターゲットファイルシステム内のレプリケートされたボリュームは、データ保護（DP）ボリュームであり、命名形式はです。 `{OriginalVolumeName}_copy`

.開始する前に
作業を開始する前に、次の前提条件を満たしていることを確認してください。

* レプリケーション関係を作成するには、ストレージインベントリに2つの使用可能なファイルシステムが必要です。
* レプリケーション関係に使用する2つのファイルシステムには、リンクが関連付けられている必要があります。ファイルシステムに既存のリンクがない場合は、 link:create-link.html["最初にリンクを作成します"]を参照してください。ファイルシステムでlink:manage-links.html["リンクの関連付け"]、*[アカウント名]*の*[リンクの関連付け]*を選択します。リンクが両方のファイルシステムに関連付けられたら、この操作に戻ります。


単一のボリュームをレプリケートするか、ファイルシステム内のすべてのボリュームをレプリケートするには、次の手順を実行します。

[role="tabbed-block"]
====
.単一のボリュームをレプリケート
--
1つのソース（読み取り/書き込み）ボリュームまたは1つのデータ保護（DP）ボリュームをレプリケートできます。DPボリュームの2つ目のレプリカは作成できません。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、レプリケートするボリュームを含むファイルシステムの3ドットメニューを選択し、*ボリュームデータのレプリケート*を選択します。
. [Replicate data]ページの[Replication target]で、次の情報を指定します。
+
.. * FSx for ONTAPファイルシステム*：対象となるFSx for ONTAPファイルシステムのクレデンシャル、リージョン、FSx for ONTAPファイルシステム名を選択します。
.. * Storage VM名*：ドロップダウンメニューからStorage VMを選択します。
.. *ボリューム名*：ターゲットボリューム名は次の形式で自動的に生成されます `{OriginalVolumeName}_copy`。自動生成されたボリューム名を使用するか、別のボリューム名を入力できます。
.. *ユースケース*：レプリケーションのユースケースとして、次のいずれかを選択します。選択したユースケースに応じて、ワークロードファクトリはベストプラクティスに従って推奨値をフォームに入力します。推奨値をそのまま使用することも、フォームに入力する際に変更を加えることもできます。
+
*** 移行：ターゲットのFSx for ONTAPファイルシステムにデータを転送
*** ホットディザスタリカバリ：重要なワークロードの高可用性と迅速なディザスタリカバリを実現
*** コールド/アーカイブのディザスタリカバリ：
+
**** コールドディザスタリカバリ：目標復旧時間（RTO）とオブジェクト復旧時点（RPO）を長くしてコストを削減
**** アーカイブ：長期的なストレージとコンプライアンスのためにデータをレプリケート


*** その他


.. *階層化ポリシー*：ターゲットボリュームに格納されているデータの階層化ポリシーを選択します。階層化ポリシーは、選択したユースケースに応じた推奨される階層化ポリシーにデフォルトで設定されます。
+
_Balanced（Auto）_は、ワークロード工場出荷時のコンソールを使用してボリュームを作成する際のデフォルトの階層化ポリシーです。ボリューム階層化ポリシーの詳細については、AWS FSx for NetApp ONTAPドキュメントのを参照してください link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["ボリュームのストレージ容量"^] 。ワークロードファクトリでは、階層化ポリシーにワークロードファクトリコンソールのユースケースベースの名前が使用され、かっこ内にFSx for ONTAP階層化ポリシー名が含まれていることに注意してください。

+
移行のユースケースを選択した場合は、ソースボリュームの階層化ポリシーをターゲットボリュームにコピーすることがワークロード出荷時に自動的に選択されます。階層化ポリシーをコピーするかどうかを選択解除し、レプリケーション対象として選択したボリュームに適用する階層化ポリシーを選択できます。

.. *最大転送速度*：* Limited *を選択し、最大転送速度をMB/秒単位で入力します。または、*無制限*を選択します。
+
制限がないと、ネットワークとアプリケーションのパフォーマンスが低下する可能性があります。また、FSx for ONTAPファイルシステムは、主にディザスタリカバリに使用されるワークロードなど、重要なワークロードには無制限の転送速度を推奨します。



. [Replication settings]で、次の情報を指定します。
+
.. *レプリケーション間隔*：ソースボリュームからターゲットボリュームにSnapshotを転送する頻度を選択します。
.. *長期保存*：オプションで、長期保存用のスナップショットを有効にします。
+
長期保持を有効にする場合は、既存のポリシーを選択するか、新しいポリシーを作成して、レプリケートするSnapshotと保持する数を定義します。

+
*** *既存のポリシーを選択*：ドロップダウンメニューから既存のポリシーを選択します。
*** *新しいポリシーを作成*：次の情報を入力します。
+
**** *ポリシー名*：ポリシー名を入力します。
**** オプション：変更不可のSnapshotを有効にします。
+
***** このポリシーで作成されたSnapshotが保持期間中に削除されないようにするには、[変更不可のSnapshotを有効にする]*を選択します。
***** [Retention Period]*を時間、日、月、または年数で設定します。


**** * Snapshotポリシー*：表で、Snapshotポリシーの頻度と保持するコピーの数を選択します。Snapshotポリシーは複数選択できます。






. 「 * Create * 」を選択します。


--
.ファイルシステム内のすべてのボリュームをレプリケート
--
ファイルシステム内のすべてのソース（読み取り/書き込み）ボリュームとデータ保護（DP）ボリュームをレプリケートできます。


NOTE: データ保護ボリュームのレプリケートは1回だけサポートされます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. [FSx for ONTAP ]タブで、ボリュームを含むファイルシステムの3ドットメニューを選択し、*[管理]*を選択します。
. ファイルシステムの概要で、*[データのレプリケート]*を選択します。
. [Replicate data]ページの[Replication target]で、次の情報を指定します。
+
.. * FSx for ONTAPファイルシステム*：対象となるFSx for ONTAPファイルシステムのクレデンシャル、リージョン、FSx for ONTAPファイルシステム名を選択します。
.. * Storage VM名*：ドロップダウンメニューからStorage VMを選択します。
.. *ボリューム名*：ターゲットボリューム名は次の形式で自動的に生成されます `{OriginalVolumeName}_copy`。
.. *ユースケース*：レプリケーションのユースケースとして、次のいずれかを選択します。選択したユースケースに応じて、ワークロードファクトリはベストプラクティスに従って推奨値をフォームに入力します。推奨値をそのまま使用することも、フォームに入力する際に変更を加えることもできます。
+
*** 移行：ターゲットのFSx for ONTAPファイルシステムにデータを転送
*** ホットディザスタリカバリ：重要なワークロードの高可用性と迅速なディザスタリカバリを実現
*** コールド/アーカイブのディザスタリカバリ：
+
**** コールドディザスタリカバリ：目標復旧時間（RTO）とオブジェクト復旧時点（RPO）を長くしてコストを削減
**** アーカイブ：長期的なストレージとコンプライアンスのためにデータをレプリケート


*** その他


.. *階層化ポリシー*：ターゲットボリュームに格納されているデータの階層化ポリシーを選択します。階層化ポリシーは、選択したユースケースに応じた推奨される階層化ポリシーにデフォルトで設定されます。
+
_Balanced（Auto）_は、ワークロード工場出荷時のコンソールを使用してボリュームを作成する際のデフォルトの階層化ポリシーです。ボリューム階層化ポリシーの詳細については、AWS FSx for NetApp ONTAPドキュメントのを参照してください link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["ボリュームのストレージ容量"^] 。ワークロードファクトリでは、階層化ポリシーにワークロードファクトリコンソールのユースケースベースの名前が使用され、かっこ内にFSx for ONTAP階層化ポリシー名が含まれていることに注意してください。

+
移行のユースケースを選択した場合は、ソースボリュームの階層化ポリシーをファイルシステム内のターゲットボリュームにコピーすることがワークロード工場で自動的に選択されます。階層化ポリシーをコピーするかどうかを選択解除し、レプリケーション対象のターゲットファイルシステム内のボリュームに適用する階層化ポリシーを選択できます。

.. *最大転送速度*：* Limited *を選択し、最大転送速度をMiB/秒で入力します。または、*無制限*を選択します。
+
制限がないと、ネットワークとアプリケーションのパフォーマンスが低下する可能性があります。また、FSx for ONTAPファイルシステムは、主にディザスタリカバリに使用されるワークロードなど、重要なワークロードには無制限の転送速度を推奨します。



. [Replication settings]で、次の情報を指定します。
+
.. *レプリケーション間隔*：ソースボリュームからターゲットボリュームにSnapshotを転送する頻度を選択します。
.. *長期保存*：オプションで、長期保存用のスナップショットを有効にします。
+
長期保持を有効にする場合は、既存のポリシーを選択するか、新しいポリシーを作成して、レプリケートするSnapshotと保持する数を定義します。

+
*** *既存のポリシーを選択*：ドロップダウンメニューから既存のポリシーを選択します。
*** *新しいポリシーを作成*：次の情報を入力します。
+
**** *ポリシー名*：ポリシー名を入力します。
**** * Snapshotポリシー*：表で、Snapshotポリシーの頻度と保持するコピーの数を選択します。Snapshotポリシーは複数選択できます。






. [Replicate]*を選択します。


--
====
.結果
レプリケーション関係は、ターゲットのFSx for ONTAPファイルシステムの*レプリケーション関係*タブに表示されます。
