---
sidebar: sidebar 
permalink: edit-volume-autogrow.html 
keywords: volume autogrow, increase volume capacity, enable autogrow 
summary: ボリュームの自動拡張を有効にすると、ワークロード ファクトリーがボリューム容量を管理できるようになります。いつでも無効にすることができます。 
---
= ワークロードファクトリーでボリュームの自動拡張を有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ボリュームの自動拡張を有効にすると、ワークロード ファクトリーがボリューム容量を管理できるようになります。いつでも無効にすることができます。

必要に応じて、を使用していつでもボリュームのボリューム容量を手動で拡張できます link:increase-volume-capacity.html["ボリューム容量の拡張機能"]。


NOTE: ボリュームの自動拡張はiSCSIボリュームではサポートされません。

.開始する前に
ボリュームの自動拡張を有効にするには、が必要です link:manage-links.html["リンクの関連付け"]。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*で*[リンクの関連付け]*を選択します。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. [FSx for ONTAP ]タブで、更新するボリュームを含むファイルシステムの3ドットメニューを選択し、*[管理]*を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [Volumes]タブで、変更するボリュームの3ドットのメニューを選択します。
. *基本アクション*を選択し、*ボリュームの自動拡張を設定*を選択します。
. 「自動拡張の設定」ダイアログでボリュームの自動拡張を有効にすると、ボリュームが最大サイズに達するまでボリューム容量が自動的に拡張されます。この機能は、データ使用量の増加に対応し、中断のない運用を実現します。
+
ボリュームの最大拡張サイズと単位を指定します。最大拡張サイズは現在のボリュームサイズより小さくすることはできません。

. * 適用 * を選択します。

