---
sidebar: sidebar 
permalink: enable-auto-capacity-management.html 
keywords: auto capacity, automatic capacity management, file system capacity 
summary: この機能を有効にすると、容量のニーズの変化に合わせて、容量の追加がワークロード工場で自動的にFSx for ONTAPファイルシステムに追加されます。 
---
= FSx for ONTAPファイルシステムの容量の自動管理を有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
この機能を有効にすると、容量のニーズの変化に応じて、BlueXP  ワークロード工場がFSx for ONTAPファイルシステムに自動的にストレージを追加できるようになります。

.タスクの内容
FSx for ONTAPファイルシステムのスキャンは30分ごとに実行され、増分ストレージを追加する必要があるかどうか、使用可能なボリュームinode、またはボリューム内のファイルやフォルダの最大数を確認します。これにより、設定された容量の自動管理のしきい値に従って数が増加します。

この機能を管理できるアカウントは1つだけです。

すべてのFSx for ONTAPファイルシステムでSSDストレージの最大容量は524、288GiBです。クォータの引き上げをリクエストするには、AWS FSx for NetApp ONTAPのドキュメントを参照して link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["クォータ"^] ください。

.開始する前に
このタスクを完了するには、ワークロードファクトリで_automate_permissionsを持つクレデンシャルが必要です。

ボリュームのinodeをストレージ容量に合わせて拡張するには、を実行する必要がありますlink:manage-links.html["リンクの関連付け"]。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*で*[リンクの関連付け]*を選択します。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]で、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、の容量の自動管理を有効にするファイルシステムの3ドットメニューを選択します。
. 「 * Manage * 」を選択します。
. [Information]で、*[Automatic capacity management]*の横にある鉛筆アイコンを選択します。[Automatic capacity management]行の上にマウスを置くと、ドロップダウン矢印の横に鉛筆のアイコンが表示されます。
. [Automatic capacity management]ダイアログで、次の情報を指定します。
+
.. *クレデンシャル*：ドロップダウンメニューから、_automate_permissionsを指定してクレデンシャルを選択します。
.. [有効化]ボタンを選択して*[自動容量管理を有効にする]*を選択します。
+
または、この機能を無効にします。ファイルシステムの容量を増やす必要がある場合は、先に容量の自動管理を無効にする必要があります。

.. *容量のしきい値*：FSx for ONTAPファイルシステムの最大サイズを入力します。
.. * Capacity Increments *：容量を段階的に拡張する割合を入力します。


. * 適用 * を選択します。


.結果
ファイルシステムスキャンは30分ごとに実行され、ファイルシステムに追加の容量が必要かどうかが判断されます。
