---
sidebar: sidebar 
permalink: enable-auto-capacity-management.html 
keywords: auto capacity, automatic capacity management, file system capacity 
summary: この機能を有効にすると、容量のニーズの変化に合わせて、容量の追加がワークロード工場で自動的にFSx for ONTAPファイルシステムに追加されます。 
---
= FSx for ONTAPファイルシステムの容量の自動管理を有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
自動容量管理を有効にすると、BlueXPワークロードファクトリーは、時間の経過とともに容量ニーズが変化するのに合わせて、FSx for ONTAPファイルシステムに自動的に増分ストレージを追加します。さらに、この機能を有効にすると、手動で容量を監視する必要がなくなり、アプリケーションデータの読み取りと書き込みによる影響のリスクを軽減できます。

.タスクの内容
FSx for ONTAPファイルシステムのスキャンは30分ごとに実行され、増分ストレージを追加する必要があるかどうか、使用可能なボリュームinode、またはボリューム内のファイルやフォルダの最大数を確認します。これにより、設定された容量の自動管理のしきい値に従って数が増加します。

この機能を管理できるアカウントは1つだけです。

すべてのFSx for ONTAPファイルシステムでSSDストレージの最大容量は524、288GiBです。クォータの引き上げをリクエストするには、AWS FSx for NetApp ONTAPのドキュメントを参照して link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["クォータ"^] ください。

.開始する前に
開始する前に、次の点を考慮してください。

* このタスクを完了するには、ワークロード ファクトリーでの _read/write_ 権限を持つ資格情報が必要です。
* ボリュームのinodeをストレージ容量に合わせて拡張するには、を実行する必要がありますlink:manage-links.html["リンクの関連付け"]。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*で*[リンクの関連付け]*を選択します。リンクが関連付けられたら、この操作に戻ります。
* AWSではSSD容量の増設ごとに最低6時間のクールダウン期間を設けているため、データ移行中はこの機能を有効にしないでください。この制限により調整が遅れる可能性があるため、計画にご注意ください。


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]で、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、の容量の自動管理を有効にするファイルシステムの3ドットメニューを選択します。
. 「 * Manage * 」を選択します。
. [Information]で、*[Automatic capacity management]*の横にある鉛筆アイコンを選択します。[Automatic capacity management]行の上にマウスを置くと、ドロップダウン矢印の横に鉛筆のアイコンが表示されます。
. [Automatic capacity management]ダイアログで、次の情報を指定します。
+
.. *クレデンシャル*：ドロップダウンメニューから、_automate_permissionsを指定してクレデンシャルを選択します。
.. [有効化]ボタンを選択して*[自動容量管理を有効にする]*を選択します。
+
または、この機能を無効にします。ファイルシステムの容量を増やす必要がある場合は、先に容量の自動管理を無効にする必要があります。

.. *しきい値の増加*：FSx for ONTAPファイルシステムの最大サイズを入力します。
.. * Incremental Increase *：容量を段階的に増やす割合を入力します。
.. オプション：inodeの自動管理を有効にして、inode（ファイル）の数を上限まで増やしてボリュームあたりのファイル容量をスケールアップします。


. * 適用 * を選択します。


.結果
ファイルシステムスキャンは30分ごとに実行され、ファイルシステムに追加の容量が必要かどうかが判断されます。
