---
sidebar: sidebar 
permalink: explore-savings.html 
keywords: cost, savings, compare costs, EBS, EFS, FSx for Windows file servers FSx for ONTAP 
summary: Amazon Elastic Block Store（EBS）ストレージ、Elastic File System（EFS）、FSx for Windowsファイルサーバでのストレージワークロードの削減効果を、AWS FSx for NetApp ONTAPと比較してご確認ください。 
---
= BlueXP  ワークロード工場でのFSx for ONTAPによるコスト削減についてご確認ください
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Amazon Elastic Block Store（EBS）、Elastic File System（EFS）、FSx for Windowsファイルサーバを使用し、FSx for NetApp ONTAPを使用するストレージワークロードの削減効果をご確認ください。

Workload Factoryにはストレージ削減試算ツールが組み込まれているので、Amazonのストレージ環境をFSx for ONTAPと比較できます。AWSクレデンシャルを指定するかどうかに関係なく、削減効果を確認したり、ストレージ環境の構成設定をカスタマイズしたりできます。AWSクレデンシャルを指定すると、たとえばAmazon Elastic Block Storeのインスタンスを1つ以上選択し、ワークロードファクトリで自動的に比較を行うことができます。この計算ツールは、手動か自動かにかかわらず、ストレージニーズに対してコストが最も低いストレージサービスを特定します。

最も対費用効果の高いストレージがFSx for ONTAPであるとストレージ計算ツールが判断した場合は、FSx for ONTAP構成を作成または保存し、ワークロードファクトリに付与した権限に関係なく、Codeboxを使用してInfrastructure as Codeテンプレートを生成できます。



== 電卓オプション

お客様のシステムとFSx for ONTAPのコストを比較するために、Amazonストレージ環境のカスタマイズと自動検出という2つの計算ツールオプションが用意されています。

カスタマイズによる削減効果の詳細：ストレージ環境の構成設定（ユースケース、リージョン、ボリュームまたはファイルシステムの数、ストレージ容量、Snapshotの頻度、Snapshotあたりの変更量、プロビジョニングされたIOPS、スループットなど）を指定できます。

検出されたストレージ環境の削減効果を確認：ワークロードファクトリは既存のAWSストレージ環境にリンクし、詳細を計算ツールに入力して自動で比較します。自動モードを使用するには、自動化権限を付与する必要があります。ユースケースは変更できますが、その他の詳細はすべて計算で自動的に決定されます。

さらに、計算機分析の精度を向上させることができますlink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWSクレデンシャルを追加"^]。[既存のリソースに基づいてコスト削減を計算する]*を選択します。[クレデンシャルの追加]ページにリダイレクトされます。クレデンシャルを追加したら、FSx for ONTAPと比較する既存のリソースを選択し、*[削減効果を確認する]*を選択します。



== カスタマイズによるコスト削減の詳細

タブに表示されるストレージの選択手順に従います。

[role="tabbed-block"]
====
.Amazon Elastic Block Store（EBS）
--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Explore savings]*を選択し、*[Amazon Elastic Block Store（EBS）]*を選択します。
. Storage Savings Calculatorで、次の詳細を入力します。
+
.. *ユースケース*：必須。ドロップダウンメニューからユースケースを選択します。選択したユースケースに基づいて、FSx for ONTAPファイルシステムの特性を比較します。
.. *リージョン*：オプション。ドロップダウンメニューからEBS設定のリージョンを選択します。
.. * EBSボリュームタイプを選択*：オプション。構成に使用するEBSボリュームタイプを選択します。
.. *ボリューム数*：オプション。EBS構成内のボリューム数を入力します。
.. *ボリュームあたりのストレージ容量（TiB）*：オプション。ボリュームあたりのストレージ容量をTiB単位で入力します。
.. * Snapshotの頻度*：オプション。EBS構成のスナップショット頻度を選択します。
.. * Snapshotあたりの変更量（GiB）*：オプション。Snapshotストレージの場合のみ。Snapshotあたりの変更量をGiB単位で入力します。
.. *ボリュームあたりのプロビジョニングIOPS *：オプション。gp3、io1、およびio2ボリュームの場合。ボリュームあたりのプロビジョニングIOPSを入力します。
.. *スループット（MiB/秒）*：オプション。gp3ボリュームの場合のみ。ボリュームあたりのスループット（MiB/秒）を入力します。




--
.Amazon FSx for Windowsファイルサーバ
--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ストレージで、*コスト削減の詳細*を選択し、* Amazon FSx for Windows File Server *を選択します。
. Storage Savings Calculatorで、次の詳細を入力します。
+
.. *ユースケース*：必須。ドロップダウンメニューからユースケースを選択します。選択したユースケースに基づいて、FSx for ONTAPファイルシステムの特性を比較します。
.. *リージョン*：オプション。FSx for Windowsファイルサーバ構成のリージョンをドロップダウンメニューから選択します。
.. *導入タイプ*：オプション。[単一のアベイラビリティゾーン]*または*[複数のアベイラビリティゾーン]*を選択します。
.. *ストレージタイプ*：SSDストレージタイプがデフォルトで選択されています。
.. *ストレージ容量（TiB）*：オプション。構成のストレージ容量を入力します。
.. *重複排除による削減量（%）*：オプション。重複排除によって削減できる容量の割合を入力します。
.. * Snapshotの頻度*：オプション。構成に応じたスナップショットの頻度を選択します。
.. * Snapshotあたりの変更量（GiB）*：オプション。Snapshotストレージの場合のみ。Snapshotあたりの変更量をGiB単位で入力します。
.. *プロビジョニングされたSSD IOPS *：オプション。[Provisioned SSD IOPS]を入力します。
.. *スループット（MiB/秒）*：オプション。スループットをMiB/秒単位で入力します。




--
.Amazon Elastic File System（EFS）
--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、[Explore savings]*、[Amazon Elastic File System（EFS）]*の順に選択します。
. Storage Savings Calculatorで、次の詳細を入力します。
+
.. *ユースケース*：必須。ドロップダウンメニューからユースケースを選択します。選択したユースケースに基づいて、FSx for ONTAPファイルシステムの特性を比較します。
.. *リージョン*：オプション。FSx for Windowsファイルサーバ構成のリージョンをドロップダウンメニューから選択します。
.. *ファイルシステムタイプ*：オプション。地域*または* 1ゾーン*を選択します。
.. *ストレージ容量（TiB）*：オプション。EFS構成のストレージ容量を入力します。
.. *アクセス頻度の高いデータ（%）*：オプション。アクセス頻度の高いデータの割合を入力します。
.. *スループットモード*：オプション。[プロビジョニングされたスループット]*または*[弾性スループット]*を選択します。
.. *スループット（MiB/秒）*：オプション。スループットをMiB/秒単位で入力します。




--
====
ストレージシステム構成の詳細を指定したら、ページに表示される計算方法と推奨事項を確認します。

さらに、次のいずれかを選択して、ページの一番下までスクロールしてレポートを表示します。

* * PDFのエクスポート*
* *電子メールで送信*
* *計算結果を表示*


FSx for ONTAPに切り替えるには、の手順に従います <<FSx for ONTAPファイルシステムの導入,FSx for ONTAPファイルシステムの導入>>。



== 検出されたストレージ環境の削減効果を確認する

.開始する前に
ワークロードファクトリでAWSアカウント内のAmazon Elastic Block Store（EBS）、Elastic File System（EFS）、FSx for Windows File Serverのストレージ環境を検出する場合は、link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["権限の付与"^]AWSアカウントに登録してください。


NOTE: この計算ツールオプションでは、EBSスナップショットとFSx for Windows File Serverシャドウコピーの計算はサポートされていません。カスタマイズによるコスト削減を検討する場合は、EBSとFSx for Windows File Serverスナップショットの詳細を提供できます。

タブに表示されるストレージの選択手順に従います。

[role="tabbed-block"]
====
.Amazon Elastic Block Store（EBS）
--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. ストレージインベントリで、*[削減効果の確認]*タブを選択します。
. [Elastic Block Store（EBS）]*タブで、FSx for ONTAPと比較するインスタンスを選択し、*[Explore savings]*を選択します。
. Storage Savings Calculatorが表示されます。選択したインスタンスに基づいて、ストレージシステムの次の特性が事前に入力されています。
+
.. *ユースケース*：構成のユースケース。必要に応じてユースケースを変更できます。
.. *選択したボリューム*：EBS構成内のボリュームの数
.. *合計ストレージ容量（TiB）*：ボリュームあたりのストレージ容量（TiB）
.. *合計プロビジョニングIOPS *：gp3、io1、およびio2のボリューム
.. *合計スループット（MiB/秒）*：gp3ボリュームのみ




--
.Amazon FSx for Windowsファイルサーバ
--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. ストレージインベントリで、*[削減効果の確認]*タブを選択します。
. [Amazon FSx for Windows File Server*]タブで、FSx for ONTAPと比較するインスタンスを選択し、*[Explore savings]*を選択します。
. Storage Savings Calculatorが表示されます。選択したインスタンスの導入タイプに基づいて、ストレージシステムの次の特性があらかじめ設定されています。
+
.. *ユースケース*：構成のユースケース。必要に応じてユースケースを変更できます。
.. *選択したファイルシステム
.. *合計ストレージ容量（TiB）*
.. *プロビジョニングされたSSD IOPS *
.. *スループット（MiB/秒）*




--
.Amazon Elastic File System（EFS）
--
.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. ストレージインベントリで、*[削減効果の確認]*タブを選択します。
. [Elastic File System（EFS）]タブで、FSx for ONTAPと比較するインスタンスを選択し、*[Explore savings（削減効果を確認）]*を選択します。
. Storage Savings Calculatorが表示されます。選択したインスタンスに基づいて、ストレージシステムの次の特性が事前に入力されています。
+
.. *ユースケース*：構成のユースケース。必要に応じてユースケースを変更できます。
.. *ファイル・システムの総数*
.. *合計ストレージ容量（TiB）*
.. *合計プロビジョニングスループット（MiB/秒）*
.. *弾性スループットの合計-読み取り（GiB）*
.. *合計柔軟性に優れたスループット–書き込み（GiB）*




--
====
ストレージシステム構成の詳細を指定したら、ページに表示される計算方法と推奨事項を確認します。

さらに、次のいずれかを選択して、ページの一番下までスクロールしてレポートを表示します。

* * PDFのエクスポート*
* *電子メールで送信*
* *計算結果を表示*




== FSx for ONTAPファイルシステムの導入

コスト削減を実現するためにFSx for ONTAPに切り替えたい場合は、FSx for ONTAPファイルシステムの作成ウィザードからファイルシステムを直接作成する場合は*作成*を選択し、推奨構成を後で保存する場合は*保存*を選択します。

導入方法:: _automate_modeでは、FSx for ONTAPファイルシステムをワークロード工場から直接導入できます。Codeboxウィンドウからコンテンツをコピーし、Codeboxメソッドのいずれかを使用してシステムを展開することもできます。
+
--
_basic_modeでは、Codeboxウィンドウからコンテンツをコピーし、いずれかのCodeboxメソッドを使用してFSx for ONTAPファイルシステムを導入できます。

--

