---
sidebar: sidebar 
permalink: improve-configurations.html 
keywords: implement best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: BlueXP  Workload Factory for Databasesは、Microsoft SQL Serverの構成をスキャンし、優れた運用性の実現に役立つ分析情報と推奨事項を提供します。 
---
= 適切に設計されたファイルシステム構成の実装
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
構成分析の洞察と推奨事項を活用し、ワークロードファクトリーを活用して、FSx for ONTAPファイルシステムにベストプラクティスを実装できます。Well-Architected ステータスを簡単に確認し、構成上の問題点を把握し、信頼性、セキュリティ、効率性、パフォーマンス、コストが最適化されていないシステムのアーキテクチャを改善するための対策を講じることができます。

link:configuration-analysis.html["ワークロード ファクトリーの構成分析と Well-Architected ステータスについて学習します。"]

.タスクの内容
ワークロードファクトリーは、Amazon FSx for NetApp ONTAPファイルシステムのデプロイメント構成を毎日分析します。この毎日の分析では、Well-Architected ステータス、インサイト、推奨事項に加え、ファイルシステムがベストプラクティスに準拠するように構成の問題を自動的に修正するためのオプションが提供されます。

ワークロード ファクトリー コンソール内のストレージ インベントリから、ファイル システムの構成の問題に関する推奨事項を確認し、問題を修正するオプションがあります。

分析対象:: Workload Factoryは、FSx for ONTAPファイルシステムの次の構成について、適切に設計されたステータスを分析します。
+
--
* SSD容量しきい値
* データの階層化
* スケジュールされたローカルSnapshot
* FSx for ONTAP バックアップ
* リモートデータレプリケーション
* ストレージの効率化
* 自動容量管理


--


.開始する前に
* _読み取り専用_または_読み取り/書き込み_権限を持つ資格情報が必要です。link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWSアカウントで権限を付与する方法を確認する"^]です。
* 設定または構成の修正を選択する前に、各推奨事項をよく確認してください。



NOTE: 修正プロセスによって、インスタンスのダウンタイムやサービスの中断が発生する可能性があります。構成の問題の修正を選択する前に、推奨事項をよく確認してください。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、* Well-architected status *列に移動し、修正するファイルシステムの問題を選択します。
. ファイルシステム用に設計されたダッシュボードで、構成の問題をカテゴリ、サブカテゴリ、ステータス、重大度、およびタグでフィルタリングします。
. ドロップダウン矢印を選択すると、構成の推奨事項が表示されます。推奨事項をよく確認してください。
+
推奨事項には、最適化されていない構成のベストプラクティスと潜在的な落とし穴が記載されています。

. [To]*[Fix]*を選択します。
+
[表示して修正]*がオプションの場合は、修正する影響を受けるボリュームを選択します。

. ダイアログに表示されるサマリー項目とアクション項目を確認して、問題の修正を選択した場合の動作を確認します。処理によっては、インスタンスの停止やサービスの中断が発生することがあります。
. 構成の問題を修正するには、*[続行]*を選択します。


.結果
問題を修正するプロセスが開始されます。アカウント設定メニューを選択し、*トラッカー*を選択して操作のステータスを表示します。
