---
sidebar: sidebar 
permalink: improve-configurations.html 
keywords: implement best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: BlueXP  Workload Factory for Databasesは、Microsoft SQL Serverの構成をスキャンし、優れた運用性の実現に役立つ分析情報と推奨事項を提供します。 
---
= 適切に設計されたファイルシステム構成の実装
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
構成分析のインサイトと推奨事項を使用して、BlueXP  ワークロードファクトリを活用し、FSx for ONTAPファイルシステムのベストプラクティスを実装します。信頼性、セキュリティ、効率性、パフォーマンス、コストが最適化されていないシステムでは、問題を簡単に見つけて、アーキテクチャを改善するための措置を講じることができます。

.タスクの内容
BlueXP  は、Amazon FSx for NetApp ONTAPのファイルシステム導入構成を日 々 分析しています。日次分析では、ファイルシステムがベストプラクティスに準拠するように構成の問題を自動的に修正するためのオプションとともに、分析情報と推奨事項が提供されます。

ファイルシステムの構成の問題に関する推奨事項を確認し、ワークロードファクトリコンソール内のストレージインベントリから問題を修正することができます。

分析対象:: Workload Factoryは、FSx for ONTAPファイルシステムの次の構成について、適切に設計されたステータスを分析します。
+
--
* SSD容量しきい値
* データの階層化
* スケジュールされたローカルSnapshot
* FSx for ONTAP バックアップ
* リモートデータレプリケーション
* ストレージの効率化


--


.開始する前に
* 読み取り専用または読み取り/書き込み権限を持つクレデンシャルが必要です。link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWSアカウントで権限を付与する方法を確認する"^]です。
* 設定または構成の修正を選択する前に、各推奨事項をよく確認してください。



NOTE: 修正プロセスによって、インスタンスのダウンタイムやサービスの中断が発生する可能性があります。構成の問題の修正を選択する前に、推奨事項をよく確認してください。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [データベース]タイルで、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、* Well-architected status *列に移動し、修正するファイルシステムの問題を選択します。
. ファイルシステム用に設計されたダッシュボードで、構成の問題をカテゴリ、サブカテゴリ、ステータス、重大度、およびタグでフィルタリングします。
. ドロップダウン矢印を選択すると、構成の推奨事項が表示されます。推奨事項をよく確認してください。
+
推奨事項には、最適化されていない構成のベストプラクティスと潜在的な落とし穴が記載されています。

. [To]*[Fix]*を選択します。
+
[表示して修正]*がオプションの場合は、修正する影響を受けるボリュームを選択します。

. ダイアログに表示されるサマリー項目とアクション項目を確認して、問題の修正を選択した場合の動作を確認します。処理によっては、インスタンスの停止やサービスの中断が発生することがあります。
. 構成の問題を修正するには、*[続行]*を選択します。


.結果
問題を修正するプロセスが開始されます。アカウント設定メニューを選択し、*トラッカー*を選択して操作のステータスを表示します。
