---
sidebar: sidebar 
permalink: increase-volume-capacity.html 
keywords: increase capacity, volume capacity 
summary: ボリュームのボリューム容量はいつでも手動で拡張できます。 
---
= ボリューム容量を拡張
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ボリュームのボリューム容量はいつでも手動で拡張できます。

必要に応じて、 link:edit-volume-autogrow.html["自動拡張機能を有効にする"] Workload Factoryでボリュームの容量を管理できます。

.タスクの内容
iSCSI LUNの場合、この処理によってホストLUNのサイズが拡張されます。容量が拡張されたら、ホストオペレーティングシステムの手順に従ってLUNの新しいサイズを検出し、LUNのファイルシステムを拡張します。

.開始する前に
ボリューム容量を拡張するには、が必要です link:manage-links.html["リンクの関連付け"]。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*の*[リンクの関連付け]*をクリックします。リンクが関連付けられたら、この操作に戻ります。

.手順
. にログインします。 link:https://console.workloads.netapp.com/["Workload Factoryコンソール"^]
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、更新するボリュームを含むファイルシステムの3つのドットメニューを選択し、*[管理]*を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [Volumes]タブで、容量を拡張するボリュームの3つのドットメニューを選択します。
. [基本的な操作]*を選択し、*[ボリューム容量の拡張]*を選択します。
. [ボリューム容量の拡張]ダイアログで、次の情報を指定します。
+
.. 大きいサイズを選択してください。
.. 必要に応じてユニットを交換します。


. [* 拡大（ * ） ] をクリックします

