---
sidebar: sidebar 
permalink: increase-file-system-capacity.html 
keywords: adjust capacity, elastic file system capacity, increase file system capacity, increase FSx capacity, decrease file system capacity, decrease FSx capacity 
summary: さまざまなアクティブワーキングセットを持つプロジェクトベースのワークロードのニーズを満たすために、FSx for ONTAPファイルシステムの SSD ストレージ容量を手動で調整します。 
---
= Workload Factory でファイルシステムの容量を調整する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
さまざまなアクティブワーキングセットを持つプロジェクトベースのワークロードのニーズを満たすために、FSx for ONTAPファイルシステムのソリッドステートドライブ (SSD) ストレージ容量を手動で調整します。

使用済みの SSD ストレージ容量が指定したしきい値を超えた場合は FSx for ONTAPファイル システムの SSD ストレージ容量を増やし、作業セットが非アクティブな場合は SSD ストレージ容量を減らしてコスト効率を向上させます。

あるいは、link:enable-auto-capacity-management.html["容量の自動管理機能を有効にする"] Workload Factory がファイル システムの容量を管理します。


NOTE: SSD ストレージ容量の削減は、第 2 世代のファイル システムでのみサポートされます。

.タスクの内容
柔軟なファイル システム容量により、ワークロードのニーズに合わせてファイル システムの容量を動的に調整できます。

ファイルシステムの容量を調整すると、FSx for ONTAPファイルシステムの IOPS に影響します。

自動的にlink:provision-iops.html["IOPSのプロビジョニング"]ファイル システムの場合、SSD 容量が 1 GiB 増加または減少するごとに、IOPS は 3 IOPS 増加または減少します。

手動で実行する場合link:provision-iops.html["IOPSのプロビジョニング"]は、ファイルシステムの容量の増加に対応するためにIOPSの割り当てを増やす必要があります。

SSDのストレージ容量の制限については、AWS FSx for NetApp ONTAPドキュメントのを参照して link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["クォータ"^] ください。

.開始する前に
ファイルシステムの容量を調整するには、まずlink:enable-auto-capacity-management.html["容量の自動管理を無効にする"]。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ストレージ タイルで、[ストレージへ移動] を選択します。
. ダッシュボードから*SSD 容量の調整*を選択します。
. 容量を調整するファイル システムを選択し、[続行] を選択します。
+
*潜在的な節約*は、容量を減らすための推奨事項です。

. SSD 容量の調整ダイアログで、*プロビジョニングされた容量*の数値を入力します。
. プロビジョニング済み容量の単位を選択します。
. * 適用 * を選択します。

