---
sidebar: sidebar 
permalink: increase-file-system-capacity.html 
keywords: increase capacity, increase file system capacity, increase FSx capacity 
summary: SSDストレージの使用容量が指定したしきい値を超えた場合は、FSx for ONTAPファイルシステムのSSDストレージ容量を手動で拡張します。 
---
= BlueXP  ワークロード工場でファイルシステムの容量を増加
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SSDストレージの使用容量が指定したしきい値を超えた場合は、FSx for ONTAPファイルシステムのSSDストレージ容量を手動で拡張します。

また、ワークロードファクトリがファイルシステムの容量を管理できるようにすることもできますlink:enable-auto-capacity-management.html["容量の自動管理機能を有効にする"]。

.タスクの内容
ファイルシステムの容量を増やすと、FSx for ONTAPファイルシステムのIOPSに影響します。

ファイルシステムの場合、 link:provision-iops.html["IOPSのプロビジョニング"] SSDの容量が1GiB増えるごとにIOPSが3 IOPS増加します。

手動で実行する場合link:provision-iops.html["IOPSのプロビジョニング"]は、ファイルシステムの容量の増加に対応するためにIOPSの割り当てを増やす必要があります。

SSDのストレージ容量の制限については、AWS FSx for NetApp ONTAPドキュメントのを参照して link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["クォータ"^] ください。

.開始する前に
ファイルシステムの容量を増やすには、最初に行う必要があります link:enable-auto-capacity-management.html["容量の自動管理を無効にする"]。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]で、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、容量を拡張するファイルシステムの3ドットメニューを選択します。
. 「 * Manage * 」を選択します。
. [Information]で、*[Capacity Distribution]*の横にある鉛筆アイコンを選択します。[Capacity Distribution]*行の上にマウスを置くと、ドロップダウン矢印の横に鉛筆のアイコンが表示されます。
. [SSDストレージサイズ]ダイアログで、*プロビジョニング済み容量*の数値を入力します。
. プロビジョニング済み容量の単位を選択します。
. * 適用 * を選択します。

