---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: このリリースの製品でサポートされていない、または正しく相互運用できないプラットフォーム、デバイス、または機能については、既知の制限事項が記載されています。これらの制限事項をよく確認してください。 
---
= 既知の制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
このリリースのWorkload Factoryでは、このリリースの製品でサポートされていない、または正しく相互運用できないプラットフォーム、デバイス、または機能については、既知の制限事項が記載されています。これらの制限事項をよく確認してください。



== 動作モード

_Read_modeは現在使用できません。



== リンク

Workload Factoryユーザーインターフェイスでレプリケーションなどの一部の操作を完了するには、リンクが必要です。



== Storage Efficiency

Storage Efficiencyは、ボリュームの作成後に無効または有効にすることはできません。



== スループット容量領域のサポート



=== スケールアップ環境

スケールアップ環境でサポートされる最大スループット容量は、米国東部（オハイオ）リージョン、米国東部（バージニア州）リージョン、米国西部（オレゴン）リージョン、およびヨーロッパ（アイルランド）です。



== スケールアウト導入

米国東部（バージニア州）、米国東部（オハイオ州）、米国西部（オレゴン州）、ヨーロッパ（アイルランド）、アジア太平洋（シドニー）の各地域では、スケールアウト環境で最大3 GB/秒と6 GB/秒のスループット容量がサポートされます。



== 容量管理

* ボリュームの自動拡張機能は、現在のところiSCSIプロトコルではサポートされていません。
* 容量の自動管理機能の実行中は、容量を手動で拡張することはできません。
* 容量の自動管理機能を無効にするには、その機能を有効にしたのと同じ権限が必要です。




== Storage VM

Storage VMの数はSKUごとに制限されます。制限を超えたStorage VMの作成はWorkload Factoryではサポートされていません。^1^

ファイルシステムあたりのSVMの最大数については、AWSのドキュメントのを参照してください link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["FSx for ONTAP Storage Virtual Machineの管理"^] 。



== iSCSIプロトコルのサポート

* iSCSIプロトコルはスケールアップ環境でのみサポートされます。^1 ^
* iSCSIプロトコルは、FlexGroupボリュームに対してのみ使用できます。^1 ^
* 1つのボリュームに設定できるLUNは1つだけです。




== リージョンのサポート

* カナダ西部(カルガリー)地域は現在サポートされていません。




== データ保護

* Snapshotは削除できません。
* FSx for ONTAPファイルシステム間のレプリケーションのみがサポートされます。
* ファイルシステムをレプリケートする場合、ファイルシステム内のすべてのボリュームが同じレプリケーションポリシーを使用します。
* リストアに使用できるのは最新のSnapshotのみです。




== Storage Savings Calculator

以下の構成の場合、Storage Savings Calculatorではコスト削減額は計算されません。

* FSx for Windowsファイルサーバ：HDDストレージタイプ
* Elastic Block Store（EBS）：st1、sc1、および標準のボリュームタイプ
* Elastic File System（EFS）:バーストスループットモード


注：

. Amazon FSx for NetApp ONTAPに適用

