---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: このリリースの製品でサポートされていない、または正しく相互運用できないプラットフォーム、デバイス、または機能については、既知の制限事項が記載されています。 
---
= Amazon FSx for NetApp ONTAPの既知の制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
このリリースの製品でサポートされていない、または正しく相互運用できないプラットフォーム、デバイス、または機能については、既知の制限事項が記載されています。これらの制限事項をよく確認してください。



== 地域サポート

次の AWS リージョンはサポートされていません。

* 中国地域
* GovCloud（米国）リージョン
* シークレットクラウド
* トップシークレットクラウド




== HAペアの追加に関する制限事項

* この処理の完了には約30分かかることがあります。
* HAペアを追加すると、HAペアの追加、IOPSのプロビジョニング、SSD容量の拡張、スループット容量の更新といった処理が制限されます。




== スループット容量領域のサポート



=== スケールアップ環境

すべての地域で最大2GB/秒のスケールアップ構成がサポートされています。スケールアップ環境でサポートされる最大スループット容量は、米国東部（オハイオ）リージョン、米国東部（バージニア州）リージョン、米国西部（オレゴン）リージョン、およびヨーロッパ（アイルランド）です。



=== スケールアウト導入

次のリージョンでは、スケールアウト展開で最大 6 GB/秒のスループット容量をサポートしています: 米国東部 (バージニア北部およびオハイオ)、米国西部 (北カリフォルニアおよびオレゴン)、欧州 (フランクフルト、アイルランド、ストックホルム)、アジア太平洋 (シンガポールおよびシドニー)。



== 容量管理

* ボリュームの自動拡張機能は、現在のところiSCSIプロトコルではサポートされていません。
* 容量の自動管理機能の実行中は、容量を手動で拡張することはできません。
* 容量の自動管理機能を無効にするには、その機能を有効にしたのと同じ権限が必要です。
* 自動容量管理が有効になっている場合、ボリュームの inode がストレージ容量に応じて増加するようにリンクが必要です。




== Storage VM

Storage VMの数はSKUごとに制限されます。制限を超えたStorage VMの作成は、ワークロード工場ではサポートされていません。^1^

ファイルシステムあたりのSVMの最大数については、AWSのドキュメントのを参照してください link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["FSx for ONTAP Storage Virtual Machineの管理"^] 。



== iSCSIプロトコルのサポート

* iSCSIプロトコルは、FlexVolボリュームに対してのみ使用できます。^1 ^
* 1つのボリュームに設定できるLUNは1つだけです。




== データ保護

* Snapshotは削除できません。
* ファイルシステムをレプリケートする場合、ファイルシステム内のすべてのボリュームが同じレプリケーションポリシーを使用します。
* 長期保持のレプリケーション関係では、最後のSnapshotのみがリストアに使用できます。
* 変更不可のスナップショットでは、次の機能はサポートされていません。
+
** 整合グループ
** FabricPool
** FlexCacheボリューム
** SMTape
** SnapMirrorアクティブ同期
** scheduleパラメータを使用したSnapMirrorポリシールール
** SnapMirror同期
** SVMデータの移動（ソースクラスタからデスティネーションクラスタにSVMを移行または再配置する場合に使用）






== Storage Savings Calculator

以下の構成の場合、Storage Savings Calculatorではコスト削減額は計算されません。

* FSx for Windowsファイルサーバ：HDDストレージタイプ
* Elastic Block Store（EBS）：st1、sc1、および標準のボリュームタイプ
* Elastic File System（EFS）:バーストスループットモード




== System Manager

System Managerでは、FSx for ONTAP接続のリンクはサポートされません。



== AWS Secrets Managerのサポート

コネクタを使用する場合、AWS Secrets Managerはサポートされません。

注：

. Amazon FSx for NetApp ONTAPに適用

