---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: ワークロードファクトリリンクは、ワークロードファクトリアカウントと1つ以上のFSx for ONTAPファイルシステム間の信頼関係と接続を作成します。 
---
= BlueXP  ワークロードファクトリリンクの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロードファクトリリンクは、ワークロードファクトリアカウントと1つ以上のFSx for ONTAPファイルシステム間の信頼関係と接続を作成します。これにより、Amazon FSx for ONTAP APIでは使用できないONTAP REST API呼び出しから、特定のファイルシステム機能を直接監視および管理できます。

ワークロードファクトリを開始するためのリンクは必要ありませんが、場合によっては、ワークロードファクトリのすべての機能とワークロード機能をロック解除するためのリンクを作成する必要があります。



== リンクが有益な理由

リンクは、 Amazon FSx for ONTAP API ではネイティブに利用できない操作をワークロードファクトリーで実行できるようにするという点で有益です。リンクによって高度なONTAP機能と自動化が実現され、FSx for ONTAPファイルシステムの管理が強化されます。

リンクを使用する利点は次のとおりです。

* このリンクにより、 BlueXP はONTAPコマンドを FSx for ONTAPファイルシステムに直接送信できるようになり、AWS がネイティブに提供する機能を超える高度なONTAP機能を利用できるようになります。
* リンクはAWS Lambdaを活用してイベントに応答するコードを実行します。このサーバーレスアプローチにより、VPC内で実行されるインスタンスへの依存が排除されます。




== リンクの仕組み

リンクはAWS Lambdaを利用します。Lambdaはイベントに応じてコードを実行し、そのコードに必要なコンピューティングリソースを自動的に管理します。作成したリンクはNetAppアカウントの一部であり、AWSアカウントに関連付けられています。

リンクを作成したら、それを 1 つまたは複数の FSx for ONTAPファイル システムに関連付けることができます。各ファイルシステムは、同じNetAppアカウント内の1つのリンクにのみ関連付けることができます。複数のNetAppアカウントがある場合は、1つのファイルシステムを別 々 のNetAppアカウントの下にある追加のリンクに関連付けることができます。

ワークロード ファクトリのストレージ ワークロードからリンクを作成し、関連付けます。

ワークロードファクトリー認証情報サービスに保存されている認証情報、または AWS Secrets Manager に保存されている認証情報を使用してリンクを認証できます。Workload Factoryは認証モードの変更をサポートしていません。



== コスト

Lambdaが実行する各トランザクションには課金が発生します。Lambdaは2つのシステム間のプロキシとして機能するため、Lambdaがファイルシステム上のONTAP REST APIにリクエストを送信したとき、およびワークロードファクトリにレスポンスを送信したときに料金が発生します。

link:https://aws.amazon.com/lambda/pricing/["AWS Lambdaの使用に関連するコストの詳細を確認する"^]



== リンクが必要な場合

Workload Factoryには、情報を表示してタスクを実行するためのリンクが必要です。リンクを必要とする操作を実行しようとしたときに、FSx for ONTAPファイル システムにリンクが関連付けられていない場合、ワークロード ファクトリーによって、操作にリンクが必要であることが通知されます。

リンクが必要な機能は次のとおりです。

* プロアクティブなメンテナンス、信頼性、コストパフォーマンスの最適化を実現する FSx for ONTAPファイルシステム構成の適切なアーキテクチャの状態
* NetApp自律型ランサムウェア保護 (ARP/AI)
* FSx for ONTAPファイルシステム全体の容量の総合的な観測性が強化されました
* ボリュームおよびストレージ VM データのレプリケーション、管理、および監視
* SMB/CIFS共有およびNFSエクスポートポリシーのプロビジョニングと管理
* FSx for ONTAPファイルシステムでのiSCSIボリュームの管理
* カスタム保護 SLA のスナップショット ポリシーの作成と管理
* 自動容量管理のためのiノード管理の強化
* 弾力的なスケーリングのためのボリューム自動拡張
* クローンの作成と管理により、即時にインプレースでデータのクローンを作成できます。
* ONTAPバージョンなどの追加メトリックをONTAPから直接表示する


方法をご確認くださいlink:create-link.html["FSx for ONTAPファイルシステムへのリンクを接続する"]。
