---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: ワークロードファクトリリンクは、ワークロードファクトリアカウントと1つ以上のFSx for ONTAPファイルシステム間の信頼関係と接続を作成します。 
---
= BlueXP  ワークロードファクトリリンクの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロードファクトリリンクは、ワークロードファクトリアカウントと1つ以上のFSx for ONTAPファイルシステム間の信頼関係と接続を作成します。これにより、Amazon FSx for ONTAP APIでは使用できないONTAP REST API呼び出しから、特定のファイルシステム機能を直接監視および管理できます。

ワークロードファクトリを開始するためのリンクは必要ありませんが、場合によっては、ワークロードファクトリのすべての機能とワークロード機能をロック解除するためのリンクを作成する必要があります。



== リンクの仕組み

リンクはAWS Lambdaを利用します。Lambdaはイベントに応じてコードを実行し、そのコードに必要なコンピューティングリソースを自動的に管理します。作成したリンクはNetAppアカウントの一部であり、AWSアカウントに関連付けられています。

リンクを作成したら、1つまたは複数のFSx for ONTAPファイルシステムに関連付けることができます。各ファイルシステムは、同じNetAppアカウント内の1つのリンクにのみ関連付けることができます。複数のNetAppアカウントがある場合は、1つのファイルシステムを別 々 のNetAppアカウントの下にある追加のリンクに関連付けることができます。

リンクは、ワークロード工場のFSx for ONTAPファイルシステムページから作成します。link:create-link.html["リンクの作成方法"] を参照してください。



== コスト

Lambdaが実行する各トランザクションには課金が発生します。Lambdaは2つのシステム間のプロキシとして機能するため、Lambdaがファイルシステム上のONTAP REST APIにリクエストを送信したとき、およびワークロードファクトリにレスポンスを送信したときに料金が発生します。

link:https://aws.amazon.com/lambda/pricing/["AWS Lambdaの使用に関連するコストの詳細を確認する"^]



== リンクが必要な場合

Workload Factoryには、情報を表示してタスクを実行するためのリンクが必要です。リンクを必要とする処理を実行しようとしたときに、FSx for ONTAPファイルシステムにリンクが関連付けられていないと、その処理にリンクが必要であるというメッセージが表示されます。その時点で新しいリンクを追加したり、FSx for ONTAPファイルシステムを既存のリンクに関連付けて操作を実行したりできます。

リンクが必要な機能は次のとおりです。

* FSx for ONTAPファイルシステムにインストールされているONTAPのバージョンの表示
* FSx for ONTAPファイルシステムでのiSCSIボリュームの管理
* ボリュームの自動拡張機能
* Snapshotポリシーの作成と管理
* レプリケーション関係の設定
* FSx for ONTAPファイルシステム間のボリュームレプリケーション
* バックアップ関係の設定
* クラウドストレージへのボリュームデータのバックアップ
* FSx for ONTAPファイルシステム内のボリュームクローン
* ONTAPから直接追加の指標を表示する（デフォルトの指標はAmazon CloudWatchで収集）
* NFSエクスポートポリシーの管理
* CIFS共有の管理

