---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Workload Factory リンクは、Workload Factory アカウントと 1 つ以上の FSx for ONTAPファイル システム間の信頼関係と接続を作成します。 
---
= NetApp Workload Factoryのリンクについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory リンクは、Workload Factory アカウントと 1 つ以上の FSx for ONTAPファイル システムの間に信頼関係と接続を作成します。これにより、 Amazon FSx for ONTAP API では利用できない特定のファイルシステム機能を、 ONTAP REST API 呼び出しから直接監視および管理できるようになります。

Workload Factory の使用を開始するためにリンクは必要ありませんが、場合によっては、Workload Factory のすべての機能とワークロード機能のロックを解除するためにリンクを作成する必要があります。



== リンクが有益な理由

リンクを使用すると、Workload Factory がAmazon FSx for ONTAP API を通じてネイティブに利用できない操作を実行できるようになるため、便利です。リンクにより、高度なONTAP機能と自動化が可能になり、FSx for ONTAPファイル システムの管理が強化されます。

リンクを使用する利点は次のとおりです。

* このリンクにより、 NetAppコンソールはONTAPコマンドを FSx for ONTAPファイルシステムに直接送信できるようになり、AWS がネイティブに提供する機能を超える高度なONTAP機能が利用できるようになります。
* リンクはAWS Lambdaを活用してイベントに応答するコードを実行します。このサーバーレスアプローチにより、VPC内で実行されるインスタンスへの依存が排除されます。




== リンクの仕組み

リンクはAWS Lambdaを利用します。Lambdaはイベントに応じてコードを実行し、そのコードに必要なコンピューティングリソースを自動的に管理します。作成したリンクはNetAppアカウントの一部であり、AWSアカウントに関連付けられています。

リンクを作成したら、それを 1 つまたは複数の FSx for ONTAPファイル システムに関連付けることができます。各ファイルシステムは、同じNetAppアカウント内の1つのリンクにのみ関連付けることができます。複数のNetAppアカウントがある場合は、1つのファイルシステムを別 々 のNetAppアカウントの下にある追加のリンクに関連付けることができます。

Workload Factory のストレージ ワークロードからリンクを作成し、関連付けます。

Workload Factory 認証情報サービスに保存されている認証情報、または AWS Secrets Manager に保存されている認証情報を使用してリンクを認証できます。ワークロード ファクトリーは認証モードの変更をサポートしていません。



== コスト

Lambda が実行するトランザクションごとに料金が発生します。  Lambda は 2 つのシステム間のプロキシとして機能するため、Lambda がファイルシステム上のONTAP REST API にリクエストを送信するとき、および応答を Workload Factory に返すときに料金が発生します。

link:https://aws.amazon.com/lambda/pricing/["AWS Lambdaの使用に関連するコストの詳細を確認する"^]



== リンクが必要な場合

ワークロード ファクトリーでは、情報を表示したりタスクを実行したりするためのリンクが必要です。リンクを必要とする操作を実行しようとしたが、FSx for ONTAPファイル システムにリンクが関連付けられていない場合、Workload Factory は操作にリンクが必要であることを通知します。

リンクが必要な機能は次のとおりです。

* プロアクティブなメンテナンス、信頼性、コストパフォーマンスの最適化を実現する FSx for ONTAPファイルシステム構成の適切なアーキテクチャの状態
* ONTAP EMSイベント監視とアラート
* NetApp自律型ランサムウェア保護 (ARP/AI)
* FSx for ONTAPファイルシステム全体の容量の総合的な観測性が強化されました
* ボリュームおよびストレージ VM データのレプリケーション、管理、および監視
* SMB/CIFS共有およびNFSエクスポートポリシーのプロビジョニングと管理
* FSx for ONTAPファイルシステムでのiSCSIボリュームの管理
* カスタム保護 SLA のスナップショット ポリシーの作成と管理
* 自動容量管理のためのiノード管理の強化
* 弾力的なスケーリングのためのボリューム自動拡張
* クローンの作成と管理により、即時にインプレースでデータのクローンを作成できます。
* ONTAPバージョンなどの追加メトリックをONTAPから直接表示する


方法をご確認くださいlink:create-link.html["FSx for ONTAPファイルシステムへのリンクを接続する"]。
