---
sidebar: sidebar 
permalink: manage-backup-schedule.html 
keywords: backup schedule, backup policy, update backups, update backup schedule, FSx for ONTAP backup 
summary: 必要に応じて、 NetApp Workload Factory で FSx for ONTAPファイル システムのバックアップ スケジュールを管理します。 
---
= FSx for ONTAPファイルシステムのバックアップスケジュールの管理
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory で FSx for ONTAPファイル システムのバックアップ スケジュールを管理します。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ストレージ タイルで、[ストレージへ移動] を選択します。
. [ストレージ] メニューから、*FSx for ONTAP* を選択します。
. *FSx for ONTAP*から、バックアップ スケジュールを更新するファイル システムのアクション メニューを選択し、*管理*を選択します。
. [Information]で、[FSx for ONTAP backup]*の横にある鉛筆のアイコンを選択します。FSx for ONTAP backup *行の上にマウスを置くと、ドロップダウン矢印の横に鉛筆のアイコンが表示されます。
. FSx for ONTAP backup *ダイアログで、以下を指定します。
+
.. *毎日の自動バックアップ*：この機能を有効または無効にします。この機能を無効にする場合は、*適用*を選択します。この機能を有効にする場合は、次の手順を実行します。
.. *自動バックアップ保持期間*：自動バックアップを保持する日数を入力します。
.. *日次自動バックアップウィンドウ*：*設定なし*（日次バックアップの開始時間を選択）または*日次バックアップの開始時間を選択*のいずれかを選択し、開始時間を指定します。
.. *週次メンテナンス時間*：*設定なし*（週次メンテナンス時間の開始時間を選択）または*週次メンテナンス時間30分の開始時間を選択*のいずれかを選択し、開始時間を指定します。


. * 適用 * を選択します。

