---
sidebar: sidebar 
permalink: manage-snapshot-policy.html 
keywords: manage snapshot policy, change snapshot policy, snapshot policies, snapshot schedule, update 
summary: Workload Factory で FSx for ONTAPボリュームのスナップショット ポリシーを管理します。スナップショット ポリシーは、システムがボリュームのスナップショットを作成する方法を定義します。 
---
= Snapshotポリシーを管理します。
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory で FSx for ONTAPボリュームのスナップショット ポリシーを管理します。スナップショット ポリシーは、システムがボリュームのスナップショットを作成する方法を定義します。

.タスクの内容
FSx for ONTAPファイルシステムでは、ボリュームのSnapshotポリシーの割り当て、変更、削除などのSnapshot管理操作は、Storage VMレベルで管理されます。Snapshotポリシーは、1つのStorage VMまたはすべてのStorage VMで共有できます。

一部の管理タスクでは、FSx for ONTAPファイル システムにリンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Workload Factoryのリンクについて学ぶ"] 。

デフォルトでは、すべてのボリュームがファイルシステムのSnapshotポリシーに関連付けられ `default` ています。ほとんどのワークロードでこのポリシーを使用することを推奨します。



== Snapshotポリシーの変更

Snapshotポリシーの名前、スケジュール、保持するコピーの数を変更したり、変更不可のSnapshotを有効または無効にしたりできます。Storage VM間でのポリシー共有を有効または無効にすることはできません。このオプションは、Snapshotポリシーの作成時にのみ使用できます。

.開始する前に
既存のスナップショット ポリシーを表示するには、リンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. *ストレージ*で、*ストレージへ移動*を選択します。
. *FSx for ONTAP* タブで、ファイル システムのアクション メニューを選択し、*管理* を選択します。
. ファイルシステムの概要で、*[Storage VMs]*タブを選択します。
. *ストレージ VM* タブから、スケジュールされたスナップショットで保護するボリュームを含むストレージ VM のアクション メニューを選択し、*詳細アクション* を選択して、*スナップショット ポリシーの管理* を選択します。
. スナップショット ポリシー管理ページで、変更するスナップショット ポリシーのアクション メニューを選択し、[編集] を選択します。
. [Edit snapshot policy]ダイアログで、Snapshotポリシーに必要な変更を加えます。
. * 適用 * を選択します。


.結果
Snapshotポリシーが更新されます。



== 書き換え不可のSnapshotを有効にする

Snapshotをロックして、保持期間中に削除されないようにします。

.開始する前に
不変のスナップショットを有効にするには、リンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. *ストレージ*で、*ストレージへ移動*を選択します。
. *FSx for ONTAP* タブで、スナップショットをロックするボリュームを含むファイルシステムのアクション メニューを選択し、*管理* を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. *ボリューム* タブから、保護するボリュームのアクションメニューを選択します。
. [データ保護操作]*、*[ Snapshot ]*を選択し、*[ Snapshotを変更不可にする]*を選択します。
. [Make a snapshot immutable]ダイアログで、次の手順を実行します。
+
.. *スナップショット名*：ロックするスナップショットを選択します。
.. [Retention Period]*を時間、日、月、または年数で設定します。
.. ステートメントを受け入れます。


. * 適用 * を選択します。


.結果
ボリュームSnapshotがロックされました。



== ボリュームへのSnapshotポリシーの割り当て

1つのボリュームにSnapshotポリシーを割り当てて、ボリュームのスケジュールされたSnapshotを作成できます。

.開始する前に
スナップショット ポリシーを割り当てるには、リンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. *ストレージ*で、*ストレージへ移動*を選択します。
. *FSx for ONTAP* タブで、スナップショット ポリシーを割り当てるボリュームを含むファイル システムのアクション メニューを選択し、*管理* を選択します。
. ファイルシステムの概要で、*[Storage VMs]*タブを選択します。
. *ストレージ VM* タブから、スケジュールされたスナップショットで保護するボリュームを含むストレージ VM のアクション メニューを選択し、*詳細アクション* を選択して、*スナップショット ポリシーの管理* を選択します。
. スナップショット ポリシー管理ページで、スナップショット ポリシーのアクション メニューを選択し、*ボリュームにポリシーを割り当てる*を選択します。
. [Snapshotポリシーの割り当て]ダイアログで、ボリュームに割り当てるSnapshotポリシーを選択し、ポリシースケジュールを確認します。
+
ポリシーに変更不可のスナップショットが含まれており、それを使用する場合は、ステートメントを受け入れます。

. [割り当て]*を選択します。


.結果
Snapshotポリシーがボリュームに割り当てられます。



== ボリュームからSnapshotポリシーを削除する

ボリュームのSnapshotが不要になった場合、または複数のボリュームに割り当てられているSnapshotポリシーを削除する場合は、ボリュームからSnapshotポリシーを削除します。が複数のボリュームに割り当てられている場合は<<Snapshotポリシーを削除します,Snapshotポリシーを削除します。>>、すべてのボリュームからそのボリュームを手動で削除する必要があります。

.開始する前に
スナップショット ポリシーを削除するには、リンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. *ストレージ*で、*ストレージへ移動*を選択します。
. *FSx for ONTAP* タブで、スナップショット ポリシーを割り当てるボリュームを含むファイル システムのアクション メニューを選択し、*管理* を選択します。
. ファイルシステムの概要で、*[Storage VMs]*タブを選択します。
. *ストレージ VM* タブから、スケジュールされたスナップショットで保護するボリュームを含むストレージ VM のアクション メニューを選択し、*詳細アクション* を選択して、*スナップショット ポリシーの管理* を選択します。
. スナップショット ポリシー管理ページで、スナップショット ポリシーのアクション メニューを選択し、*ボリュームにポリシーを割り当てる*を選択します。
. [Snapshotポリシーの割り当て]ダイアログで、*[なし]*を選択してSnapshotポリシーを削除します。
. [割り当て]*を選択します。


.結果
Snapshotポリシーがボリュームから削除されます。



== Snapshotポリシーを削除します

不要になったSnapshotポリシーを削除します。

Snapshotポリシーが複数のボリュームに割り当てられている場合、Snapshotポリシーを削除するには、すべてのボリュームから手動で削除する必要があります<<ボリュームからSnapshotポリシーを削除する,削除>>。または、ボリュームにアクセスすることもできます<<ボリュームへのSnapshotポリシーの割り当て,別のSnapshotポリシーを割り当てる>>。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. *ストレージ*で、*ストレージへ移動*を選択します。
. [ストレージ] メニューから、*FSx for ONTAP* を選択します。
. *FSx for ONTAP*から、ボリュームを含むファイルシステムのアクションメニューを選択し、*管理*を選択します。
. ファイルシステムの概要で、*[Storage VMs]*タブを選択します。
. *ストレージ VM* タブから、削除するスナップショット ポリシーを持つストレージ VM のアクション メニューを選択し、*詳細アクション* を選択して、*スナップショット ポリシーの管理* を選択します。
. スナップショット ポリシー管理ページで、削除するスナップショット ポリシーのアクション メニューを選択し、[削除] を選択します。
. [削除]ダイアログで、*[削除]*を選択してポリシーを削除します。

