---
sidebar: sidebar 
permalink: pause-resume-replication.html 
keywords: pause replication, quiesce replication, resume replication 
summary: レプリケーション関係を一時停止および再開して、ターゲットボリュームをソースボリュームにします。 
---
= NetApp Workload Factory でレプリケーション関係を一時停止および再開する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
レプリケーション関係を一時停止して、ソースボリュームからターゲットボリュームへのスケジュールされたレプリケーション更新を停止します。ターゲットボリュームは読み取り専用から読み取り/書き込みに移行します。両方のボリュームで最新のレプリケーションSnapshotが引き続き共有され、あとで再同期するための新しいベースラインとして使用されます。

.タスクの内容
一時停止しても、ソースボリュームとターゲットボリューム間のレプリケーション関係は維持されます。データ転送が一時停止し、ボリュームが独立した状態になります。ソースボリュームからデスティネーションボリュームへの変更の転送を再度有効にするには、レプリケーションを再開します。

レプリケーションを再開すると、ターゲット ボリュームへのすべての変更が元に戻され、 NetApp Workload Factory によってレプリケーションが再度有効になります。ターゲット ボリュームは読み取り/書き込みから読み取り専用に移行し、スケジュールされたレプリケーション間隔でソース ボリュームからの更新を再度受信します。レプリケーション関係を再開すると、ターゲット ボリュームは最新の初期レプリケーション スナップショットに戻り、その時点でボリューム レプリケーション プロセスが最初からやり直されます。

.開始する前に
転送の実行中に一時停止しても転送は影響を受けず、転送が完了するまで関係は「休止中」になります。現在の転送が中止された場合、転送は再開されません。



== レプリケーション関係を一時停止します。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ストレージ タイルで、[ストレージへ移動] を選択します。
. [ストレージ] メニューから、*FSx for ONTAP* を選択します。
. *FSx for ONTAP*から、更新するファイルシステムのアクションメニューを選択し、*管理*を選択します。
. ファイルシステムの概要で、*[レプリケーション関係]*タブを選択します。
. レプリケーション関係タブで、一時停止するレプリケーション関係のアクション メニューを選択します。
. [Pause（Quiesce）]*を選択します。
. [休止関係]ダイアログで*[休止]*を選択します。


.結果
関係が一時停止し、ステータスが「Paused」と表示されます。



== 一時停止したレプリケーション関係を再開します。

レプリケーション関係を再開すると、レプリケーションの停止中にデスティネーションボリュームに加えた変更はすべて削除されます。


NOTE: 最後のデータレプリケーションが行われてからソースボリュームが無効になるまでの間に元のソースボリュームに書き込まれたデータは保持されません。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ストレージ タイルで、[ストレージへ移動] を選択します。
. [ストレージ] メニューから、*FSx for ONTAP* を選択します。
. *FSx for ONTAP*から、更新するファイルシステムのアクションメニューを選択し、*管理*を選択します。
. ファイルシステムの概要で、*[レプリケーション関係]*タブを選択します。
. レプリケーション関係タブで、再開するレプリケーション関係のアクション メニューを選択します。
. [再開]*を選択します。
. [Resume relationship]ダイアログで、*[Resume]*を選択します。


.結果
関係が再開され、ステータスが「Replicated」と表示されます。
