---
sidebar: sidebar 
permalink: provision-iops.html 
keywords: iops, SSD, provision, allocate 
summary: FSx for ONTAPファイルシステムのSSD IOPSを自動でプロビジョニングまたは手動でプロビジョニング 
---
= FSx for ONTAPファイルシステム用SSD IOPSのプロビジョニング
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロード工場でFSx for ONTAPファイルシステムに対してSSD IOPSを自動的にプロビジョニングまたは手動でプロビジョニング

.タスクの内容
FSxファイルシステムに対してSSD IOPSの自動プロビジョニングを有効にすることも、IOPSを手動でプロビジョニングすることもできます。

自動プロビジョニングされるIOPSは、GiBあたり3つのIOPSとして計算されます。

IOPSを手動でプロビジョニングした場合は、前にIOPSを増やしなければならないことがありlink:increase-file-system-capacity.html["ファイルシステム容量の拡張"]ます。

IOPSの制限については、AWS FSx for NetApp ONTAPドキュメントのを参照してlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["クォータ"^]ください。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]で、*[ストレージインベントリに移動]*を選択します。
. [FSx for ONTAP *]タブで、IOPSをプロビジョニングするファイルシステムの3ドットメニューを選択し、*[Manage]*を選択します。
. [Information]で、*[IOPS allocation]*行の上にマウスを置くとドロップダウン矢印の横に表示される鉛筆のアイコンを選択します。
. [Provisioned IOPS]ダイアログで、*[Automatic]*または*[User Provisioned]*を選択します。
. [User Provisioned]*を選択した場合は、* IOPS値*を入力します。
. * 適用 * を選択します。

