---
sidebar: sidebar 
permalink: ransomware-protection.html 
keywords: ransomware, arp, autonomous protection, protect, security, detect, detection, restore, recover, threat, attack, suspect, anti-ransomware, entropy, abnormal volume activity, anti-ransomware, extension conformity, ransomware protection strategy 
summary: 自律型ランサムウェア対策は、NAS環境でワークロードを分析し、ランサムウェア攻撃の可能性がある異常なアクティビティを検出して警告します。 
---
= 自律型ランサムウェア対策でデータを保護
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
自律型ランサムウェア対策（ARP）でデータを保護：NAS（NFS / SMB）環境でワークロードを分析し、ランサムウェア攻撃の可能性がある異常なアクティビティを検出して警告する機能です。攻撃が疑われると、ARPは変更不可能な新しいスナップショットも作成し、そこからデータを復元できます。

.タスクの内容
ARPを使用して、身代金が支払われるまで攻撃者がデータを保留するサービス拒否攻撃から保護します。ARPは、以下に基づいてリアルタイムのランサムウェア検出を提供します。

* 受信データを暗号化またはプレーンテキストとして識別します。
* 以下を検出する分析：
+
** ** Entropy **：ファイル内のデータのランダム性の評価
** **ファイル拡張子タイプ**：通常の拡張子タイプと一致しない拡張子
** **ファイルIOPS **：データ暗号化による異常なボリュームアクティビティの急増




ARPは、少数のファイルのみが暗号化された後、ほとんどのランサムウェア攻撃の拡散を検出し、データを保護するためのアクションを自動的に実行し、攻撃の疑いがあることを警告します。

ARP機能は、Amazon FSx for NetApp ONTAPが実行するONTAPのバージョンに応じて自動的に更新されるため、手動で更新する必要はありません。

学習モードとアクティブモード:: ARPは最初に_learning mode_で動作し、次に自動的に_active mode_に切り替わります。
+
--
* *ラーニングモード*: ARPをイネーブルにすると、_learning mode_で実行されます。学習モードでは、FSx for ONTAPファイルシステムは、エントロピー、ファイル拡張子のタイプ、ファイルIOPSなどの分析領域に基づいてアラートプロファイルを作成します。ワークロード特性を評価するのに十分な時間、ファイルシステムがARPをラーニングモードで実行すると、Workload Factoryは自動的にARPから_ACTIVE MODE_に切り替わり、データの保護を開始します。
* *アクティブモード*：ARPが_ACTIVEモード_に切り替わると、FSx for ONTAPはARP/AIスナップショットを作成し、脅威が検出された場合にデータを保護します。
+
アクティブモードで、ファイル拡張子が異常としてフラグされている場合は、アラートを評価する必要があります。アラートに対処してデータを保護したり、アラートを誤検出としてマークしたりできます。アラートをfalse positiveとしてマークすると、アラートプロファイルが更新されます。たとえば、新しいファイル拡張子によってアラートがトリガーされ、アラートをfalse positiveとしてマークした場合、次回そのファイル拡張子が監視されたときにアラートは受信されません。



--
サポートされない構成:: 次の設定では、ARPの使用はサポートされていません。
+
--
* SAN /ブロックボリューム
* iSCSI ボリューム
* NVMeボリューム


--




== ファイルシステムに対して自律型ランサムウェア対策を有効にする

ファイルシステムのARPを有効にすると、既存のすべてのNASおよび新しく作成されたNASボリュームに対する保護が自動的に追加されます。

ARPを有効にした後、攻撃が発生し、攻撃が実際であることが判明した場合、BlueXP  Workload Factoryは、4時間ごとに最大6つのスナップショットを作成するスナップショットポリシーを自動的に設定します。各スナップショットは2~5日間ロックされます。

.開始する前に
ファイルシステムのARPを有効にするには、次link:manage-links.html["リンクの関連付け"]の手順を実行する必要があります。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*で*[リンクの関連付け]*を選択します。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]で、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、ARPを有効にするファイルシステムの3ドットメニューを選択し、* Manage *を選択します。
. [Information]で、*[Autonomous Ransomware Protection]*の横にある鉛筆アイコンを選択します。[Autonomous Ransomware Protection]行の上にマウスを置くと、ドロップダウン矢印の横に鉛筆のアイコンが表示されます。
. [Autonomous Ransomware Protection]ダイアログで、この機能を有効または無効にします。
. 続行するには、ステートメントを受け入れます。
. [適用]*を選択して変更を保存します。




== ランサムウェア攻撃を検証

攻撃が誤ったアラームであるか、本物のランサムウェアインシデントであるかを特定

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]で、*[ストレージインベントリに移動]*を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [Autonomous Ransomware Protection]タイルで[Analyze Attacks]*を選択します。
. 攻撃イベントレポートをダウンロードして、ファイルやフォルダが侵害されていないかどうかを確認し、攻撃が発生したかどうかを判断します。
. 攻撃が発生していない場合は、テーブル内のボリュームに対して* False alarm *を選択し、* Close *を選択します。
. 攻撃が発生した場合は、表のボリュームに対して* Real Attack *を選択します。[Restore compromised volume data]ダイアログが開きます。すぐにに進むか、*[閉じる]*を選択して後でリカバリプロセスを完了することができます<<ランサムウェア攻撃のあとにデータをリカバリ,データをリカバリ>>。




== ランサムウェア攻撃のあとにデータをリカバリ

攻撃が疑われると、その時点のボリュームSnapshotが作成され、そのコピーがロックされます。あとで攻撃が確認された場合は、ARPスナップショットを使用して、影響を受けたファイルまたはボリューム全体をリストアできます。

ロックされたSnapshotは保持期間が終了するまで削除できません。ただし、後で攻撃をfalse positiveとしてマークすると、ロックされたコピーは削除されます。

影響を受けるファイルと攻撃時間を把握していれば、ボリューム全体をSnapshotの1つに戻すだけでなく、さまざまなSnapshotから影響を受けるファイルを選択してリカバリできます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]で、*[ストレージインベントリに移動]*を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [Autonomous Ransomware Protection]タイルで[Analyze Attacks]*を選択します。
. 攻撃が発生した場合は、表のボリュームに対して* Real Attack *を選択します。
. [Restore compromised volume data]ダイアログで、指示に従って、ファイルレベルまたはボリュームレベルでリストアします。ほとんどの場合、ボリューム全体ではなくファイルをリストアします。
. リストアが完了したら、*[閉じる]*を選択します。


.結果
侵害されたデータが復元されました。
