---
sidebar: sidebar 
permalink: rebalance-volume.html 
keywords: rebalance capacity, volume capacity, redistribute capacity 
summary: ボリュームの容量をチェックしてリバランシングし、時間の経過とともに不均衡が生じないようにします。 
---
= ボリュームの容量のチェックとリバランシング
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
FlexGroupボリュームの容量のバランスを確認し、ボリュームの容量をリバランシングしてすべてのコンスティチュエントにファイルを均等に分散し、すべてのノードが1つのFlex Groupボリュームのワークロードに参加するようにします。

.タスクの内容
FlexGroupボリュームの容量は、2つ以上のハイアベイラビリティ（HA）ペアを使用したスケールアウトFSx for ONTAPファイルシステムで複数のコンスティチュエントに分散されます。各コンスティチュエントは、単一のファイルの最大サイズを決定するコンテナです。FSx for ONTAPでは、ファイルがすべてのコンスティチュエントに均等に分散されるため、すべてのノードが1つのFlexGroupボリュームのワークロードに参加します。

コンスティチュエントがすべてのノードに均等に分散されていないと、FlexGroupボリュームのパフォーマンスが低下します。

FlexGroupボリュームの容量のバランスの確認には、コンスティチュエントの現在のレイアウトの評価も含まれます。ボリュームの容量をリバランシングすると、BlueXP  ワークロードの工場では、偶数のコンスティチュエントで構成される新しいコンスティチュエントレイアウトが設計され、すべてのHAペアにデータが均等に分散されます。サービスは再バランス計画を実行し、それによって読み取りと書き込みの処理が改善されます。

ボリュームのリバランシングでは、新しいファイルの追加やファイルの増加によって不均衡が長期的に生じた場合に容量が再配分されます。リバランシング処理を手動で開始したら、ファイルを選択し、システムを停止せずに自動的に移動します。


NOTE: ボリュームのリバランシングはFlexGroupボリュームでのみサポートされます。



== FlexGroupボリュームのバランスを確認する

アクティブなFlexGroupボリュームのバランスを確認します。

.開始する前に
* FlexGroupボリュームのバランスは、2つ以上のHAペアで構成されたスケールアウト環境を使用するFSx for ONTAPファイルシステムでのみ使用できます。
* ボリュームの形式はFlexGroupである必要があります。
* FlexGroupボリュームのバランスを確認するには、が必要ですlink:manage-links.html["リンクの関連付け"]。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*で*[リンクの関連付け]*を選択します。リンクが関連付けられたら、この操作に戻ります。


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]*で、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、リバランシングするボリュームを含むファイルシステムの3ドットメニューを選択し、* Manage *を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [Volumes]タブで、テーブルの上部にある*[Check FlexGroup balance]*を選択します。
. FlexGroup balanceウィンドウで、FSx for ONTAPファイルシステム内のすべてのFlexGroupボリュームのバランスステータスを確認します。
+
FlexGroupボリュームがアンバランスな場合は、を検討してください<<FlexGroupボリュームのリバランシング,リバランシング>>。





== FlexGroupボリュームのリバランシング

<<FlexGroupボリュームのバランスを確認する,FlexGroupボリュームのバランスを確認する>>ボリュームのリバランシング前

.開始する前に
ボリュームをリバランシングするには、が必要です link:manage-links.html["リンクの関連付け"]。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*で*[リンクの関連付け]*を選択します。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]*で、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、リバランシングするボリュームを含むファイルシステムの3ドットメニューを選択し、* Manage *を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [Volumes]タブで、リバランシングするボリュームの3ドットメニューを選択します。
. [詳細な操作]*を選択し、*[ボリュームのリバランシング]*を選択します。
. [ボリュームの再バランス]ダイアログで、*[再バランス]*を選択します。


.結果
FlexGroupボリュームの容量がリバランシングされます。
