---
sidebar: sidebar 
permalink: rebalance-volume.html 
keywords: rebalance capacity, volume capacity, redistribute capacity 
summary: 時間の経過とともに不均衡が生じないように、ボリュームの容量をリバランシングします。 
---
= BlueXP  ワークロードファクトリでのボリューム容量のリバランシング
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
時間の経過とともに不均衡が生じないように、BlueXP  ワークロード工場でボリュームの容量をリバランシングします。

.タスクの内容
ボリュームのリバランシングでは、新しいファイルの追加やファイルの増加によって不均衡が長期的に生じた場合に容量が再配分されます。リバランシング処理を手動で開始したら、ファイルを選択し、システムを停止せずに自動的に移動します。


NOTE: ボリュームのリバランシングはFlexGroupボリュームでのみサポートされます。

.開始する前に
ボリュームをリバランシングするには、が必要です link:manage-links.html["リンクの関連付け"]。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*で*[リンクの関連付け]*を選択します。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]*で、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、リバランシングするボリュームを含むファイルシステムの3ドットメニューを選択し、* Manage *を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [Volumes]タブで、リバランシングするボリュームの3ドットメニューを選択します。
. [詳細な操作]*を選択し、*[ボリュームのリバランシング]*を選択します。
. [ボリュームの再バランス]ダイアログで、*[再バランス]*を選択します。

