---
sidebar: sidebar 
permalink: rebalance-volume.html 
keywords: rebalance capacity, volume capacity, redistribute capacity 
summary: ボリュームの容量をチェックしてリバランシングし、時間の経過とともに不均衡が生じないようにします。 
---
= ボリュームの容量のチェックとリバランシング
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
FlexGroupボリュームの容量のバランスを確認し、ボリュームの容量をリバランシングしてすべてのコンスティチュエントにファイルを均等に分散し、すべてのノードが1つのFlex Groupボリュームのワークロードに参加するようにします。

.タスクの内容
FlexGroupボリュームの容量は、2つ以上のハイアベイラビリティ（HA）ペアを使用したスケールアウトFSx for ONTAPファイルシステムで複数のコンスティチュエントに分散されます。各コンスティチュエントは、単一のファイルの最大サイズを決定するコンテナです。FSx for ONTAPでは、ファイルがすべてのコンスティチュエントに均等に分散されるため、すべてのノードが1つのFlexGroupボリュームのワークロードに参加します。

コンスティチュエントがすべてのノードに均等に分散されていないと、FlexGroupボリュームのパフォーマンスが低下します。

FlexGroupボリュームの容量のバランスの確認には、コンスティチュエントの現在のレイアウトの評価も含まれます。ボリュームの容量をリバランシングすると、BlueXP  ワークロードの工場では、偶数のコンスティチュエントで構成される新しいコンスティチュエントレイアウトが設計され、すべてのHAペアにデータが均等に分散されます。サービスは再バランス計画を実行し、それによって読み取りと書き込みの処理が改善されます。

ボリュームのリバランシングでは、新しいファイルの追加やファイルの増加によって不均衡が長期的に生じた場合に容量が再配分されます。リバランシング処理を手動で開始したら、ファイルを選択し、システムを停止せずに自動的に移動します。ボリューム転送処理はファイルシステムのリソースを消費します。


NOTE: リバランシングはFlexGroupボリュームでのみサポートされ、iSCSIまたはNVMe FlexGroupボリュームではサポートされません。



== FlexGroupボリュームのバランスを確認する

アクティブなFlexGroupボリュームのバランスを確認します。

.開始する前に
* FlexGroupボリュームのバランスは、2つ以上のHAペアで構成されたスケールアウト環境を使用するFSx for ONTAPファイルシステムでのみ使用できます。
* ボリュームの形式はFlexGroupである必要があります。
* FlexGroup ボリュームの残高を確認するには、リンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]*で、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、リバランシングするボリュームを含むファイルシステムの3ドットメニューを選択し、* Manage *を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [Volumes]タブで、テーブルの上部にある*[Check FlexGroup balance]*を選択します。
. FlexGroup balanceウィンドウで、FSx for ONTAPファイルシステム内のすべてのFlexGroupボリュームのバランスステータスを確認します。
+
FlexGroupボリュームがアンバランスな場合は、を検討してください<<FlexGroupボリュームのリバランシング,リバランシング>>。





== FlexGroupボリュームのリバランシング

負荷が分散されていない1つ以上のボリュームをリバランシングします。メンバーボリューム間でデータが再配分され、FlexGroupボリュームのリバランシングが行われます。リバランシング処理では、使用するデータ分散レイアウトによってFlexGroupメンバーボリュームが追加され、プロビジョニングされたボリュームのサイズが大きくなることがあります。


NOTE: ワークロードファクトリ管理者は、処理中にリバランシングを停止できます。

.開始する前に
* <<FlexGroupボリュームのバランスを確認する,FlexGroupボリュームのバランスを確認する>>ボリュームのリバランシング前
* ボリュームのバランスを再調整するには、リンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。
* リバランシングするボリューム上の既存のSnapshotは部分的になり、ボリュームデータのリストアには使用できませんが、リバランシング後に作成された新しいSnapshotを使用してボリュームデータをリストアできます。


.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [ストレージ]*で、*[ストレージインベントリに移動]*を選択します。
. FSx for ONTAP *タブで、リバランシングするボリュームを含むファイルシステムの3ドットメニューを選択し、* Manage *を選択します。
. ファイルシステムの概要で、*[ボリューム]*タブを選択します。
. [Volumes]タブで、テーブルの上部にある*[Check FlexGroup balance]*を選択します。
. 1つ以上のアンバランスボリュームをリバランシングするには、FlexGroup balanceウィンドウで* Rebalance *を選択します。
. 再バランスウィザードで、必要なデータ分散レイアウトを選択します。
+
** *パフォーマンス最適化*（推奨）：FlexGroupメンバーボリュームの数とボリュームのプロビジョニングサイズを増やします。NetAppのベストプラクティスに従います。
** *制限付き*：レプリケーション関係のボリュームをサポートします。FlexGroupメンバーボリュームの数とプロビジョニングされるボリュームのサイズは変わりません。選択したすべてのボリュームがレプリケーション関係に含まれている場合はデフォルトで選択されます。
** *手動*：HAペアあたりのFlexGroupメンバーボリュームの必要数を選択します。選択内容によっては、FlexGroupメンバーボリュームの数とボリュームのプロビジョニングサイズが増えることがあります。


. *スロットル*:オプション。デフォルトでは無効です。ファイルシステム上のボリューム移動の帯域幅を制限し、送信ボリュームのレプリケーショントラフィックを遅くするには、スロットルを有効にします。
+
スロットル値をMB/秒単位で入力します。

. レイアウト比較ビューを選択し、*次へ*を選択します。
+
** ボリュームレイアウトの比較
** FSx for ONTAPのレイアウトの比較


. 必要に応じて、リバランシングする前にボリューム移動のリストをダウンロードします。
. [リバランス]*を選択します。


.結果
FlexGroupに追加されるFlexGroupメンバーボリュームの数に応じて、FlexGroupボリュームメンバー移動処理は一度に1つずつ実行されます。処理が完了すると、ファイルシステムは元の値に調整されます。
