---
sidebar: sidebar 
permalink: replicate-svm-to-file-system.html 
keywords:  
summary: ストレージVMを別のFSx for ONTAPファイルシステムにレプリケートすることで、データ損失時のデータアクセスを保護することができます。 
---
= Storage VMを別のFSx for ONTAPファイルシステムにレプリケートする
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ストレージVMを別のFSx for ONTAPファイルシステムにレプリケートすることで、データ損失時のデータアクセスを保護することができます。この処理では、あるStorage VM内のすべてのボリュームが別のFSx for ONTAPファイルシステムにレプリケートされます。

.開始する前に
Storage VMを別のFSx for ONTAPファイルシステムにレプリケートするには、次の作業が必要です link:manage-links.html["リンクの関連付け"]。既存のリンクがない場合は、 link:create-link.html["リンクの作成"]を参照してください。ファイルシステムにリンクを関連付けるには、*[アカウント名]*の*[リンクの関連付け]*をクリックします。リンクが関連付けられたら、この操作に戻ります。

.手順
. Workload Factoryコンソールにログインします。
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、レプリケートするStorage VMがあるファイルシステムの3つのドットメニューを選択し、*[管理]*を選択します。
. ファイルシステムの概要で、*[Storage VMs]*タブを選択します。
. [Storage VM]タブで、SVMをレプリケートするStorage VMの3つのドットメニューを選択します。
. [Storage VMのレプリケート]*を選択します。
. [Create replication]ページの[Replication target]で、次の情報を指定します。
+
.. * FSx for ONTAPファイルシステム*：対象となるFSx for ONTAPファイルシステムのクレデンシャル、リージョン、FSx for ONTAPファイルシステム名を選択します。
.. * Storage VM名*：ドロップダウンメニューからStorage VMを選択します。
.. *ボリューム名*：ターゲットボリューム名は次の形式で自動的に生成されます `{OriginalVolumeName}_copy`。
.. *階層化ポリシー*：ターゲットボリュームに格納されているデータの階層化ポリシーを選択します。
+
_Auto_は、Workload Factory FSx for ONTAPユーザインターフェイスを使用してボリュームを作成する場合のデフォルトの階層化ポリシーです。ボリューム階層化ポリシーの詳細については、AWS FSx for NetApp ONTAPドキュメントのを参照してください link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["ボリュームのストレージ容量"^]。

.. *最大転送速度*：* Limited *を選択し、最大転送速度をMB/秒単位で入力します。または、*無制限*を選択します。
+
制限がないと、ネットワークとアプリケーションのパフォーマンスが低下する可能性があります。また、FSx for ONTAPファイルシステムは、主にディザスタリカバリに使用されるワークロードなど、重要なワークロードには無制限の転送速度を推奨します。



. [Replication settings]で、次の情報を指定します。
+
.. *レプリケーション間隔*：ソースボリュームからターゲットボリュームにSnapshotを転送する頻度を選択します。
.. *長期保存*：オプションで、長期保存用のスナップショットを有効にします。
+
長期保持を有効にする場合は、既存のポリシーを選択するか、新しいポリシーを作成して、レプリケートするSnapshotと保持する数を定義します。

+
... [Choose an existing policy]*で、ドロップダウンメニューから既存のポリシーを選択します。
... [新しいポリシーを作成する]*に、次の情報を入力します。
+
.... *ポリシー名*：ポリシー名を入力します。
.... * Snapshotポリシー*：表で、Snapshotポリシーの頻度と保持するコピーの数を選択します。Snapshotポリシーは複数選択できます。






. [ 作成（ Create ） ] をクリックします。


.結果
Storage VM内のすべてのボリュームがターゲットファイルシステムにレプリケートされます。
