---
sidebar: sidebar 
permalink: replicate-svm-to-file-system.html 
keywords:  
summary: ストレージVMを別のFSx for ONTAPファイルシステムにレプリケートすることで、データ損失時のデータアクセスを保護することができます。 
---
= Storage VMを別のFSx for ONTAPファイルシステムにレプリケートする
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory でストレージ VM を別の FSx for ONTAPファイル システムに複製すると、データ損失が発生した場合にデータ アクセスの保護層が提供されます。この操作により、1 つのストレージ VM 内のすべてのボリュームが別の FSx for ONTAPファイル システムに複製されます。

.開始する前に
ストレージ VM を別の FSx for ONTAP ファイル システムに複製するには、リンクを関連付ける必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]です。リンクが関連付けられたら、この操作に戻ります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ストレージ タイルで、[ストレージへ移動] を選択します。
. [ストレージ] メニューから、*FSx for ONTAP* を選択します。
. *FSx for ONTAP*から、レプリケートするストレージVMを含むファイルシステムのアクションメニューを選択し、*管理*を選択します。
. ファイルシステムの概要で、*[Storage VMs]*タブを選択します。
. [ストレージ VM] タブから、SVM をレプリケートするストレージ VM のアクション メニューを選択します。
. [Storage VMのレプリケート]*を選択します。
. [Create replication]ページの[Replication target]で、次の情報を指定します。
+
.. * FSx for ONTAPファイルシステム*：対象となるFSx for ONTAPファイルシステムのクレデンシャル、リージョン、FSx for ONTAPファイルシステム名を選択します。
.. * Storage VM名*：ドロップダウンメニューからStorage VMを選択します。
.. *ボリューム名*：ターゲットボリューム名は次の形式で自動的に生成されます `{OriginalVolumeName}_copy`。
.. *階層化ポリシー*：ターゲットボリュームに格納されているデータの階層化ポリシーを選択します。
+
Workload Factory FSx for ONTAPユーザー インターフェイスを使用してボリュームを作成する場合、デフォルトの階層化ポリシーは「_Auto_」です。ボリューム階層化ポリシーの詳細については、以下を参照してください。link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["ボリュームのストレージ容量"^] AWS FSx for NetApp ONTAPドキュメント。

.. *最大転送速度*：* Limited *を選択し、最大転送速度をMB/秒単位で入力します。または、*無制限*を選択します。
+
制限がないと、ネットワークとアプリケーションのパフォーマンスが低下する可能性があります。また、FSx for ONTAPファイルシステムは、主にディザスタリカバリに使用されるワークロードなど、重要なワークロードには無制限の転送速度を推奨します。



. [Replication settings]で、次の情報を指定します。
+
.. *レプリケーション間隔*：ソースボリュームからターゲットボリュームにSnapshotを転送する頻度を選択します。
.. *長期保存*：オプションで、長期保存用のスナップショットを有効にします。
+
長期保持を有効にする場合は、既存のポリシーを選択するか、新しいポリシーを作成して、レプリケートするSnapshotと保持する数を定義します。

+
... [Choose an existing policy]*で、ドロップダウンメニューから既存のポリシーを選択します。
... [新しいポリシーを作成する]*に、次の情報を入力します。
+
.... *ポリシー名*：ポリシー名を入力します。
.... * Snapshotポリシー*：表で、Snapshotポリシーの頻度と保持するコピーの数を選択します。Snapshotポリシーは複数選択できます。






. 「 * Create * 」を選択します。


.結果
Storage VM内のすべてのボリュームがターゲットファイルシステムにレプリケートされます。
