---
sidebar: sidebar 
permalink: reverse-replication.html 
keywords: reverse replication, change replication 
summary: レプリケーション関係を反転して、ターゲットボリュームをソースボリュームにします。 
---
= BlueXP  ワークロードファクトリでレプリケーション関係を反転する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ターゲットボリュームがソースボリュームになるように、BlueXP  ワークロードファクトリでレプリケーション関係を反転します。

反転操作は、次の場合にサポートされます。

* FSx for ONTAPファイルシステム×2
* FSx for ONTAPファイルシステム×1、オンプレミスのONTAPクラスタ×1


レプリケーションを停止してターゲットボリュームに変更を加えたら、それらの変更をソースボリュームにレプリケートできます。このプロセスは、一時的にターゲットボリュームを操作し、ボリュームの役割を切り替えるディザスタリカバリシナリオで一般的です。

.タスクの内容
レプリケーションを反転および再開すると、ボリュームのソースとターゲットの役割が切り替わります。ターゲットボリュームが新しいソースボリュームになり、ソースボリュームが新しいターゲットボリュームになります。逆方向の処理では、新しいターゲットボリュームの内容も新しいソースボリュームの内容で上書きされます。レプリケーションを2回反転すると、元のレプリケーション方向が再確立されます。


NOTE: 最後のデータレプリケーションが行われてからソースボリュームが無効になるまでの間に元のソースボリュームに書き込まれたデータは保持されません。

.開始する前に
新しいターゲットボリュームでの変更は新しいソースボリュームで上書きされるため、ソースボリュームとターゲットボリュームの現在と将来の役割を把握しておいてください。誤って使用すると、意図しないデータ損失が発生する可能性があります。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. FSx for ONTAP *タブで、更新するファイルシステムの3ドットメニューを選択し、* Manage *を選択します。
. ファイルシステムの概要で、*[レプリケーション関係]*タブを選択します。
. [Replication relationships]タブで、反転するレプリケーション関係の3ドットのメニューを選択します。
. [関係を反転]*を選択します。
. [Reverse relationship]ダイアログで、*[Reverse]*を選択します。

