---
sidebar: sidebar 
permalink: view-volume-details.html 
keywords: volume details, volume information 
summary: ボリュームの詳細、分散、消費、アクセス、保護を表示します。 
---
= BlueXP  ワークロードファクトリでのボリュームの詳細の表示
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ボリュームの詳細、分散、消費、アクセス、保護を表示します。

ボリュームの詳細は、ファイルシステムにボリュームが作成されたあとに表示されます。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. [Storage]で、*[Go to storage inventory]*を選択します。
. [Volumes]タブで、変更するボリュームの3つのドットからなるメニューを選択します。
. [基本的な操作]*を選択し、*[ボリュームの詳細を表示]*を選択します。
. [ボリュームの詳細]*で、タブを選択して次のボリュームの詳細を表示します。
+
.. *一般的な詳細*：ボリューム名、ボリュームUUID、ボリュームID、作成時間、状態、ボリュームタイプ（読み取り/書き込み/データ保護（RW / DP）または読み取り専用）、Snapshotポリシー名、ホストしているStorage VM（SVM）、タグが含まれます。
.. *ディストリビューション*：ホストするアグリゲート、ボリューム形式（FlexGroupまたはFlexVol）、コンスティチュエント（FlexGroupのみ）、リバランシング率（FlexGroupのみ-高、中、低）が含まれます。
.. *消費量*：サイズ、使用済みSSD、使用済み容量プール、自動拡張設定、最大拡張サイズ、 Storage Efficiencyの設定、圧縮による削減スペース、重複排除による削減スペース、階層化ポリシー、クーリング日数
.. *アクセス*：ジャンクションパス、セキュリティ形式、NFSのエクスポートポリシーとNFSのバージョン、Active Directory、CIFS共有名、ユーザまたはグループ、SMB / CIFSの権限、iSCSIのイニシエータグループとホストIQNが含まれます。
.. *保護*：ローカルスナップショット、スナップショットポリシー名、リモートレプリケーション、FSx for ONTAPバックアップが含まれます。



