---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx for netapp ontap, fsx for ontap' 
summary: Amazon FSx for NetApp ONTAPの最新情報をご確認ください。 
---
= Amazon FSx for NetApp ONTAP の最新情報
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Amazon FSx for NetApp ONTAPの最新情報をご確認ください。



== 2024年11月3日



=== ストレージインベントリのタブビュー

ストレージインベントリが2つのタブで構成されるように更新されました。

* FSx for ONTAPタブ：現在お使いのFSx for ONTAPファイルシステムが表示されます。
* コスト削減を確認するタブ：Elastic Block Store、FSx for Windows File Server、Elastic File Systemsの各ストレージシステムが表示されます。そこから、FSx for ONTAPと比較して、これらのシステムのコスト削減効果を確認できます。




== 2024年9月29日



=== リンク作成の更新

* Codeboxビューア: Codeboxがリンク作成プロセスに統合されました。操作を実行するためにAWSにリダイレクトする前に、ワークロードファクトリのCodeboxからCloudFormationテンプレートを表示およびコピーできます。
* 必要な権限: AWS CloudFormationでリンク作成を実行するために必要な権限が、ワークロードファクトリのCreate Linkウィザードで表示およびコピーできるようになりました。
* 手動リンク作成のサポート:この機能を使用すると、AWS CloudFormationでリンクARNを手動で登録してスタンドアロンで作成できます。これは、セキュリティチームまたはDevOpsチームがリンク作成プロセスを支援する場合に役立ちます。


link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["リンクの作成"]



== 2024年9月1日



=== ストレージ管理用の読み取りモードのサポート

読み取りモードはワークロード工場でのストレージ管理に使用できます。読み取りモードでは、コードとしてのインフラストラクチャテンプレートに特定の変数が入力されるように、読み取り専用権限を追加することで、基本モードのエクスペリエンスが向上します。コードとしてのインフラストラクチャテンプレートは、ワークロードファクトリに変更権限を与えることなく、AWSアカウントから直接実行できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["読み取りモードの詳細"]



=== ボリューム削除前のバックアップのサポート

ボリュームを削除する前にバックアップできるようになりました。バックアップは削除されるまでファイルシステムに残ります。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/delete-volume.html["ボリュームを削除する"]



== 2024 年 8 月 4 日



=== Terraformのサポート

CodeboxのTerraformを使用してファイルシステムとStorage VMを導入できるようになりました。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["ファイルシステムの作成"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["Storage VM を作成"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["コードボックスからTerraformを使用"]




=== Storage Calculatorに推奨されるスループットとIOPS

ストレージ計算ツールは、AWSのベストプラクティスに基づいて、FSx for ONTAPファイルシステム構成のスループットとIOPSに関する推奨事項を提示し、選択に対する最適なガイダンスを提供します。



== 2024年7月7日



=== Amazon FSx for NetApp ONTAP向けワークロードファクトリーの初版リリース

Amazon FSx for NetApp ONTAPは現在、BlueXP  ワークロード工場で一般提供されています。
