= ボリューム自動拡張の強化
:allow-uri-read: 




=== ボリューム自動拡張の強化

ビジネス ニーズやアプリケーション要件に応じて、ボリューム サイズがプロビジョニングされたサイズを超えて拡張できるように、ボリュームの自動拡張サイズを設定できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-volume-autogrow.html["ボリュームの自動拡張を有効にする"]



=== Well-Architected 分析のアップデート

Workload Factory は、FSx for ONTAP ファイルシステムを分析し、データコンパクション、圧縮、重複排除といったストレージ効率が活用されているかどうかを確認します。ストレージ効率は、ファイルシステムが利用可能なスペースをどれだけ効率的に使用しているかを測定します。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["ストレージ効率の適切なアーキテクチャの状態を表示する"]



=== ストレージダッシュボードの機能強化

本日より、Workload Factory コンソールからストレージ ワークロードを開くと、*ダッシュボード*が表示されます。新しく設計されたダッシュボードでは、ファイルシステムの数、SSD の合計容量、Well-Architected ステータスの概要、データ保護の概要、レプリケーション関係の健全性など、FSx for ONTAPシステムの全体的なビューが提供されます。



=== ボリュームタブの機能強化

ストレージ ワークロードでは、Workload Factory コンソールの FSx for ONTAPファイル システム内のボリューム タブが強化されました。機能強化には次のものが含まれます。

* *新しいカード*: SSD 容量、容量プール、自律ランサムウェア保護 (ARP)
* *新しい列*: 容量分布、使用済み SSD 容量、使用済み容量プール、SSD 効率




=== ボリューム作成時のストレージ効率のアップデート

新しいボリュームを作成すると、データの圧縮、圧縮、重複排除などのストレージ効率がデフォルトで有効になります。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Workload Factoryで新しいボリュームを作成する"]
